### ISSUE TITLE
Feature Request: optional email field

### ISSUE THREAD

**Issue by balupton** [calcom/cal.com#10015]
### Is your proposal related to a problem?

I use a specific calendar event type for scheduling calls with new contacts, in which case I already have enough of their identifying information that I only need their name during event booking (either having their email or phone number already). However, email is a required field that cannot be made optional, nor can it be removed — this is an unnecessary burden upon those I am calling, especially when they are new contacts and may not wish to disclose their email to me yet.

Currently people use cal.com event page to find a time slot with me, then message me about it, then I have to add it to my calendar instead.

I understand there are benefits to the booker providing their email - they get follow ups, calendar entry via email, and all the rest - however those should be an optional flow.

<img width="537" alt="image" src="https://github.com/calcom/cal.com/assets/61148/89bbc57d-c439-49e0-be57-9754f8418275">

^ the no toggle is impossible to select

<img width="755" alt="image" src="https://github.com/calcom/cal.com/assets/61148/a437b9c5-1b09-4738-b8d5-c08884b3efbe">

^ resulting in email being a required field

### Describe the solution you'd like

The ability to mark the email field as optional or remove it all together.

### Describe alternatives you've considered

- Creating my own booking system specifically for this use case.
- Telling people to use a fake email.

**Comment by PeerRich** [comment]
i think this can cause a lot of issues, no?

**Comment by rene-mueller** [comment]
@balupton the background why this is so is because the user receives appointment confirmations with the entered information and the generated link to the web meeting. If the user wants to cancel or reschedule the meeting, for example, this is not possible because the user has not received a link. Texts are charged and should only be used as an exception.

From your point of view, what would be the primary communication method on the system side?

**Comment by balupton** [comment]
> From your point of view, what would be the primary communication method on the system side?

There wouldn't be any.

----

Happy to have this requested rejected.

**Comment by ArnaudBD** [comment]
> @balupton the background why this is so is because the user receives appointment confirmations with the entered information and the generated link to the web meeting. If the user wants to cancel or reschedule the meeting, for example, this is not possible because the user has not received a link. Texts are charged and should only be used as an exception.
> 
> From your point of view, what would be the primary communication method on the system side?

I use it some times for phone calls. In this particular case I think the primary communication method should be the phone number.

**Comment by JamilFilho** [comment]
I would implement Cal.com on the website of a client who works as a nail designer, however, the fact that email is not optional creates a barrier to use, especially considering a context where appointments are for in-person appointments and who is scheduling the service has little facility and/or contact with technology.

In this specific scenario, my client works in a poor neighborhood in Salvador, Bahia (Brazil), many of the women who would use the scheduling system do not even have an email account, or use it.

**Comment by charleslcso** [comment]
> I would implement Cal.com on the website of a client who works as a nail designer, however, the fact that email is not optional creates a barrier to use, especially considering a context where appointments are for in-person appointments and who is scheduling the service has little facility and/or contact with technology.
> 
> In this specific scenario, my client works in a poor neighborhood in Salvador, Bahia (Brazil), many of the women who would use the scheduling system do not even have an email account, or use it.

Yes, I need to disable/optional email field too. I guess I'll pass on cal.com, no matter how good it is.

**Comment by charleslcso** [comment]
Is it possible to pre-fill the email field, since it can't be disabled?

**Comment by yanamal** [comment]
This feature request is closed as "completed", but it has not been implemented in the current version of the app, and email is still required. Can you clarify why it was closed as "completed"?

I also have a compelling use case for not requiring an email address. I am trying to run a study on Prolific where I schedule a study session with random participants. Per Prolific rules, this means that I cannot collect PII, including emails (this also means that our IRB process is much easier because they are not worried about PII). Prolific has its own way of communicating with the participants based on their participant ID. 

In theory, the participant is supposed to use their special prolific email which is not PII (and participants are not able to receive emails from external sources at that address, so in practice it's  moot placeholder anyway). But they do not do that because they are not paying attention, and it's still a hazard from a PII collection perspective. The workaround which will probably work in Cal (I haven't tried it yet) is to embed the scheduling widget and manipulate the widget pre-fill their email with their Prolific id, but it's a pain, especially with how buggy Qualtrics is (where I am embedding it). Clearly, there are use cases for not collecting emails.

**Comment by dshahrokhian** [comment]
The work-around I found is to just use a constant placeholder for all appointments.
