### ISSUE TITLE
[CAL-2129] Explicitly setting dark color-scheme on container page of embed adds a white background to embed iframe

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10032]
Demo of the bug at [https://codesandbox.io/s/color-scheme-3xvcqy?file=/public/index.html](https://codesandbox.io/s/color-scheme-3xvcqy?file=/public/index.html). Notice that there is white background beyond the bordered booker.

Why it happens [https://fvsch.com/transparent-iframes#:\~:text=the resolution was%3A-,If the color scheme of an iframe differs from embedding document%2C iframe gets an opaque canvas background appropriate to its color scheme.,-So the dark](https://fvsch.com/transparent-iframes#:\~:text=the%20resolution%20was%3A-,If%20the%20color%20scheme%20of%20an%20iframe%20differs%20from%20embedding%20document%2C%20iframe%20gets%20an%20opaque%20canvas%20background%20appropriate%20to%20its%20color%20scheme.,-So%20the%20dark)

When color-scheme is set to dark

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/13f995bd-5903-4ace-aad9-6dc647b0546e/21497b0b-e163-46fc-8172-7c00398afcd8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xM2Y5OTViZC01OTAzLTRhY2UtYWFkOS02ZGM2NDdiMDU0NmUvMjE0OTdiMGItZTE2My00NmZjLTgxNzItN2MwMDM5OGFmY2Q4IiwiaWF0IjoxNjg5Njg5Mzg3LCJleHAiOjE2ODk3NzU3ODd9.Q16QtmwMvXPths8toQlb_UF5-MAqvAX-qle6t60kWCI)

[Source image](https://github.com/calcom/cal.com/assets/1780212/131fc8ab-22cb-46b2-8de0-95fdbd9e34d2)

When color-scheme isn't set to dark

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0888c27a-fd52-4328-9aa6-a5514db86de1/969c2632-d867-4f77-8bbf-fbbd6070f4c9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wODg4YzI3YS1mZDUyLTQzMjgtOWFhNi1hNTUxNGRiODZkZTEvOTY5YzI2MzItZDg2Ny00Zjc3LThiYmYtZmJiZDYwNzBmNGM5IiwiaWF0IjoxNjg5Njg5Mzg3LCJleHAiOjE2ODk3NzU3ODd9.PibBAAmxYFgpoJGNSC2SEmTj-frYg2JKWhM5lfBp_zs)

[Source image](https://github.com/calcom/cal.com/assets/1780212/cf7c0360-3c78-4534-b8da-1c6bce62e062)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2129](https://linear.app/calcom/issue/CAL-2129/explicitly-setting-dark-color-scheme-on-container-page-of-embed-adds-a)</sub>

**Comment by saeedjabbar** [comment]
Having this same issue.

**Comment by Prabhat-D-M** [comment]
Try doing this: 
enableColorScheme={false} on next-themes (or removing color-scheme: dark from <html>) fixes the iframe/overlay rendering, and that dark mode works fine via CSS custom properties alone without the browser-level color-scheme hint.

I had a similar issue, this  fixed it.

**Comment by xapple** [comment]
I'm not sure this is really fixed — the bug still happens today. If you have `<meta name="color-scheme" content="dark">` on your website and you embed a Cal iframe, Cal renders the booker buttons and fields in dark correctly, but the area around/behind it is white.

This is because when the iframe's color-scheme differs from the embedding document's color-scheme, the browser paints an opaque canvas behind the iframe's transparent body.

There are two fixes that work.

Either by passing the page's scheme through the embed config:

```
Cal("ui", {
  theme: "dark",        // themes the booker components
  colorScheme: "dark",  // makes the iframe's color-scheme match the page
});
```

Or by forcing the scheme on the injected iframe: `.cal-inline iframe { color-scheme: light !important; }`
(you have to specify light here, counterintuitively, because that makes the iframe's color-scheme match the one Cal uses inside the iframe which stays light. The opaque canvas then disappears, and the page's dark background shows through.)

But I think it might be worth defaulting the iframe's color-scheme to match the embedding document instead, because I didn't find the "colorScheme" option in the docs, and this is still biting people. @zomars
