### ISSUE TITLE
[CAL-2157] booking free event, the confirmation loads in the modal; when booking the paid event it redirects the whole page

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10084]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2157](https://linear.app/calcom/issue/CAL-2157/booking-free-event-the-confirmation-loads-in-the-modal-when-booking)</sub>

**Comment by hariombalhara** [comment]
I quickly debugged it and found that this is the implementation behaviour of Stripe sdk. `return_url` that we provide to stripe is always opened by stripe in the top window thus breaking out of an existing iframe.

@joeauyeung You have more experience with Stripe. Do you know this behaviour or you have some inputs here?

Worst case scenario which we can always implement would be to let Stripe do the redirection on the top and we read the params there and open the embed again and pass those params in it so that we can show the success page within the embed. But that won't be a good experience.

**Comment by PeerRich** [comment]
this only affects paid bookings right?

**Comment by hariombalhara** [comment]
Yeah. This is just paid bookings because redirect is done by stripe.

Also, in this scenario user has the option to setup a custom success page, so that user still stays on his website.

**Comment by kcrimi** [comment]
With the custom success page, the user will still be navigated off the current page correct? 
The ideal experience would be to prevent the user having to find their way back to the page that they opened the modal on similar to the free events.

**Comment by joeauyeung** [comment]
@hariombalhara, we can always add `redirect: if_required`  to the confirm params for embeds. We would have to do something in the embed to signal to the user the payment was successful.

https://stripe.com/docs/js/payment_intents/confirm_payment
