### ISSUE TITLE
Misspelling when only one user is added as Admin for Organizations

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10146]
### Issue Summary

During the Organizations onboarding, the flow asks for Admins to be set ("Invite your organization admins"). If only one is invited, the notification shows a misspelling: `1 userS have been invited`.

1. Start the flow for create an organization (/settings/organizations/new)
2. In the step to "Invite your organization admins", add only one valid email
3. Click on "Continue" button
4. Wait and look for the notification

### Actual Results

- A misspelling is shown when only 1 admin is added.

### Expected Results

- When only 1 admin is added, the message should be something like: `1 user has been invited`
- When more than 1 admin is added, the message should be something like: `X users have been invited`, where X is the number of admins added.

### Technical details

- Tested on Chrome (114.0.5735.134)

### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/13b69a9b-8a5a-42f5-9845-90c620dadda8)

**Comment by dewanshchaudhari** [comment]
From what I understand https://github.com/calcom/cal.com/blob/main/packages/features/ee/organizations/components/AddNewOrgAdminsForm.tsx#L25  is responsible for checking if the input value is an array or a string and sending toast message `{{userCount}} users have been invited` if the value is an array even or `{{email}} has been invited` if the value is a string.
I think the expected results should be
- When only 1 admin is added, the message should be: `{{email}} has been invited`
- When more than 1 admin is added, the message should be:  `{{userCount}} users have been invited`

This can be fixed here https://github.com/calcom/cal.com/blob/main/packages/features/ee/organizations/components/AddNewOrgAdminsForm.tsx#L79
Since onChange always returns an array of string email_invite_team toast never shows up. We can return a string if only 1 element is present in the array.

**Comment by JunedKhan101** [comment]
Hi, I would like to pick this up, Kindly assign this issue to me.
