### ISSUE TITLE
Full day booking duration

### ISSUE THREAD

**Issue by j333t** [calcom/cal.com#10181]
### Is your proposal related to a problem?

I conduct corporate trainings and workshops for Excel. I would like a meeting type where people can just book a full day(s) or half day training.

### Describe the solution you'd like

Give custom duration slots. Right now, the max I can see is just 120 mins, which is far too less for workshops.

### Describe alternatives you've considered

google calendar appointments, but I would prefer having it all in cal

### Additional context

This could as a booking page for events too then.

### Requirement/Document

None.

**Comment by PeerRich** [comment]
we thought about this before and are not sure when and how we can offer multi-day durations

**Comment by j333t** [comment]
Wouldn't allowing for custom duration slots solve this? For e.g., I can put 1 day or 8hrs as booking duration instead of 120mins

**Comment by j333t** [comment]
ideally, it should be an input field and a dropdown for units, defaulting to hrs.
[   3] hrs
[ 25] mins
[   2] days
…

**Comment by vitis586** [comment]
I like the idea that @j333t has. The drop down with units gives us the most options. I am working with a booking for a tour guide so again hours rather than minutes. Full day tour is 420 minutes and it would be nice to see straightaway 7 hours. Minutes makes sense for shorter events, but something like tours, workshops or trainings could use the hours.

Multi day bookings are a dream but I cant think of a good way of implementing it. We currently book only the first day and the second day is agreed during further communication.
