### ISSUE TITLE
Bookings that require confirmation don't appear in booker's calendar

### ISSUE THREAD

**Issue by alix-pham** [calcom/cal.com#10191]
### Issue Summary

I set up all my bookings to "requires confirmation" at some point, and the people that missed meetings consistently reported not having the event showing up in their calendar (which was not happening before I opt on for the "requires confirmation" setting)
 
### Steps to Reproduce

1. Have an event set on "Requires confirmation" ("Always") in "Advanced" event settings
2. Send the link for the event, the booker books a meeting
3. Receive an email notifying that an event has been scheduled and awaits confirmation
4. Confirm - the event shows up in my calendar
5. Wait for people to show up but they often don't because they don't have it in their calendar :(

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual/Expected Results

I wish people wouldn't miss meetings they scheduled because it's not showing up in their calendar! 

### Technical details

I'm using Chrome and a MacBook Pro

### Evidence

It happened at least 3 times since I changed the settings.

**Comment by PeerRich** [comment]
after confirming, a calendar invite should be sent. its possible this is unrelated. i believe my events that require confirmation are being added to my calendar

**Comment by alix-pham** [comment]
They are added to my calendar, but not to the person that scheduled it and was waiting for confirmation, I believe

**Comment by Udit-takkar** [comment]
@alix-pham This could be due to the new google Calendar update.

<img width="1096" alt="Screenshot 2023-07-25 at 5 59 19 PM" src="https://github.com/calcom/cal.com/assets/53316345/2132edc7-450d-467b-ac61-7ad3cdcf8ac2">


Attendees would have to click on i know the sender the first time to allow creating event to calendar. ( check this https://cal.com/blog/google-s-new-spam-policy-may-be-affecting-your-invitations )

You can see the event is not added to my calendar

<img width="162" alt="Screenshot 2023-07-25 at 6 02 05 PM" src="https://github.com/calcom/cal.com/assets/53316345/60e2fbbc-3db1-4bbe-9ee4-16c786bcb502">

**Comment by Udit-takkar** [comment]
@keithwillcode this is not a bug. google calendar doesn't directly add invitation without clicking on "I know the sender".
