### ISSUE TITLE
[CAL-2218] Organizations: Shows as nameless in top left profile

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10310]
I just created an org and the org shows as Nameless. This should have the org name

![CleanShot 2023-07-22 at 10.21.45@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/287b48a1-4b11-4380-b539-df969677c4b1/7b899633-ac71-4b4d-afba-40fd530dca5e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yODdiNDhhMS00YjExLTQzODAtYjUzOS1kZjk2OTY3N2M0YjEvN2I4OTk2MzMtYWM3MS00YjRkLWFmYmEtNDBmZDUzMGRjYTVlIiwiaWF0IjoxNjkwMDE3ODY3LCJleHAiOjE2OTAxMDQyNjd9.MVQxAwxb-a_AsgZyxLPYk3_9N51C1CtK7T_s7BHAeyI)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2218](https://linear.app/calcom/issue/CAL-2218/organizations-shows-as-nameless-in-top-left-profile)</sub>

**Comment by leog** [comment]
@Jaibles Tested it. I think it’s not showing the Org there, it’s your username that if you don’t go through your onboarding gets a “Nameless” treatment. If you reload you should get the Org name. My guess is that is not getting the Org context due to caching, once you reload you force to refetch and triggers Org context correctly. Will take a look.

**Comment by Jaibles** [comment]
@leog while we don't have a name would it be easy to just put the email in there? Would look better than nameless I think.

**Comment by leog** [comment]
> @leog while we don't have a name would it be easy to just put the email in there? Would look better than nameless I think. 

@Jaibles of course, tackling that too
