### ISSUE TITLE
[CAL-2350] Move [type].tsx logic from getServerSideProps to getStaticProps

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#10750]
Initially only with data that never needs revalidating in between builds, such as i18n & the event type id.

<sub>[CAL-2350](https://linear.app/calcom/issue/CAL-2350/move-[type]tsx-logic-from-getserversideprops-to-getstaticprops)</sub>

**Comment by NextThread** [comment]
hi, can i work on this?

**Comment by suyash5053** [comment]
Hey, I agree with @emrysal , but the problem is using getStaticProps will lower the efficiency of page as server side rendering hydrates the page faster, Now for the matter of revalidating we can use [Caching with SSR](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props#caching-with-server-side-rendering-ssr) and headers like [state-while-revalidate](https://web.dev/stale-while-revalidate/) inside SSR. Your views @emrysal ?

**Comment by emrysal** [comment]
@keithwillcode Closing, the main reason this is on pending is due to appDir, - it's got no point if we are deprecating static props anyway (however appDir has taken a while longer than expected)
