### ISSUE TITLE
Individual user profile page - less event info shown in overview

### ISSUE THREAD

**Issue by Obiast** [calcom/cal.com#10768]
Is it possible to only display a short summary of the events in the individual user profil? 

I'd like to only see the first couple of lines as I see them in my event type page and not the whole text - making it kind of untidy. 

For example, check my current profil: www.cal.com/buchen

Another useful workaround / feature would be to categorize event types i. e. individual / group / online, so that visitors of the profile page would have to choose from the category before they see the single events with description.

Thanks for your response!

**Comment by PeerRich** [comment]
i agree this is quite long. would you mind if we just concat with ... after 3 lines?

**Comment by DYNAMICMORTAL** [comment]
I will add this feature please assign me. I have read what needs to be done while making a PR and accepting a PR. Thanking you in advance.

**Comment by Obiast** [comment]
I love you guys! Thanks for your great work!

**Comment by iamr-kumar** [comment]
@PeerRich @Obiast do you guys think turning the events into a collapsable dropdown be a better solution, where you see the first few lines for each event and then can choose to expand the ones you are interested in.

**Comment by DYNAMICMORTAL** [comment]
@iamr-kumar I think there must be navigating bar beside and clicking on each of them opens a section beside it, something like this would conserve the space and would look clean. 
If interested I can show how!

**Comment by DYNAMICMORTAL** [comment]
@iamr-kumar I was talking about something like this:-
![image](https://github.com/calcom/cal.com/assets/85486112/5a19070e-2862-4421-84cf-4b9897854872)

**Comment by DYNAMICMORTAL** [comment]
Does it look good though?

**Comment by vineetpradhan-dev** [comment]
@Obiast Initially it will show atmost 4 lines. Then you can click on show more to expand. 

https://github.com/calcom/cal.com/assets/138296762/52903e07-2a97-4ba9-a86a-9a5bb1639538

**Comment by vineetpradhan-dev** [comment]
I have created a state and ref in EventTypeDescription component. I am not sure if it is the most optimized solution. If someone comes up with better solution feel free to open a pr.

**Comment by madjed-hue** [comment]
hello Devs, 
@vineetpradhan-dev
yes you can create a state or ref to handle it using useEffect or useCallback would be better because you know the difference between them as side effect hooks.
#1st suggestion:
if you wanna truncate the events without showing the full text, you can make a function that checks the length of your events and depending on that, trigger the function:
function truncate(string, n) {
    return string?.length > n ? string.substr(0, n - 1) + "..." : string;
}
note: string is the event in our case, and n is the desired number of characters we want to show.

#2nd suggestion:
const [collapsed, setCollapsed] = useState(true)
const toggleCollapse = useCallback(()=>{
setCollapsed(!collapsed)
},[collapsed])
then add that condition to your onClick event of the show more or show less button.

**Comment by vineetpradhan-dev** [comment]
@madjed-hue Thanks for the suggestion. Using hard coded character limit is not very responsive friendly as the character might stop in the middle of the line. EventTypeDescription already use line-clamp to truncate. But thanks for useCallback I was totally forgetting about that.

**Comment by PeerRich** [comment]
we are redesigning this page and will take this into account!
