### ISSUE TITLE
Unable to use skiff as default calendar with other calendars installed

### ISSUE THREAD

**Issue by naveen-heliograph** [calcom/cal.com#10884]
### Issue Summary

Just using Skiff on my cal.com account works, although there's a big red flag that says "Something went wrong. [Skiff](https://app.cal.com/apps/skiff): Try reconnecting your calendar with all necessary permissions".
<img width="875" alt="Screenshot 2023-08-22 at 5 47 02 PM" src="https://github.com/calcom/cal.com/assets/133039393/94923dd3-69b7-459a-93bd-271adbf01edf">

The "Create events on" options don't have Skiff installed.
<img width="877" alt="Screenshot 2023-08-22 at 5 46 52 PM" src="https://github.com/calcom/cal.com/assets/133039393/f75cb5d2-2114-4776-82fd-bcc8ce9b747a">

However, I am able to book meetings and have no issues there.

### Steps to Reproduce

1. Install the skiff app
2. Check the installed apps
3. Deleting and installing does no good.

**Comment by PeerRich** [comment]
sharing this with the skiff team!

**Comment by cwaring** [comment]
I also stumbled across this today. It appears that there is currently no way to use Skiff when other calendar apps are installed, and adding the Skiff app directly breaks the entire cal.com booking form due to the error above.

### Desired result:
Enable multiple calendars in cal.com to check for time block conflicts but default using Skiff directly for managing the final booking.

**Comment by arkoc** [comment]
Any update on the issue?

**Comment by asadath1395** [comment]
We have removed Skiff from the app store, ref: https://github.com/calcom/cal.com/pull/13650. We can close this issue i believe

cc @PeerRich @keithwillcode
