### ISSUE TITLE
Previously committed/ merged translations overwritten by the crowdin translations.

### ISSUE THREAD

**Issue by sajanlamsal** [calcom/cal.com#11354]
### Issue Summary

As mentioned in the title, previously committed/ merged translations were overwritten by the crowdin translations.

### Evidence

1. [merged pull request](https://github.com/calcom/cal.com/pull/10416)
2. [overriding PR from Crowin bot](https://github.com/calcom/cal.com/commit/697e80966b0372973c6819e120a117a850e17fbc)
3. [Supporting articles](https://community.crowdin.com/t/crowdin-overrides-my-translations-on-repository-how-to-prevent-it/170)

Community-provided and merged translations should not be overridden by GitHub action.

<img width="722" alt="image" src="https://github.com/calcom/cal.com/assets/16210881/40ca5397-e2c5-4e02-83c6-c2eb090d689c">
<img width="705" alt="image" src="https://github.com/calcom/cal.com/assets/16210881/0625b830-483d-4f63-ad2a-ec0a0bc21e2a">

**Comment by PeerRich** [comment]
@p6l-richard can you investigate this?

**Comment by p6l-richard** [comment]
This looks like unexpected behavior in the crowdin github action to me, because:
- The config contains the `upload_translations: true` setting
- This setting worked for us in the past

→ Therefore:

- quick fix is to update the github action version ([PR here](https://github.com/calcom/cal.com/pull/11387))
- if this doesn't work I'll reach out to crowdin for further investigation

--

Shoutout to @sajanlamsal for this issue -- it's so clear and contains everything to swiftly dig into this. 👏

**Comment by p6l-richard** [comment]
The update of the crowdin github-action did not fix the issue.

I'm reaching out to crowdin now to investigate why the translation upload doesn't happen before the translation download.

**Comment by sajanlamsal** [comment]
@p6l-richard Thank you for the update 🙏

**Comment by sazn-heliks** [comment]
@p6l-richard Thank you for the fix and effort from your side. It is really helpful. 🙏

**Comment by sajanlamsal** [comment]
@p6l-richard Thank you for the fix and effort from your side. It is really helpful. 🙏
