### ISSUE TITLE
[bug]: Layout Shifting

### ISSUE THREAD

**Issue by rahulpandey70** [calcom/cal.com#11398]
### Issue Summary

Layout shifting, while filling basic details after login(getting started).

### Steps to Reproduce

1. Login with email
2. Then it will ask for basic details 
3. At last (step-5), At about section, write long dummy text and as soon as line chnages to next line layout shift.  

### Evidence
[CalIssue.webm](https://github.com/calcom/cal.com/assets/34403988/724c0882-a440-4cfa-89c2-93635a0c41a6)

**Comment by gutogalego** [comment]
I managed to reproduce it. It happens because of the scrollbar, not sure if really a bug. 

<img width="776" alt="Screenshot 2023-09-17 at 1 21 06 PM" src="https://github.com/calcom/cal.com/assets/31139680/5eb1c22b-2b9f-41a9-aa7d-669952f50215">
<img width="777" alt="Screenshot 2023-09-17 at 1 21 24 PM" src="https://github.com/calcom/cal.com/assets/31139680/e61c97bd-b638-41c7-b4db-260482695803">

**Comment by ChaudharyPradip** [comment]
This tends to happen because when initially the content of the page is less than 100% of the height the scrollbar is not showing up but as soon as the content gets longer the scrollbar kicks in which leads to the layout shift. This can be tackled by setting {scrollbar-gutter: stable} CSS property on HTML. It basically tells the browser to reserve the space for the scrollbar.

I'm creating a PR with the above-mentioned change.
