### ISSUE TITLE
[CAL-2482] Provide easier alternatives to prefill booking forms

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11419]
Provide and easier alternative to prefill attendee phone and address, organizer phone and address and may be more.

The current approach of providing location query param as JSON feels very raw to users. Their intuition always remain to use query params like `phone`, 'attendeeAddress' etc.

Also, explore creating a prefill URL generator or prefill embed code generator. We can have a UI showing all prefillable fields of Booking Form that user can fill and click 'Get me Prefill URL for this event-type'

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2482](https://linear.app/calcom/issue/CAL-2482/provide-easier-alternatives-to-prefill-booking-forms)</sub>

**Comment by nishchal27** [comment]
@hariombalhara can you please elaborate on your issue and requirements?

**Comment by moilejter** [comment]
I am not sure if this is the use case the OP had in mind - but in our case, we'd like to enable an attendee that successfully attended a meeting with us to be able to book a second appointment later on, without having to enter all the information they entered in the original appointment.  We were thinking we'd have to send them an invitation email for that follow-up - ideally we'd like to send them a link to a page like the public profile page, but where the events they select would auto-fill some the information we have for them, rather than asking them to enter it all again (if we sent them to the original public page).

**Comment by Tyler-Petrov** [comment]
@moilejter I agree with that.  I have the same problem.  If you're doing sales calls, and you're using cal.com for that, two call closes are hard because the user has to reenter their stuff every time.  Rescheduling the current call is what I have to do in that situation, but it's annoying
