### ISSUE TITLE
[CAL-2503] This is flagging initially right and when password entered it doesn't change.

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#11486]
This is flagging initially right and when password entered it doesn't change.

![image](https://github.com/calcom/cal.com/assets/4461358/e6043c28-e56c-4bb4-b8e8-5478809040ce)

_Originally posted by @alannnc in https://github.com/calcom/cal.com/pull/11421#discussion_r1333873425_
            

<sub>[CAL-2503](https://linear.app/calcom/issue/CAL-2503/this-is-flagging-initially-right-and-when-password-entered-it-doesnt)</sub>

**Comment by supalarry** [comment]
Closing this issue because password validation works as expected:
https://www.loom.com/share/786f320e03d04aa991b9e4c40e27a9f8

**Comment by supalarry** [comment]
Re-opening because I understood the issue with password not working was on the dev branch not main

**Comment by supalarry** [comment]
The issue was in the dev branch of [the PR](https://github.com/calcom/cal.com/pull/11421).

I pushed [a fix]([3e8470b](https://github.com/calcom/cal.com/pull/11421/commits/3e8470b8dd714f98d0f686f7830f01125c23fec7)) for this issue to the dev branch itself and now the password hint check is dynamic again:

<img width="574" alt="Screenshot 2023-10-31 at 10 06 49" src="https://github.com/calcom/cal.com/assets/42170848/298e0fa9-7f83-43af-8a18-9d2913039219">
