### ISSUE TITLE
[CAL-2522] We need to have some solid reasons to write E2E for third party apps which might need more effort to maintain

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11509]
We are planning to write unit tests in all third party apps and that would be mocking the requests to those third party app services.

Here are some of the issues that can't be caught using unit tests for apps and thus require us to write some E2E tests with those third party apps.

1. [https://threads.com/34538679100?s=ppe89JZmeP5ZHP3GT8btBy](https://threads.com/34538679100?s=ppe89JZmeP5ZHP3GT8btBy) - Missing a header in the request that was made to third party endpoint
2. [https://github.com/calcom/cal.com/pull/12250#discussion_r1384560719](https://github.com/calcom/cal.com/pull/12250#discussion_r1384560719) - This issue is difficult to be discovered by unit/integration tests as they would mock the response of google calendar API and would be as good as we mock it
3. Google Calendar API throws error when date range is too big, not possible to be discovered in unit tests.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2522](https://linear.app/calcom/issue/CAL-2522/we-need-to-have-some-solid-reasons-to-write-e2e-for-third-party-apps)</sub>

**Comment by keithwillcode** [comment]
Even these kinds of things can be unit tested if we extract these pieces of logic out (e.g. using the builder pattern).

In this case, the `Content-Type` header was excluded from the payload but let's say we had a request header builder for this integration, we could write tests asserting that the builder always include the proper headers. Then, the inner service actually making the call off to the third-party apps would use headers provided by the builder instead of having them nested in the service.

There are drawbacks to this approach, of course, as it introduces code redirection, more files, etc.

**Comment by hariombalhara** [comment]
Closing this. We have enough reasons to have e2e tests. @joeauyeung is already working on them
