### ISSUE TITLE
[CAL-2817] Cal.com Error message / Unable to remove the 'Check for Conflicts' google calendar. (video linked)

### ISSUE THREAD

**Issue by ejgennrich-joinbetter** [calcom/cal.com#11516]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cal.com configuration setting throwing an error when attempting to remove the 'check for conflicts' Google Calendar. Ideally users are able to check for conflicts on the same **or different** calendar as the one where to add events. 

### Steps to Reproduce

1. Add a google calendar where to add events.
2. Attempt to 'toggle off' the check for conflicts, or swap to a different calendar.
3. Generic Error message in the bottom right corner

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I would expect to be able to remove the 'check for conflicts calendar'

### Actual Results

- Error message 
- 
### Expected Results

- The ideal would being able to toggle off check for conflicts calendar. This has many practical reasons. 

### Technical details

Recording and audio explanation of the bug in action and the error message: https://www.loom.com/share/a840f0fdcfa147d59bd476ec93143a9f

- Browser version: Google Chrome Version 117.0.5938.92 

- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? See linked Loom video above. 

<sub>[CAL-2817](https://linear.app/calcom/issue/CAL-2817/calcom-error-message-unable-to-remove-the-check-for-conflicts-google)</sub>

**Comment by ejgennrich-joinbetter** [comment]
Any update on looking into this bug?

**Comment by vikaspatil0021** [comment]
Hey ,

I've taken a closer look at this issue, and I believe I've identified the problem. The issue seems to be originating from this specific line of code: 

```javascript
cal.isSelected || cal.externalId === data?.destinationCalendar?.externalId
```

You can locate this line within the file `cal.com/apps/web/pages/settings/my-account/calendars.tsx`. Just perform a search for "CalendarSwitch" within that file, and you'll spot it.

Here's what's happening: This line of code is responsible for ensuring that the toggle switch for a general calendar stays on by default after you install the Google Calendar app.

However, there's a bug that needs attention. This code runs every time the page loads, but it's not storing any data in the "selectedCalendar" table in the database when the toggle switch is on based on the condition in the above line. So, when you attempt to toggle it off, it tries to delete a record that doesn't actually exist. That's why you're encountering the error message that says, "Something went wrong when toggling example@gmail.com."

Here's a solution:
1. Let's go ahead and remove the following part of the line: 
```javascript
cal.externalId === data?.destinationCalendar?.externalId
```
 This part is causing the toggle to stay on all the time, even when there's no record. By removing it, all calendar options will default to the "off" state when the Google Calendar is installed. Users will need to manually toggle it on when needed.

2. To ensure that the general calendar is toggled on by default after installing the Google Calendar app, we need to create a record in the 'selectedCalendar' table immediately upon app installation

One approach is by creating a record using Prisma in the file located here:

`cal.com/packages/app-store/googlecalendar/api/callback.ts`

However, I'm not entirely certain if this is the correct method, and I must admit that I'm not familiar with how to implement this. I would greatly appreciate some guidance and assistance in this matter.

Thank you for your support.

**Comment by LuisSaybe** [comment]
@alishaz-polymath Hey, I'm an engineer who works at better health (co-worker with original issue reporter), thanks for taking a look at this, this bug has been causing quite a few issues related to our usage of cal.com. Any updates on prioritizing this issue?

**Comment by ejgennrich-joinbetter** [comment]
Hi, I'm wondering what some of these updates mean for resolution of this bug in the Production environment. Thanks!

**Comment by vikaspatil0021** [comment]
In a production environment, when you install the Google Calendar app on cal.com:

 - The 'check for conflicts' option for your main calendar (e.g., peer support coaching session) will be enabled by default, but you'll have the option to manually toggle it off without encountering any error messages.
 - Additionally, you'll be able to disable the 'peer support coaching session' calendar, and the toggle-off state will persist even after refreshing the page

**Comment by ejgennrich-joinbetter** [comment]
@vikaspatil0021 I just tested the bug fix and I am still encountering the same bug. Are you saying this bug-fix should be live, or are you saying that you're waiting for the push to push your code live? @alishaz-polymath 

Here is a quick loom video demonstration of the bug in production in our live instance of app.cal.com: https://www.loom.com/share/d3f3b390218e42dbb0dbe50d2d8b2eec

**Comment by vikaspatil0021** [comment]
@ejgennrich-joinbetter I made a pull request which still needs to be reviewed and merged by cal.com team.
Once it is merged the changes will reflect in your live instance.

**Comment by keithwillcode** [comment]
> Thanks all! @alishaz-polymath Any idea when we might expect this pull request to be reviewed and merged? Thanks!

We are reviewing today!

**Comment by ejgennrich-joinbetter** [comment]
thank you for the update @keithwillcode. Any additional timeline or how I might access the bug-fix in the latest version?

**Comment by ejgennrich-joinbetter** [comment]
Any update for this week? Thanks!

**Comment by vikaspatil0021** [comment]
@ejgennrich-joinbetter One last review regarding UX before merging.

**Comment by ejgennrich-joinbetter** [comment]
Thank you @vikaspatil0021! So close, i appreciate all of your help :) Any day now?

**Comment by ejgennrich-joinbetter** [comment]
I'm still getting this bug 😭. Any update on timeline for the UX review? @vikaspatil0021

**Comment by ejgennrich-joinbetter** [comment]
Bump! thanks!

**Comment by ejgennrich-joinbetter** [comment]
@vikaspatil0021 Any update here? I commented on the other thread as well. Speaking from the point of view of an end user, the question to UX seems small/non-blocking/doesn't pose a significant UX-risk vs. UX experience of the bug in question.

**Comment by vikaspatil0021** [comment]
@ejgennrich-joinbetter I agree with you, but I am also awaiting the team's response.

**Comment by ejgennrich-joinbetter** [comment]
[11639](https://github.com/calcom/cal.com/pull/11639) was closed and merged with [12388](https://github.com/calcom/cal.com/pull/12388)

Checking on a follow-up question where these settings appear to live in two places. @vikaspatil0021

**Comment by Udit-takkar** [comment]
@ejgennrich-joinbetter I think this bug has been fixed. I just tested it again on the latest main branch.

**Comment by ejgennrich-joinbetter** [comment]
@Udit-takkar I believe you can close this. I referenced a couple other tickets in most recent comment. Seems like this feature had been built out in two areas, or something to that effect. Closing now! Happy new year!
