### ISSUE TITLE
[CAL-2550] booker: layout shift when changing months

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11614]
https://github.com/calcom/cal.com/assets/8019099/eaecb69a-3d37-44a8-9729-9af08340bd10

<sub>[CAL-2550](https://linear.app/calcom/issue/CAL-2550/booker-layout-shift-when-changing-months)</sub>

**Comment by akarsh-jain-790** [comment]
@PeerRich Can you assign this issue to me

**Comment by gutogalego** [comment]
Hey, I tried to work and fix this, don't know if I'll have the time, so I'll just log some findings below. On Booker.tsx, line 232 we can fix the height of this component. up to 29rem it will stay still/fix, larger than that it will be glitchy. I don't really understand what's going on.

Here's the code with fixed heights [29rem]
![Screenshot 2023-09-29 at 5 54 31 PM](https://github.com/calcom/cal.com/assets/31139680/c526ab32-c303-4ea6-88b1-90b2d7dfbf3d)

It looks ok, but this size doesn't fit all the content: https://www.loom.com/share/96a02e5d90ef41fa98264a5ccfbba54a


When we update it to 32rem like so:
![Screenshot 2023-09-29 at 5 54 00 PM](https://github.com/calcom/cal.com/assets/31139680/c9ba5676-7a32-466e-8390-d1dfaf2d0239)

we get layout shifting back: https://www.loom.com/share/39c25b85b3d74bdca4417195c9618626

**Comment by gutogalego** [comment]
We can also fix this height, but it's not an ideal solution. It'd be great to have it fit the content but not shift, instead of just having a big enough div
![Screenshot 2023-09-29 at 6 23 49 PM](https://github.com/calcom/cal.com/assets/31139680/f7e11288-9803-4cc2-a282-5c7dfda7a43a)

https://www.loom.com/share/b7356381d0da4f8287824baced8cb5ac
