### ISSUE TITLE
[CAL-2603] refactor: PayPal to use their OAuth and not require users to make an app

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11791]
before:
![image](https://github.com/calcom/cal.com/assets/8019099/c792acc2-3209-412f-a024-70271a819312)

after:

![CleanShot 2023-10-10 at 13 08 49@2x](https://github.com/calcom/cal.com/assets/8019099/9e39ccdf-5ae6-4e7e-9360-c84917a1b9d8)

<sub>[CAL-2603](https://linear.app/calcom/issue/CAL-2603/refactor-paypal-to-use-their-oauth-and-not-require-users-to-make-an)</sub>

**Comment by ThyMinimalDev** [comment]
- [ ] Remove Setup Page
- [ ] install paypal app button calls paypal/add endpoint directly
- [ ] Modify paypal/add api endpoint to redirect to paypal onboarding
- [ ] create paypal/callback api endpoint, customer is redirected to this endpoint when the  paypal onboarding is completed,  this is where we create the credentials and redirect user to installed apps page
- [ ] create paypal/status endpoint, in order to know if the paypal integration is still valid

**Comment by supalarry** [comment]
Love this feature! When checking PayPal app I felt users would highly benefit from simplifying the process like this, so looking forward to it! ❤️
