### ISSUE TITLE
Lock timezone on booking page

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#11873]
For an in-person event type, it may be useful to lock the timezone on the booking page, as attendees could be coming from different timezones.

We should add a toggle 'Lock timezone' to the advanced event type settings.

**Comment by manpoffc** [comment]
I can take this one :)

**Comment by Siddharth-2382** [comment]
@CarinaWolli Instead of adding a toggle `Lock Timezone`, I made the Timezone un-clickable on the booking page itself. As the person who is going on the booking page should still be able to see what timezone they're in. But when the hover on the toggle, the cursor will change to `not-allowed` and clicking on the toggle does nothing.
Let me know what you think about it. I have attached the video in the PR. If there are any reviews, I would be glad to do the necessary changes.
