### ISSUE TITLE
[BUG]: "Undefined" Email Subject if left empty

### ISSUE THREAD

**Issue by piyushgarg-dev** [calcom/cal.com#11916]
### Issue Summary
The subject of the email is undefined if the user does not give the subject while chatting with the cal.com ai bot.

### Steps to Reproduce

1. Try to book a meeting using the cal.com AI bot
2. Leave the subject empty and send email
3. Wait for the reply from bot
4. The email subject would be "Re: undefined"

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results
<img width="1099" alt="Screenshot 2023-10-16 at 5 43 20 PM" src="https://github.com/calcom/cal.com/assets/44976328/b6c7ff5e-b842-45bf-909e-da8e37a14531">

### Expected Results

- Either the email must be rejected or the bot must set the subject to something meaningful

### Evidence
- Screenshot Added

**Comment by DexterStorey** [comment]
Question: What is the ideal subject in this case?
For now we changed it from "Re: undefined" to "Re: " as in a blank subject.

This should make it so the emails show up as a reply to the original message.

Would something like "Re: Your Cal AI Request" be better?"
What about an ai generated subject - if your email is about a booking: "Re: Cal.ai booking request"

The only problem with this would be they wouldn't show up as a reply to your original email (since it's subject is blank)

WDYT @piyushgarg-dev, @Udit-takkar ?
