### ISSUE TITLE
[CAL-2630] organizations: some teams throw 404 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12003]
@G3root the changes looks fine.

Not sure if it's related but can you look into why i get 404 on some teams?

https://github.com/calcom/cal.com/assets/53316345/3be8c75f-7b37-4fc9-9fc5-88d005c194a6

_Originally posted by @Udit-takkar in https://github.com/calcom/cal.com/pull/11737#pullrequestreview-1664782990_
            

<sub>[CAL-2630](https://linear.app/calcom/issue/CAL-2630/organizations-some-teams-throw-404)</sub>

**Comment by G3root** [comment]
@Udit-takkar are those teams published ?

**Comment by tedspare** [comment]
Maige label this

**Comment by Udit-takkar** [comment]
@G3root Oh right It could be possible but i don't see unpublished badge in /teams and I can create event types for design team and do a lot of other things also. maybe we are not handling unpublished team well in orgs

**Comment by SomayChauhan** [comment]
maybe the url should be `http://acme.cal.local:3000/team/[team-name]` instead of `http://acme.cal.local:3000/[team-name]`
i think this may be causing the issue becasue it is considering it to be a user instead of a team,
atleast that is how it is in non-org teams
![Screenshot from 2023-10-23 16-21-49](https://github.com/calcom/cal.com/assets/32706411/638a2aac-5f12-4357-bc9d-c0953fde4cbe)
works fine on adding /team/
[Screencast from 23-10-23 04:24:51 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/f676395e-3579-4606-a70b-fb529bae35a3)

**Comment by SomayChauhan** [comment]
i see it was fixed in #9558

**Comment by hariombalhara** [comment]
This issue has been fixed a few weeks back
