### ISSUE TITLE
[CAL-2734] bug: Date overrides UI bug depending on screen size

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#12406]
> Screen sizing bug in the desktop app. I'm trying to add a date override, and unless the screen is a specific size, the buttons to complete the override are unaccessible. You are unable to scroll down as well to populate the bottom half of the popup.

Reported in [discord](https://discord.com/channels/1125390093386010654/1125390093386010657/1174928440772792380)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a1e2f474-19d1-4666-bfda-30e467e32639/30464a42-a93c-4ba9-b6e4-244fa2ea2764?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMWUyZjQ3NC0xOWQxLTQ2NjYtYmZkYS0zMGU0NjdlMzI2MzkvMzA0NjRhNDItYTkzYy00YmE5LWI2ZTQtMjQ0ZmEyZWEyNzY0IiwiaWF0IjoxNzAwMjE3Mjg3LCJleHAiOjE3MDAzMDM2ODd9.z7c94qGD7vrPOjvQUrdWQbldELf-T2ldAvYMl6z0i64)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2734](https://linear.app/calcom/issue/CAL-2734/bug-date-overrides-ui-bug-depending-on-screen-size)</sub>

**Comment by ujjwalgoyal19** [comment]
### Proposal

**Problem**
Scrollbar is not present when screen size is small for the component **DateOverrideInputDialog**


**What is the root cause of that problem?**
Overflow handling is only present when the width of the screen is less than **768px**, which basically means for Mobile devices.
But whenever width of device exceeds **768px**, we **disableOverflow** in the component **DialogContent**.

We have a mediaQuery Hook isMobile for **768px** which is true when width of device is under **768px**. (You can see the same in picture below.)
And whenever it's true we **enableOverflow** in **DialogContent**.

![image](https://github.com/calcom/cal.com/assets/35370133/6cfcdc2f-6d30-43b0-9f19-50ff41687e72)

**What changes can be made in order to solve the problem?**
We can simply make **enableOverflow** true for every device irrespective of the width.

![image](https://github.com/calcom/cal.com/assets/35370133/a2f6f4a7-123a-466d-836c-7c2a2a17b26b)

PS: Sorry for the red lines my vscode is messed up.

### If there is something that I am missing then please let me know.
