### ISSUE TITLE
[CAL-2755] Next steps in invite email are broken in gmail

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12521]
This has been broken for a long time. I suggest we just remove these if we can't recreate or find the issue as this is a really bad first impression.

![CleanShot 2023-11-24 at 11.25.20@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/40423606-1960-4e8e-b5e6-b16bf20122d4/6d3d1282-21ce-40ab-87bb-6d800e66faaf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80MDQyMzYwNi0xOTYwLTRlOGUtYjVlNi1iMTZiZjIwMTIyZDQvNmQzZDEyODItMjFjZS00MGFiLTg3YmItNmQ4MDBlNjZmYWFmIiwiaWF0IjoxNzAwODI1MjU4LCJleHAiOjE3MDA5MTE2NTh9.lhICEF_Cp4HWz-D9atEweYqjM8hEIxt0PnytJFgZrEE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2755](https://linear.app/calcom/issue/CAL-2755/next-steps-in-invite-email-are-broken-in-gmail)</sub>

**Comment by Dharmavineta** [comment]
Hey, the issue seems to be already sorted out? The code already has the flex-column applied with the required gap. Also the child div is correctly styled with align-items and justify-content. 
Wonder why the issue is still open.

**Comment by ciaranha** [comment]
>  The code already has the flex-column applied with the required gap.

Does gmail support flexbox?

**Comment by Dharmavineta** [comment]
The production version doesn't have the updated code, which my fork does. I tried playing with different values through the inspect styles option in inspect menu- and yes after a bit of tweaking, it appears correctly.
The issue is that the code in my fork already has such a code, and as such there's nothing to fix.
@sean-brydon update on this please?
