### ISSUE TITLE
Impersonation and Login on users with uppercase email addresses bug

### ISSUE THREAD

**Issue by Shpadoinkle** [calcom/cal.com#12688]
#### UPDATE
- not an API only issue.
  - the front end dashboard also doesnt enforce or expect lower case email addresses, emails are saved to DB with capitals.

#### Impersonation Issue
- Saw an issue when impersonating a user,  every page returns a generic unauthorized response. 
- Turns out again it was due to the impersonated users email address containing an uppercase letter.
- Changing this users email address in the db directly solved the issue,  could not access their own profile to do so.

#### Login issue
- Users that existing in the database with with Captial letters in their email address
  - Login does not work when providing email in either lowercase or uppercase format. 
  - logic on this input to the database does not work

### Steps to Reproduce

1. Create a user via the API OR front end with capital letters in email address
2. Try to login or impersonate user,  dashboard will return unauthorized errors.

### Actual Results
- a bulk of unauthorized errors.

### Expected Results
- Normal login or impersonation.

### Technical details
v3.5.5

**Comment by sarthakgarg814** [comment]
Please Assign it to me

**Comment by zomars** [comment]
Hey @Shpadoinkle Thanks for reporting this. Just wanted to add our two cents since we stumbled with this before. Also here's a workaround you can use to sanitize your DB data:

```sql
-- Find users with uppercase characters in email
SELECT * FROM users u WHERE u.email ~ '[[:upper:]]';

-- Lowercase all user emails
UPDATE users SET email = lower(email) WHERE email ~ '[[:upper:]]';
```

I recommend running the first query first to see how many users are affected. Then run the UPDATE query to lowercase them all.

We didn't put this in a migration since there could be an edge case where there's conflicting emails like `user@example.com` and `User@example.com` would cause the UPDATE query to fail due to unique constrains.

If you do find a duplicate emails you can query their duplicate with this:

```sql
SELECT * FROM users u WHERE LOWER(u.email)=LOWER('user@example.com');
```

And then decide which one to rename/delete/etc.

Hope this helps 🙏🏽
