### ISSUE TITLE
Pressing ESC when creating a new event type directly closes the window and deletes progress.

### ISSUE THREAD

**Issue by daallgeier** [calcom/cal.com#12838]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Pressing ESC when creating a new event type directly closes the window and deletes progress. 

### Steps to Reproduce

1. Open the New Event Type Prompt
2. Type content
3. Press ESC
4. The prompt closes

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- The prompt closes and deletes all typed content.

### Expected Results

- After any new content has been added, the ESC button press creates a prompt to ask to quit the "New Event Type" Prompt. 

### Technical details

- Safari on ipadOS

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by wtLau** [comment]
Can I work on this?

**Comment by daallgeier** [comment]
I'm pretty sure clicking on taping next to the pop-up does the same. Would love to see that trigger the confirmation too.

**Comment by wtLau** [comment]
Hi @daallgeier, I spent a day trying to get the Dialog (Event Type Form) component to work with another Dialog (to prompt a exit when form is dirty). I am not able to implement it because there are limitations either with my ability or with Radix (the component library). Based on my research, it seems like Radix identify this as anti-pattern see [Use of Dialog without Trigger disscussion](https://github.com/radix-ui/primitives/discussions/1234#discussioncomment-3261126). 

The problem I am facing is the API to detect "Esc" or "empty space" is not built for controlling the Dialog state. I think if we want to enable such imperative control would require more effort into [dialog primitives implementation](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L270) and get a more granular control to perform whats needs to be done here. This [dialog poc](https://codesandbox.io/p/devbox/nostalgic-joana-mxcl6v?file=%2FApp.jsx%3A20%2C61) is the best I could archieve so far but its incomplete. Here's a copy of the [attempted PR](https://github.com/wtLau/cal.com/pull/1/files) for reference.

One thing to mention is that this dialog behaviour is consistent across the platform, I couldn't find an example where this isn't the case. If you happen to know such case please let me know! 

Thanks!

**Comment by daallgeier** [comment]
I haven't seen any counter examples across the interface.  This might/probably is an issue in other fields too.  

I filed this issue because i needed 3 attempts at creating a new calendar type this week and failed in 2 different ways because i tapped on the wrong button and just next to the field/popup and that was annoying.

**Comment by PeerRich** [comment]
ok but thats the whole point of ESC no?

**Comment by daallgeier** [comment]
not sure if it is.  its fine not to see it my way for sure. 

For these somewhat short fields it's fine i guess but for longer forms i'd be much more annoyed if stuff just got deleted this easily. I think my biggest problem with this right now comes from ESC on ipad being right next to `a` and that's unfortunate sometimes.  

Maybe there is a future form where "do you really want to go back?" speed-bump is affecting more people and bigger pieces of content.
