### ISSUE TITLE
[CAL-2939] input elements should be disabled while loading (updating or creating)

### ISSUE THREAD

**Issue by soham2k06** [calcom/cal.com#13111]
### Is your proposal related to a problem?

Most of the inputs are still accepting input even while loading. But it's leading to bugs.

### Describe the solution you'd like

Inputs should be disabled while loading.

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-2939](https://linear.app/calcom/issue/CAL-2939/input-elements-should-be-disabled-while-loading-updating-or-creating)</sub>

**Comment by soham2k06** [comment]
@Airbornharsh In almost every static (non modals) form inputs.
eg. profile settings, event updating and many more inputs which are static and not contained in any modals.
This is causing many different bugs.

**Comment by iprime2** [comment]
Hey @soham2k06 I looked into this issue The problem is that in the TextField component, the value of the disable attribute or prop is not passed, so we have to do that for each TextField component manually. We can create a const loading variable using useState, and its default value will be false. Whenever the user clicks the button, we can change the loading value to true. In a disabled prop or attribute, we can pass the loading variable.
Please let me know what you think about this.

![image](https://github.com/calcom/cal.com/assets/29702609/d7337baa-677b-471f-b8b5-425cc0093f32)

https://github.com/calcom/cal.com/assets/29702609/b3581c5a-7ec9-4bc7-bc28-383cea1db4b5
