### ISSUE TITLE
[CAL-3058] Feat request: Multiple availabilities for team events

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13480]
Right now for team events, only the default availabilities of team members are considered. 

However, there are many teams out there who want (for example) two team event types with the same members but one of the event type would have a different availability. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3058](https://linear.app/calcom/issue/CAL-3058/feat-request-multiple-availabilities-for-team-events)</sub>

**Comment by PeerRich** [comment]
urgh..  can they not just make two event types?

**Comment by maartenparmentier** [comment]
We would also very much like this feature!

Our use case:
We need 3 round robins for on-off events, e.g. 1 for each location. 

Location 1: [emp1, emp2], 2024-05-03 from 9AM to 11AM
Location 2: [emp1, emp3], 2024-05-03 from 1PM to 5PM
Location 2: [emp3, emp4], 2024-05-04 from 1PM to 5PM

People from location 1 get round robin link 1, location 2 gets link 2, etc...

Problem now is e.g. emp1 is only available for location 1 in AM, and for location in PM on May 5. We need to set a separate schedule for both locations, otherwise people in location 2 can also book in AM, which should not be the case.

For us it would be amazing to be able to set time slots per person per round robin

**Comment by maartenparmentier** [comment]
Can someone provide feedback if we can ever expect to have this functionality? If not, is there a workaround in the current product we can implement?
