### ISSUE TITLE
[CAL-3104] Open-source project is not buildable

### ISSUE THREAD

**Issue by squatica** [calcom/cal.com#13575]
### Issue Summary

Currently there are 254 imports `from "@calcom/features/ee/` in the open-source parts of the project (outside of /packages/features/ee and /apps/api). This means that it is impossible to use the actual open-source project without also using the EE licensed parts. In effect, there is no open-source cal.com.

### Steps to Reproduce

1. clone the project
2. `rm -fr ./packages/features/ee && rm -fr ./apps/api`
3. try to build the project

### Actual Results

large number of `Module not found: Can't resolve '@calcom/features/ee/...` errors

### Expected Results

should build successfully. The EE parts should be optional, or even in another repo.

### Evidence

```
grep -r 'from "@calcom/features/ee/' --exclude-dir apps/api --exclude-dir packages/features/ee/ | wc -l
> 254
```

<sub>[CAL-3104](https://linear.app/calcom/issue/CAL-3104/open-source-project-is-not-buildable)</sub>

**Comment by PeerRich** [comment]
during the installation step you can pick your license, where you can select AGPLv3, but I agree, we never thought about being able to completely remove the /ee folder.

lemme think about a way to do this, would require a decent amount of work

**Comment by zomars** [comment]
The EE folder is not meant to be removed. The license specifies on not using code from it. This decision was also made to avoid spending resources on having to develop and maintain two separate codebases.

So as far a you don't actively use enterprise features you would still be honoring the license.

**Comment by squatica** [comment]
Unfortunately the license states that the files in /ee "may only be **used in production**, if you (and any entity that you represent) have agreed to, and are in compliance with, the Cal.com Subscription Terms available at https://cal.com/terms"

Executing the code is "using" it, right? So anyone who follows your installation instructions or uses your docker image "in production" and navigates to the event-types page (editing an event type), the left menu will load `import("@components/eventtype/EventInstantTab")` which will `import InstantEventController from "./InstantEventController";` which will `import useLockedFieldsManager from "@calcom/features/ee/managed-event-types/hooks/useLockedFieldsManager";` and execute it at line 36. And that's just one of many examples, many more can be found by simply deleting features/ee and checking which errors are thrown.

All self-hosters are unknowingly breaching your commercial license, unless they modified the AGPL code to avoid those imports, in which case they are probably breaching the AGPL license by not publishing their modifications.

**Comment by JulienMalka** [comment]
I don't understand why this issue has been closed. I am very reluctant to use cal.com with the AGPLv3 as is, because the way the code is structured forces me to be in breach of the license. As of today, cal.com is not, effectively, open source software. 
Can we do something about that ? Even if it's just lay out a plan that will take some time to execute and at least *track* this problem ?

**Comment by bayraak** [comment]
Obviously they are not planning to fix this. @PeerRich you're protecting yourself via AGPLv3 from derivative changes, but you create a technically impossible self hosts with derivative license dependency hell.

I really encourage you to change the project `README` and `LICENSE` to say, this software is no `AGPLv3`. Because effectively it is not.

Somebody have a nice article about this issue: [https://isitreallyfoss.com/projects/calcom/](https://isitreallyfoss.com/projects/calcom/)
