### ISSUE TITLE
[CAL-3114] layout showing the scrollbar on mobile without need

### ISSUE THREAD

**Issue by tiagobarros01** [calcom/cal.com#13570]
### Issue Summary

The layout scrollbar on mobile is appearing inconsistently even when there is no need for it. Obs: this bug doesn't happen using local `calOrigin` (`http://localhost:3000`)

Using the default `calOrigin` value with `rick/get-rick-rolled` `calLink`:

https://github.com/calcom/cal.com/assets/69446514/c4fddaa7-599f-42fd-9854-5473acdca5c0

Using the `http://localhost:3000` `calOrigin` with `pro` `calLink` (default example):

https://github.com/calcom/cal.com/assets/69446514/38b36245-f696-41e1-aa64-a23085eda235

### Steps to Reproduce

1. Go to `inline.tsx` file;
2. Change the properties of the `<Cal />` component:
      - Remove the `calOrigin` property;
      - Change the `calLink` to `rick/get-rick-rolled`;
3. Run the `embed-react` project;
4. Change the call day several times (_video_) and you will see the scrollbar appearing and disappearing.

### Actual Results

- The scrollbar shouldn't be showing

### Expected Results

- The scrollbar shouldn't appear when it doesn't have a `max-height` defined. Maybe this is related to the production iframe? since when I change the `calOrigin` the problem doesn't happen.

### Technical details

- Browser version: Arc, Chromium 121;
- Node.js version: 18;

<sub>[CAL-3114](https://linear.app/calcom/issue/CAL-3114/layout-showing-the-scrollbar-on-mobile-without-need)</sub>

**Comment by d-szuffy** [comment]
Hi, I just recently started using cal.com and also wanted to embed it into my website and bumped into the same issue as described in this ticket. From what I've found the scrollbar is displayed due to the <iframe> having to small height. The problem is that the height specified in the style prop of <Cal /> component corresponds with the height of a <div> "cal-inline-container" not the <iframe> directly. Manually changing the height of <iframe> to at least 1051px makes the scrollbar disappear. 

<img width="2095" alt="image" src="https://github.com/calcom/cal.com/assets/72738337/d3188e15-e142-42be-963b-7efc39224779">

<img width="2076" alt="image" src="https://github.com/calcom/cal.com/assets/72738337/1a3b3969-e165-4197-bfed-0b5caebb0345">

Could someone please elaborate on this one? It is a little bit annoying. I tried go around and to reach the element from the DOM and change the height of the <iframe> when it is loaded but I was not able to do so due to the CORS errors. I know it is a minor bug, but the fix also doesn't seem complicated. 

Kind regards, 
Mateusz.
