### ISSUE TITLE
[CAL-3100] Round Robin Fairness Algorithm

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#13606]
Stop assigning to a user when a given fairness threshold is reached, even if this person is the only possible assignee, if it is determined unfair we disable this user.

Example: 
If a round-robin host is assigned to more than 5 bookings more than the other round-robin hosts, their availability won't be shown and they can't be booked. 

Things to consider: 

* This will make debugging availability issues more complex, we should think about adding something to help debug missing slots disabled because of fairness.
* How to deal with newly added hosts: If a host is getting added when other hosts already have a lot of bookings the new host can be booked many times until they reach this amount of bookings. This is not ideal and should be handled differently

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3100](https://linear.app/calcom/issue/CAL-3100/round-robin-fairness-algorithm)</sub>

**Comment by Nis-Han** [comment]
@CarinaWolli  This looks interesting.

I have some queries.

- Q1: Do we want to enforce this for all roundRobin events, or give the admin the ability to toggle the RoundRobin eventType to be fair or not.

-  Q2: Are we taking about max 5 bookings difference on a particular day, or on weekly basis? 

- Q3: What about time based fairness, for example, 1 user is booked for `2 * 1hr` meetings, while other is booked for like `7 * 15min` meetings? (I guess we can add more fairness rules with time, once a primary fairness filter is introduced).

For solving the issue of a new user being bombarded with all the new events, here are some ideas that come to my mind:
- Option 1: Compute the `maximum number of bookings` the preexisting users have on a single day for the next 3 days or so, set it as the limit for the new user's daily booking. This way, a new user on a single day will not have more booking than the maximum bookings other users have.
- Option 2: Lets assume a user to be a new user for the 1st week or month. First we calculate the round robin with new user in the usual fair round robin way. If a new users is selected, check if it violates some constraints, (Like new user already has more than 50% of bookings this day). If some constraint is violated, perform the fair round robin again excluding the new user (ie, `(max - min) < 5` is calculated without taking the new user into consideration) and assign the booking  to a pre-existing user.

> This will make debugging availability issues more complex

For this, I am thinking of adding a fairness filter after availableUsers are queried from DB. If while processing the availableUsers array, if the filter decides to disable a user due to fairness, we can log it, along with the reason of why we are disabling this user. This will help with the debugging.

**Comment by S-Tirupathi-Reddy** [comment]
h

**Comment by CarinaWolli** [comment]
> @CarinaWolli to ensure that we're meeting the requirements found in this doc [docs.google.com/document/d/1iOtRfY5AeuuhFTnWZBQazwJ2vGnbq3xlg_jiywF8aas/edit](https://docs.google.com/document/d/1iOtRfY5AeuuhFTnWZBQazwJ2vGnbq3xlg_jiywF8aas/edit)

I think this is what we want instead: https://github.com/calcom/cal.com/issues/15340

**Comment by PeerRich** [comment]
[https://github.com/calcom/cal.com/pull/17643](https://github.com/calcom/cal.com/pull/17643)
