### ISSUE TITLE
don't ask twice for phone number

### ISSUE THREAD

**Issue by mokkin** [calcom/cal.com#13744]
We are always asking for the phone number. In case something goes wrong we can easily reach the customer.
Our appointment can be held on different places, so phone calls are one option next to meetings in person or online. If the customer selects this option the number is asked again.
In this case the phone field should be prefilled by the other phone field or vice versa.

![grafik](https://github.com/calcom/cal.com/assets/2938748/da1cb002-1b73-45d3-ad13-f907bc5ee8b9)

**Comment by PeerRich** [comment]
ah i see. so you srtill want the phone number even if they use cal video, correct? 🤔 i am trying to figure out what the best way to do this is

**Comment by PeerRich** [comment]
have you thought about having two event-types instead of one as a potential solution? instead of having two locations to select from, people select the event type:

- phone call
- video call

this could be a quick fix.

unfortunately, fixing this would touch a lot of core logic as it's not meant to be mixed really (both inputs have different purposes)
