### ISSUE TITLE
[CAL-3171] New Team Members Join Org as OWNER/ADMIN

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#13773]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

invite a new team member to a sub-team in an org as an OWNER/ADMIN, notice how the player also joins the org with that role.

### Steps to Reproduce

1. create an org
2. create a new team in that org
3. to to team/[teamId]/members page - ignore the weird layout of page, created another issue for that
4. add a new team member to that team as ADMIN/OWNER

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- the new team member also joins the org with the selected role itself

### Expected Results

- we want that member to be a admin/owner of that team only not the entire organization

### Evidence

[LOOM](https://www.loom.com/share/2cce8b2c87a347678eaf0a5ca9528660?sid=93054cfa-7f8b-4bf0-a79a-04848be15cda)

<sub>[CAL-3171](https://linear.app/calcom/issue/CAL-3171/new-team-members-join-org-as-owneradmin)</sub>

**Comment by zeeshanbhati** [comment]
The user to whom the invite is sent should be a member of the organization; otherwise, the flow sends invites for both the organization and the team with the same access control.

If you follow the below-mentioned flow, you will encounter an error stating that the user needs to accept the organization invite first before being added to the team.

1. Add a user as a member of the organization but do not accept the invite.
2. Try to add the same user to a team.

The ideal approach here should be to implement a check. If the user is not a member of the organization, an error should be displayed when sending the invite. 

@zomars  Any input on this ?
