### ISSUE TITLE
[CAL-3428] [CAL-3222] Booking questions: Add file upload option

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13887]
Allow Cal.com users to add an option for file upload from their bookings questions

The booker would then be able to drag and drop or click to upload a file when filling out the booking confirmation form.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3222](https://linear.app/calcom/issue/CAL-3222/booking-questions-add-file-upload-option)</sub>

<sub>[CAL-3428](https://linear.app/calcom/issue/CAL-3428/[cal-3222]-booking-questions-add-file-upload-option)</sub>

**Comment by PeerRich** [comment]
quiet low prio, no?

**Comment by ayush-leap** [comment]
I use cal.com to let folks select time for interviews, and often people don't have a handy drive link to share their resume. would def love to add an optional file input field for the same.

I understand file hosting could be an issue here, but it should be safe to delete files after x amount of time of an event.

**Comment by ajsharp** [comment]
upvote

**Comment by ajsharp** [comment]
We have a very similar need, my guess is lots of other folks do too.

**Comment by eelior** [comment]
We have a very similar need, our clients book consultation sessions and we want to prepare to the meetings with documents they need to upload prior to the meeting.

**Comment by racso-dev** [comment]
Same need, why closed as not planned @keithwillcode  ?

**Comment by nbruneau71250** [comment]
I would love to have this option as well.

**Comment by patrickgarr** [comment]
Agreed! Bumping this… been an Acuity user for a long time but Cal.com is WAY more modern and flexible. But this is a huge must. I’m a freelancer who offers coaching and need to intake résumés or files clients want to work on during events. Additionally, the lack of being able to offer coupons, paid subscriptions for recurring events, and also being able to search history of appointments by client is really frustrating. Otherwise, I’d pay and switch in a HEARTBEAT.

**Comment by MaxAntony** [comment]
If cal.com isn't going to do it, then what alternative do we have on the market that will?
