### ISSUE TITLE
[CAL-3323] [CAL-3214] [CAL-3212] Resetting password deletes my avatar

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13883]
(This was in an org, but not sure if it happens in all accounts)

I reset my password and was logged out. When I logged back in, my avatar was deleted.

![CleanShot 2024-02-27 at 10.01.26@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5dfa4928-cd0e-4e23-861c-631c20f30f85/51f060bd-78f2-4c70-a339-a317ed681c2f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ZGZhNDkyOC1jZDBlLTRlMjMtODYxYy02MzFjMjBmMzBmODUvNTFmMDYwYmQtNzhmMi00YzcwLWEzMzktYTMxN2VkNjgxYzJmIiwiaWF0IjoxNzA5MDI4MTQ5LCJleHAiOjE3MDkxMTQ1NDl9.-AY_ruZ5e2EdlpynNWhiRn0vt7LG5O-vuPjdNC07OP8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3212](https://linear.app/calcom/issue/CAL-3212/resetting-password-deletes-my-avatar)</sub>

<sub>[CAL-3214](https://linear.app/calcom/issue/CAL-3214/[cal-3212]-resetting-password-deletes-my-avatar)</sub>

<sub>[CAL-3323](https://linear.app/calcom/issue/CAL-3323/[cal-3214]-[cal-3212]-resetting-password-deletes-my-avatar)</sub>

**Comment by therealrinku** [comment]
similar issue was happening for me too but with google login and I added a PR as well for it, not sure it's the same issue here.

turns out image url was wrong in my case,
image url was like this **https://cal.comhttps://lh3.googleusercontent.com/a/ACg8ocIlZx3JegV_-rX0TIEQPDFwusYH49h9E79G-tlsRsRXiEg=s96-c**
