### ISSUE TITLE
Booking POST API ignores status passed

### ISSUE THREAD

**Issue by mreilly-lula** [calcom/cal.com#14026]
### Issue Summary

a `POST` to `/bookings` seems to be ignoring the status passed. [This line](https://github.com/calcom/cal.com/blob/844592e15e3aa80c5280681e812ce598cd54d68a/packages/features/bookings/lib/handleNewBooking.ts#L653) looks to set the status based on the event type's requires confirmation flag alone.

If this is by design, understood. Wanted to bring it up in case it isn't.
### Steps to Reproduce

1. POST a booking for an event type that requires confirmation with status = ACCEPTED.
2. Observe that the booking will be PENDING

Thank you!!

**Comment by pradipkhomane** [comment]
In this case, if the owner of the event is not rescheduling then it gets status as pending. Let me know if this is expected behavior.

[Code Link](https://github.com/calcom/cal.com/blob/844592e15e3aa80c5280681e812ce598cd54d68a/packages/features/bookings/lib/handleNewBooking.ts#L2400)

` // If the user is not the owner of the event, new booking should be always pending.
  // Otherwise, an owner rescheduling should be always accepted.
  // Before comparing make sure that userId is set, otherwise undefined === undefined
  const userReschedulingIsOwner = !!(userId && originalRescheduledBookingOrganizerId === userId);
  const isConfirmedByDefault = (!requiresConfirmation && !paymentAppData.price) || userReschedulingIsOwner;
`

**Comment by keithwillcode** [comment]
Yes, this is the expected behavior for new bookings.
