### ISSUE TITLE
[CAL-3369] Seated event includes info despite the opt out and one member cancels - the entire event gets canceled

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14458]
I have trouble setting up an event that offers seats.

Privacy: Without a check mark in "Share attendee info" everybody still gets notified about names and email address of all other attendees

1. Cancellation: If somebody books a seat to an event and then cancel before other seats are taken, the entire event gets canceled and removed from the calendar showing availability.
   Did I get something wrong?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3369](https://linear.app/calcom/issue/CAL-3369/seated-event-includes-info-despite-the-opt-out-and-one-member-canceles)</sub>

**Comment by emrysal** [comment]
Hey @milospuac - I think this was due to you being the host. I confirmed you cannot see other attendee information if you are logged out as the owner of the event type, but if you are logged in you can see everyone.

It's also quite possible that the cancellation as an attendee removes the entire event if you are logged in as the host user. This is a minor bug if true.
