### ISSUE TITLE
[CAL-3377] Issue with stripe meta data corrupts many different endpoints

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#14482]
\[ { "code": "invalid_type", "expected": "string", "received": "undefined", "path": \[ "apps", "stripe", "currency" \], "message": "Required" } \]

Go to Sentry to see all the places it's affecting

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3377](https://linear.app/calcom/issue/CAL-3377/issue-with-stripe-meta-data-corrupts-many-different-endpoints)</sub>

**Comment by keithwillcode** [comment]
![SomethingWentWrong.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f328ba6f-43bc-4738-b6b0-146203b68e65/dd87ba73-6f82-4fd1-b284-c4d655c4b14b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mMzI4YmE2Zi00M2JjLTQ3MzgtYjZiMC0xNDYyMDNiNjhlNjUvZGQ4N2JhNzMtNmY4Mi00ZmQxLWIyODQtYzRkNjU1YzRiMTRiIiwiaWF0IjoxNzEyNjg5MzkxLCJleHAiOjE3MTI3NzU3OTF9.ipUq27lSdAEMnKboXBxM8gfr0BpusXtBn4X-rvr6YAI)

**Comment by SkipDead** [comment]
Possible way to reproduce the bug : 

**Two last actions I did :** 

1. I was trying to remove Stripe app from my account app. It did not work because I got a Bad Request error on the remove app button click.
2. I had a window on my app on the confirmation summary step. I clicked on the cancel button and confirmed it after being prompted to write a reason to cancel.

Current observed behavior : 

**integration on website**
I receive an error 500 when trying to display on my website any Event : 
![image](https://github.com/calcom/cal.com/assets/25327656/bd415a60-5bc8-4e6d-8402-c6270a0b85f5)

**behaviors on the cal dashboard**
On the dashboard of cal, I cannot access my Event.

Payload on https://app.cal.com/api/trpc/eventTypes/getByViewer? call when I look at the console : 

```json
[
    {
        "error": {
            "json": {
                "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"apps\",\n      \"stripe\",\n      \"currency\"\n    ],\n    \"message\": \"Required\"\n  }\n]",
                "code": -32603,
                "data": {
                    "code": "INTERNAL_SERVER_ERROR",
                    "httpStatus": 500,
                    "path": "getByViewer"
                }
            }
        }
    }
]
```

It looks like a validation error related to stripe possibly because of the payload ? My honest take is that for some reasons, the currency selected for a stripe payment got emptied for an unkown reason. I can visually see the error on the cancelled booking tab : 
![image](https://github.com/calcom/cal.com/assets/25327656/fcaa2e93-6818-45d2-9b4a-7fbd1b541233)

but on the others tabs shows that I have no booking. It is obivously because of the same error 500. Would say the same for the event Type page.

**Comment by sean-brydon** [comment]
Context: Me and @emrysal are doing some digging on this - we see this on the update event type and think its an issue with dirty fields. 

We are also seeing this in another few places which are looking into right now - eventType viewer

**Comment by SkipDead** [comment]
Ok thank you for the follow up.

Also, I would recommend some kind of validation / catching when a a specific event type has a problem with its schema. 


For example, I would see the error for a specific event without affecting the whole page / system.

If I have 2 event type but one of them does not pass the validation, the system could show the error only for that event type but will show the second event type regardless. 

Will make the system more robust and not lock the account because of one invalid event type.  I am not familiar with the architecture of cal so I am not sure if this check is possible to do. But it would be interesting as it seems that it is affecting the whole booking feature page and the event type page.
