### ISSUE TITLE
[CAL-3450] autosave availability after making changes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14591]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ff7a65f2-f916-4097-a70f-304baf254bcf/d27a3486-3084-45d5-8734-6474dd30d49f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mZjdhNjVmMi1mOTE2LTQwOTctYTcwZi0zMDRiYWYyNTRiY2YvZDI3YTM0ODYtMzA4NC00NWQ1LTg3MzQtNjQ3NGRkMzBkNDlmIiwiaWF0IjoxNzEzMjAwMjMxLCJleHAiOjE3MTMyODY2MzF9.5vmYrRTUqyEG4vaIrAXvwT7MEKEFHNO0NwGjjwVJlms)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3450](https://linear.app/calcom/issue/CAL-3450/autosave-availability-after-making-changes)</sub>

**Comment by manideep1428** [comment]
@PeerRich  Added a auto save gets some disadvantage , if user wants change the availability  , do changes  , for some reason he wants to undo the things it very difficult because of auto save  and also for small  changes to will hit server many times . So Adding a alert box for saving the data is best option , if user don't  want to save  he will cancel or he  want  will save the data through alert box .
Or it totally upon you choice to add auto save , I will work on it
