### ISSUE TITLE
[CAL-3511] ability to add guests via app.cal.com/bookings

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14691]
https://x.com/pbteja1998/status/1782161880854769929

<sub>[CAL-3511](https://linear.app/calcom/issue/CAL-3511/ability-to-add-guests-after-the-event-via-appcalcombookings)</sub>

**Comment by PeerRich** [comment]
we should rename: "Edit location" to "Edit" 
![CleanShot 2024-04-21 at 23 49 00@2x](https://github.com/calcom/cal.com/assets/8019099/9f6ecb0c-1d53-4d46-b1bb-eec9a33771c7)

and then in the dialog add more settings, such as "Add guests" and later more things


![CleanShot 2024-04-21 at 23 49 37@2x](https://github.com/calcom/cal.com/assets/8019099/5e4c604f-bd00-4fbf-a6e5-b8998fca62d6)

**Comment by jayeshp19** [comment]
@PeerRich, I'd be glad to take this task on. I've already begun working on it. However, I wanted to clarify the approach. Are we certain about changing "Edit Location" to "Edit"? We already have an "Edit" option at the top of the dropdown. 
![image](https://github.com/calcom/cal.com/assets/60539217/40cef171-078d-4c17-a51d-48c85c33a5eb)

I've considered two potential solutions:
1. We could introduce a new button for "Add guests" below the "Edit Location" in the dropdown.
2. Alternatively, we could transform "Edit" into a button rather than a dropdown. Clicking on it would open a dialog containing all the settings such as "Reschedule Booking", "Reschedule Request", "Change Location", "Add Guests", etc.

Please let me know what do you think?

**Comment by jayeshp19** [comment]
@PeerRich @zomars @Udit-takkar can you please suggest your inputs?

**Comment by anikdhabal** [comment]
> @PeerRich @zomars @Udit-takkar can you please suggest your inputs?

Hey @jayeshp19 I worked on it and fixed by today. By the way, I also positioned the button in the same place. Thank you.
