### ISSUE TITLE
[CAL-3734] [CAL-3735] Get bookings via API returns 500 error

### ISSUE THREAD

**Issue by pgvr** [calcom/cal.com#14735]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Get bookings via API returns 500 error.
This happens for a certain API key, that I can share with someone from [Cal.com](http://Cal.com), if need be.
For new keys that I create this request works.

### Actual Results

* Request returns 500 error

### Expected Results

* Request returns list of bookings

### Evidence

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/be8b6a38-6cf8-4138-ae01-b0dd914cfd7c/a642da69-cd66-4c6b-86cd-6d5283507201?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iZThiNmEzOC02Y2Y4LTQxMzgtYWUwMS1iMGRkOTE0Y2ZkN2MvYTY0MmRhNjktY2Q2Ni00YzZiLTg2Y2QtNmQ1MjgzNTA3MjAxIiwiaWF0IjoxNzE1ODY2Mjc1LCJleHAiOjE3NDc0MDIyNzV9.KUn8sDOBBTPiZTJdoDVwzYL83v0DdSYCtqDoNMEVzFU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3734](https://linear.app/calcom/issue/CAL-3734/[cal-3735]-get-bookings-via-api-returns-500-error)</sub>

**Comment by sumitdashrathgupta** [comment]
1) Verify API Key: Ensure that the API key you're using for the requests causing the 500 error is correct and active. Check for any typos or discrepancies in the key.
2) Check API Documentation: Review the documentation for the API endpoint you're trying to access. Make sure you're forming the request correctly, including any required headers or parameters.
3) Review Error Logs: If possible, access error logs from the API server to see if there's more specific information about why the request is failing. This can provide insights into the root cause of the issue.
4) Compare Requests: Compare the requests made with the working API keys to the one that's causing the error. Look for any differences in headers, parameters, or payload that could be contributing to the problem.
5) Test in Isolation: If you have a sandbox or test environment for the API, try making the problematic request there. This can help determine if the issue is specific to the production environment or if it's related to the API key itself.
6) Contact Support: If you're still unable to resolve the issue, reach out to the support team for the API provider. Provide them with details about the problem, including the specific endpoint, request payload, and any error messages received. If necessary, share the API key causing the problem with them for further investigation.
7) Check for Rate Limits or Restrictions: Ensure that the API key causing the issue isn't subject to any rate limits or access restrictions that could be causing the 500 error. Review the API provider's documentation for any relevant information in this regard.

**Comment by keithwillcode** [comment]
@pgvr Are you still experiencing this issue? We've fixed many problems with this endpoint
