### ISSUE TITLE
[CAL-3572] Slots API getting a blank response (managed events)

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14802]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3572](https://linear.app/calcom/issue/CAL-3572/slots-api-getting-a-blank-response-managed-events)</sub>

**Comment by Shaik-Sirajuddin** [comment]
When creating a managed event type , a template is created and the template is cloned for each assigned user.
The copy assigned to user has availability set and is bookable, the original template is not bookable ( as its a template ).

Slots api returns response accordingly as per user schedule when trying to access a users instance of managed event.
It returns empty response when passing template's eventId.
It seems to be match the expected behaviour .

**Comment by Shaik-Sirajuddin** [comment]
/team/pro/managetest

a link to template opens booking page while showing no available slots
I think it should redirect to not found or show list of bookable team members.

**Comment by alishaz-polymath** [comment]
There have been reports of empty slots in event types other than managed, including but not limited to multiple duration events

**Comment by alishaz-polymath** [comment]
Finally fixed!
