### ISSUE TITLE
[CAL-3917] Dashboard Theme: system default not working

### ISSUE THREAD

**Issue by hichemfantar** [calcom/cal.com#15284]
### Issue Summary

The `System default` theme setting in the appearance settings doesn't work.

### Steps to Reproduce

1. go to https://app.cal.com/settings/my-account/appearance
2. if OS theme is dark, set cal.com theme to `light`, then set it again to `system default`
3. notice it doesn't change

### Actual Results

- `system default` is `light` even though OS is dark

### Expected Results

- `system default` should be `dark` because OS is dark

### Technical details

- Browser version: chrome 125, macOS 14.3.1

### Evidence

OS is dark:

https://github.com/calcom/cal.com/assets/34947993/c57d778b-37fd-49d0-9a2e-2698866863b4

<sub>[CAL-3917](https://linear.app/calcom/issue/CAL-3917/dashboard-theme-system-default-not-working)</sub>

**Comment by clicktodev** [comment]
looks like this has regressed again

**Comment by clicktodev** [comment]
btw i noticed that input components aren't consistent in several places in the UI which leads me to believe that there are duplicate input components being used because i notice different focus styles and animation transitions for inputs when navigating between different pages.
something you might wanna address

I think this issue is very obvious in the profile/general settings page
