### ISSUE TITLE
[CAL-3859] No-show bookings: Handle in Salesforce

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#15310]
When an attendee is marked as a no-show, we should send that data to the CRM platform and see if they mark meetings as no-shows.

<sub>[CAL-3859](https://linear.app/calcom/issue/CAL-3859/no-show-bookings-handle-in-crm-platform)</sub>

**Comment by joeauyeung** [comment]
No native functionality in Salesforce. Need to consider how we can leverage custom fields to do this.

**Comment by alishaz-polymath** [comment]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/89c48864-46b1-4fb5-9f91-75d4bab8e38b/3666e3c3-dc9b-46fd-8ffe-60955d045404?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84OWM0ODg2NC00NmIxLTRmYjUtOWY5MS03NWQ0YmFiOGUzOGIvMzY2NmUzYzMtZGM5Yi00NmZkLThmZmUtNjA5NTVkMDQ1NDA0IiwiaWF0IjoxNzM1MTg5NzE5LCJleHAiOjE3NjY3MjU3MTl9.2O93T0gi-TJlkw94aF0P67LCBd4XQaOPsaaO2xt8Ye8)

This has since been completed by @joe
