### ISSUE TITLE
Make cal.com open source

### ISSUE THREAD

**Issue by carstensbix** [calcom/cal.com#15552]
Cal.com was originally developed as an open-source alternative to Calendly. However, it seems their primary motivation for making it open-source was to leverage free contributions from the community under the MIT license. Once the product matured, they switched the license to AGPL, allowing them to monetize by selling licenses to businesses. This approach undermines the principle of open source, as it restricts the community's ability to benefit from their contributions while enabling the company to profit.

The pricing is also exorbitant, with $100 for 50 API calls, a rate unparalleled by any other company.

If Cal.com is truly open source, why isn't the API open source, and why are the licenses so costly? This practice appears to exploit free labor from contributors to the open-source project.

The popularity of Cal.com stemmed from its MIT-licensed open-source nature, which allowed everyone to use it freely. In response, a group of us (12 so far) are developing a new alternative, starting from the MIT-licensed version found at https://github.com/ayoungh-forked/calendso. We intend to maintain the MIT license to ensure it remains genuinely open source.

We invite anyone interested in contributing to this project to join us. We are a dedicated group committed to creating a true open-source alternative to Cal.com.

**Comment by carstensbix** [comment]
https://www.reddit.com/r/opensource/comments/1cwm0o7/calcom_thats_actually_open_source/?rdt=46485

**Comment by PeerRich** [comment]
AGPL does not undermine open source

Open Core means some parts will be open, some closed. Same as Gitlabs CE and EE. Gitlab is open source.

> The pricing is also exorbitant, with $100 for 50 API calls, a rate unparalleled by any other company.
where did you get this? This is false.

We have a ton of free APIs, whether we host them or you host them.

The only product we monetize is the Cal.com Platform API


> The popularity of Cal.com stemmed from its MIT-licensed open-source nature
False. We changed from MIT to AGPLv3 in September 20, 2021, almost 3 years ago. https://cal.com/blog/changing-to-agplv3-and-introducing-enterprise-edition
The popularity comes from our balance of open source and commercial source and our community is really happy with the state of the repo.

This issue unfortunately has a lot of loaded assumptions and false statements. Happy to discuss on a call: https://i.cal.com/peer

If people genuinely feel this way (which i disagree) we're happy to make even more adjustments.

Again, 99% of Cal.com is fully open source. The open source initative opensource.org considers AGPLv3 is an open source license https://opensource.org/license/agpl-v3

**Comment by carstensbix** [comment]
> AGPL does not undermine open source
> 
> Open Core means some parts will be open, some closed. Same as Gitlabs CE and EE. Gitlab is open source.
> 
> > The pricing is also exorbitant, with $100 for 50 API calls, a rate unparalleled by any other company.
> > where did you get this? This is false.
> 
> We have a ton of free APIs, whether we host them or you host them.
> 
> The only product we monetize is the Cal.com Platform API
> 
> > The popularity of Cal.com stemmed from its MIT-licensed open-source nature
> > False. We changed from MIT to AGPLv3 in September 20, 2021, almost 3 years ago. https://cal.com/blog/changing-to-agplv3-and-introducing-enterprise-edition
> > The popularity comes from our balance of open source and commercial source and our community is really happy with the state of the repo.
> 
> This issue unfortunately has a lot of loaded assumptions and false statements. Happy to discuss on a call: https://i.cal.com/peer
> 
> If people genuinely feel this way (which i disagree) we're happy to make even more adjustments.
> 
> Again, 99% of Cal.com is fully open source. The open source initative opensource.org considers AGPLv3 is an open source license https://opensource.org/license/agpl-v3

I understand that you have paid features like teams etc.. But your pushing people to the AGPL license as a lot of the code is proprietary, then you benefit from free labor through open source and then still take an absurd amount for the platform license. 

I could understand if it were something like 1000 bookings for 1 dollar or something like that. Look at anything else like Sanity, Shopify etc.. and see how cheap their plans are. 1 booking is a simple HTTP request I don't understand why that is so expensive. Or maybe make it a fixed price for a license, something like 29 dollars a month or something idk.

**Comment by PeerRich** [comment]
no that is simply not correct

people can self host and use everything thats not /ee/ under agplv3

thats all open source

if you take a look at contributions of the /ee/ folder thats almost 99% coming from our paid core team, and even if its from community, they know what they sign up for. our CLA is very clear about that

if community contributors--for whatever reason, need an enterprise license we are more than happy to do that

but frankly, almost all enterprise features are in fact only relevant for enterprise

if not, happy to move some things from /ee/ to open source

**Comment by PeerRich** [comment]
about the fee: 

we are not charging for an api call

you pay for a platform plan to commercially engage with us. receive the best support we can offer, updates, and everything else

we dont charge for a simple endpoint, its a package that comes with bookings included (but also a lot of other stuff included)

to put things into perspective, the platform product alone cost ~$1M to develop. if people want good products with longevity we simply have to ensure that

cal.com is a commercial open source product, the alternative for a product of this quality and over $5M in r&d is not FOSS (free open source) the alternative is closed SaaS and we believe COSS is the best of both worlds here

after all these words i would still love to jump on a call, maybe i am missing something 

our pricing and product evolves almost weekly and if there is something thats stopping adoption its my job to fix that

https://i.cal.com/peer 🙏

**Comment by carstensbix** [comment]
Thank you for your response. However, there are some misunderstandings regarding your pricing and white-labeling options.

While Cal.com markets itself as offering white-labeling—"Self-hosted or hosted by us. White-label by design"—access to white-labeling requires an enterprise plan. This makes it challenging to use Cal.com for building simple applications without an enterprise license.

You frequently compare your service to GitLab’s AGPL license. However, GitLab charges $29 per user, providing extensive usage and support at a lower cost. A fairer comparison would be if Cal.com offered a $29/month platform license with unlimited bookings, making it more accessible.

I suggest reviewing your pricing structure to align better with customer expectations and market standards. For example, I would be willing to pay $30 per team member for white-labeling and the ability to build on top of Cal.com with unlimited bookings.

**Comment by carstensbix** [comment]
> about the fee:
> 
> we are not charging for an api call
> 
> you pay for a platform plan to commercially engage with us. receive the best support we can offer, updates, and everything else
> 
> we dont charge for a simple endpoint, its a package that comes with bookings included (but also a lot of other stuff included)
> 
> to put things into perspective, the platform product alone cost ~$1M to develop. if people want good products with longevity we simply have to ensure that
> 
> cal.com is a commercial open source product, the alternative for a product of this quality and over $5M in r&d is not FOSS (free open source) the alternative is closed SaaS and we believe COSS is the best of both worlds here
> 
> after all these words i would still love to jump on a call, maybe i am missing something
> 
> our pricing and product evolves almost weekly and if there is something thats stopping adoption its my job to fix that
> 
> https://i.cal.com/peer 🙏

Thank you for your response, I really appreciate your comments. However, there are some misunderstandings regarding your pricing and white-labeling options.

While Cal.com markets itself as offering white-labeling—"Self-hosted or hosted by us. White-label by design"—access to white-labeling requires an enterprise plan. This makes it challenging to use Cal.com for building simple applications without an enterprise license.

You frequently compare your service to GitLab’s AGPL license. However, GitLab charges $29 per user, providing extensive usage and support at a lower cost. A fairer comparison would be if Cal.com offered a $29/month platform license with unlimited bookings, making it more accessible.

I suggest reviewing your pricing structure to align better with customer expectations and market standards. For example, I would be willing to pay $30 per team member for white-labeling and the ability to build on top of Cal.com with unlimited bookings.

**Comment by Novapixel1010** [comment]
First, I want to say that I’m sorry, but I feel like this situation borders on gaslighting. You stated, "The only product we monetize is the Cal.com Platform API." However, when you go into Settings → API Keys, it clearly shows entries for "contact_sales" and "enterprise_license_sales" — exactly as written, with underscores.

Additionally, I've noticed the self-hosted version runs very slowly. My hardware is more than capable, so I know that's not the bottleneck.

More importantly, I want to point out a broader concern: switching the project's license from MIT to AGPLv3 feels like a betrayal of the open source community that helped support and grow the project. Starting a project under AGPLv3 is one thing — developers can make an informed choice from the beginning. But starting under the very permissive MIT license and then switching once traction has been gained undermines trust and takes advantage of the community.

I’m sure the typical justification will be cited — "to protect the project" or "to ensure profitability" — but there are plenty of examples of projects thriving financially without resorting to such license changes: Kubernetes (over $1B ecosystem), Next.js, Vue.js, TensorFlow, Chatwoot, and many others.

This isn’t the first time the Cal.com project has misrepresented its relationship with open source, and I believe it’s important to be honest and transparent if you want to maintain the trust of the developer community. For example @ssddanbrown has highlighted this.

**Comment by PeerRich** [comment]
not looking to gaslight anyone, just explaining with full transparency what we are doing and why.

let me go into detail why we still consider what we do open core.

couple bullet points:
- only the paid core team is contributing to the /ee/ team 
- the non-enterprise open core has about 2M of research and development of our own team invested, free to use
- we give free commercial licenses for anyone in need asking, such as nonprofits or indie developers (rarely needed)
- we have over 1M docker pulls, out of which are likely 99.9% using the free open core
- every contributor is aware of the licenses and what it means, we also sign a CLA (contributor license agreement) that explains in easy language what to expect
- AGPLv3 is open source. it has nothing to do with the commercial license

> "starting under the very permissive MIT license and then switching once traction has been gained" 
- this statement is objectively false, we changed to AGLv3 about 3 years ago https://cal.com/blog/changing-to-agplv3-and-introducing-enterprise-edition – many many years before there was any meaningful traction. We moved to AGPLv3 to protect us and the community from a hostile OSS takeover like AWS has done to Elastic. AGPLv3 is not a commercial license, it is an open source license that simply requires you to stay open source if forked.
- the self-hosted version is not slower because we hate the community. there is no line of code that artificially lowers the speed. we simply havent spent enough time figuring out why it is slow on some hardware vs other. we run the **same codebase** on vercel, with a simple AWS RDS and dont have a lot of issues. the community and core team is constantly working on making the self-hosted experience better (also thanks to self-hosters who purchase a commercial license).
- the current price is not 299 for self-hosting, its $299 with 15 seats included and we start with licenses as low as $15/month (you need to contact sales tho). We have done this countless times, also happy to do a personal call here and get you onboarded: https://cal.com/peer
> resorting to such license changes: Kubernetes (over $1B ecosystem), Next.js, Vue.js, TensorFlow, Chatwoot, and many others.
- nextjs and vuejs are hard to compare with an application that has a completely cost structure like Cal.com, nextjs is the "free" part of vercel, which is heavily monetizing it
- TensorFlow is owned by Google, please dont compare us with a $T company
- Chatwoot has an open core split license with MIT + Enterprise license as well: https://www.chatwoot.com/docs/self-hosted/enterprise-edition the only difference you are pointing out is MIT vs AGPLv3 which – are both open source

![Image](https://github.com/user-attachments/assets/1e36afcc-389a-4a9f-8f0c-24c30f7d69a9)

i’m not a keyboard warrior, feel free to book a time with me any day: i.cal.com/peer we strongly care about every voice in the ecosystem and want to do whats right for everyone:
- employees
- customers
- investors
- community members

expect issues to come from lack of knowledge, not malice

best,
Peer

**Comment by Novapixel1010** [comment]
Thank you for taking the time to provide such a detailed response. I appreciate the transparency and willingness to engage in a conversation rather than being only defensive. I sure this will serve as a good resource for people with questions. I will also try to keep this as my last reply. 

## I want to acknowledge a few things you clarified:

- I understand now that the move to AGPLv3 happened several years ago before major traction, and not recently.

- I also understand that AGPLv3 is technically an open source license but it is much more restrictive one compared to MIT. (some companies won't even use AGPLv3 which might mean big companies that would've paid for a support package won't even look at the software)

- I agree that protecting a project from misuse by large cloud providers (like AWS with Elastic) is a valid concern.

I appreciate that you offer discounted or free commercial licenses for non-profits and indie developers.

## That said, I still have a few concerns that I don't think were fully addressed:

Changing from MIT to AGPLv3 still represents a fundamental shift. Even if it was years ago, MIT and AGPLv3 encourage very different types of community participation and adoption. Developers who originally contributed under MIT assumptions might feel differently about AGPLv3, regardless of CLAs. 

Minio did the same thing but they may have a legal battle in the future because last I checked a lot of developers disagreed and no one can find if the 200+ contributes signed for the change.

"Open core" is often understood to mean the complete core experience is free and usable, while paid features are truly "extras." Having key functionality behind "contact_sales" and "enterprise_license_sales" messaging in the API settings, even in the open source version, can give the impression that the free version is intentionally limited rather than fully functional.

The slow performance on self-hosted installs still raises some questions. I appreciate you saying there’s no deliberate throttling. Maybe I can provide more details about my system and logs if that helps find the bottle neck.

Comparison to other projects: I agree it's not a perfect apples-to-apples comparison. Kubernetes, Next.js, Vue.js, TensorFlow — all had very different backers, ecosystems, or financial models. But the point still stands that it's possible to build healthy open-source businesses here is a better example [ERPnext](https://frappe.io/erpnext) that I last checked has nothing behind a paywall.

Finally,
I want companies like Cal.com to succeed especially those trying to balance open source with a real business model. My goal is to provide honest feedback about how these things feel to someone who deeply cares about open source ethics and sustainability.

## one last question 

1. I have to pay for an api I am hosting on my own hardware and maintaining?

> Charging for basic API access while self-hosting your own server is extremely unusual — and feels closer to a SaaS upsell strategy than a true open-source model.

**Comment by ssddanbrown** [comment]
@Novapixel1010 since you mentioned me and got me watching this thread, I thought I'll just provide some input to your thoughts as another perspective.

> I also understand that AGPLv3 is technically an open source license but it is much more restrictive one compared to MIT. (some companies won't even use AGPLv3 which might mean big companies that would've paid for a support package won't even look at the software)

The AGPLv3 has more conditions, but permissive (like the MIT) vs copyleft (like the AGPLv3) comes down to the balance of freedoms. The MIT license provides a large amount of freedom to the user, AGPLv3 provides assures much better freedom of the code to its potential user-base (but this requires more conditions).
I don't think use of the AGPLv3 itself is really problematic at all, most fear of it comes [from misconceptions](https://danb.me/blog/common-agpl-misconceptions/).
If companies won't use it, then that's on them, as there's a lot of freedom of use afforded via the AGPLv3 still and it can be used in most commercial context (unless you want/need to combine/add & distribute with source of other licenses).

Being AGPLv3 + CLA is more problematic IMO, due to the imbalance of freedoms between the original authors and users, but code under AGPLv3 is still open source and can be useful. In fact the CLA can add risk to the original author, since they can't accept changes to forks of their own software (without direct permission).

My personal concerns have been around the mixing of AGPLv3 and non-AGPLv3 code, along with the representation of the AGPLv3, but these have been raised before so I won't push on them further.

> Developers who originally contributed under MIT assumptions might feel differently about AGPLv3, regardless of CLAs.

If they contributed under the MIT then they provided their work under a license which allows sub-licensing, including under the AGPLv3 or even under something completely non-open. I don't think this is really problematic at all. Those contributions would technically remain MIT, but the AGPLv3 is not incompatible (unlike the reverse). The licensing could _maybe_ be better labelled to state this, since the MIT license (and MIT contributions) still requires specific notice text, **_but_** you get into the specific wording of the MIT text and what's considered "substantial portions of the Software", and my guess would be the externally contributed MIT portions could have been lesser at the time of change (not something I've looked into though).

How the change was done could be problematic. I don't think it's great for projects to switch out licenses without a good amount of notice (I've seen projects switch to non-open licenses, with the only significant mention being a discussion in a long weekly dev video) but I don't know the context for that for this project, so I won't assume malice. Again, a bigger concern to me would be creep in overlap/mixing of open and non-open code over time since that can impact feasibility of forking.

**Comment by PeerRich** [comment]
> Developers who originally contributed under MIT assumptions

i just [went back in time](https://github.com/calcom/cal.com/commit/5ad825544a7787f58db7c7e9e12da49c6a6a0ad0), MIT was everything before v1.0 which dates back to September 2021, 4 years ago. no one really contributed to the MIT license other than me, my cofounder and maaaybe some early paid freelancers.

there has not been any outcry from previous nor current contributors about this change and everyone welcomed it. https://x.com/calcom/status/1439996261596282882

i understand that some projects do a serious open source rug pull but if you actually check out anything thats been done before v.1.0 under MIT you will soon realise it's next to nothing that cal.com stands for today. There is probably 0 lines of code left from those days OR they were written by people still with the company today.

if the sadness from agplv3 is too big, thats the tradeoff we are taking by being a commercial open source project (COSS), not a freemium open source project (FOSS). i believe there are more benefits than drawbacks but thats a personal believe.

> My personal concerns have been around the mixing of AGPLv3 and non-AGPLv3 code, along with the representation of the AGPLv3, but these have been raised before so I won't push on them further.

i want to double click on this because there is virtually no difference between an MIT + Enterprise vs AGPLv3 + Enterprise, only that you can only fork in public (and thereby, in my opinion, honor the work of past contributors more than forking in private).

a CLA is pretty much *always* recommended, no matter the license. 

long story short: if you are asking for MIT, this is not the right project. maybe if someone had donated $5M to $10M as a philantrophic act we could go fully OSS with the least permissive license, but thats probably a project for another day.

until then i wanna struck the best balance between OSS and commercialisation, and looking at this incredible community that is dying to contribute + 1M docker pulls using cal.com for free + having the **very best free hosted plan** i think we are doing a great job right now

**Comment by Novapixel1010** [comment]
I thank you both for your time and makes things very clear.  Glad to hear this project is doing good.  and no the license is not a deal breaker for me personally. You both are very knowledge in this so I will ask here if I use this software simply for clients to book appointments. I assumed I need to link back to this project or can I white-label. Just to be clear I am not looking to sell this software itself just use it. 

## Maybe missed it but what about 

> Do I have to pay for an license to use the api when am hosting the api server on my own hardware?

or is that a bug.

**Comment by PeerRich** [comment]
to follow up here, the commercial license now costs $15 per user to start, https://cal.com/pricing
