### ISSUE TITLE
opt-in emails are being sent after the event happened if unanswered

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1577]
I forgot to cancel an opt-in event so I keep getting reminders to accept/reject it, even tho the event already passed

solution: stop sending opt-in emails when time has passed

**Comment by MarthoxGT** [comment]
Greetings @PeerRich!

I was looking at this issue and actually implemented various solutions based on code behavior, but I have a problem testing this in my local environment, because emails doesn't send, I tried creating a new a user on the database, creating a new user by an organization invitation, and modifying an already existing user email, all unsuccessful, so I would really appreciate if you can give a hand on how can I replicate the send email behavior in local environment.

Thank you.

**Comment by PeerRich** [comment]
@baileypumfleet what do we recommend for sending emails on staging / localhost?
