### ISSUE TITLE
[CAL-4051] Error with the UI teams

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#15812]
UI teams tab showing only one team but says "you have a lot of teams".

profile with only one team.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/412621f4-bd3f-4748-8c01-dc7a44450245/6669d43c-2866-45e9-ac7c-fe0e647a2a9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80MTI2MjFmNC1iZDNmLTQ3NDgtOGMwMS1kYzdhNDQ0NTAyNDUvNjY2OWQ0M2MtMjg2Ni00NWU5LWFjN2MtZmUwZTY0N2EyYTljIiwiaWF0IjoxNzIxMjI4ODAzLCJleHAiOjE3NTI3NjQ4MDN9.SNqRr99_cWw5Stm9kqbDp3H-WufcgpYXqzYVKkG5p7A)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4051](https://linear.app/calcom/issue/CAL-4051/erorr-with-the-ui-teams)</sub>

**Comment by tmy348mane** [comment]
can u have more details on this ?

**Comment by SySagar** [comment]
Unable to produce it in the latest local version. Is this on production?

**Comment by Souptik2001** [comment]
cc: @anikdhabal 👆

**Comment by Souptik2001** [comment]
@SySagar Just FYI - Were you not able to see that self-serve message box? If that's the case that's because you didn't set `NEXT_PUBLIC_ORG_SELF_SERVE_ENABLED` env var to 1.

This constant is checked before displaying that message - https://github.com/calcom/cal.com/blob/e6a16f5b5c69a4bc1a8c4b8819183b20c0ef1a21/packages/features/ee/teams/components/TeamList.tsx#L55, which is in-turn derived from the env var mentioned above.
