### ISSUE TITLE
[CAL-4104] Whatsapp message body sometimes editable

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16067]
WhatsApp only allows predefined templates, so the input field for the WhatsApp message body shouldn't be editable. 

How to reproduce? 

* Create a new workflow
* Change action to 'Send WhatsApp message to attendee'
* Now you the text from for text message can be edited

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4104](https://linear.app/calcom/issue/CAL-4104/whatsapp-message-body-sometimes-editable)</sub>

**Comment by asharamseervi** [comment]
Hi, While this feature should be designed for development, which could be iterated further to handle other exceptional cases; like WhatsApp, SMS, etc.

**Comment by Flash-Shivam** [comment]
```
                   <Editor
                      getText={() => {
                        console.log(step.action);
                        console.log(props.readOnly);
                        console.log(!props.readOnly && !isWhatsappAction(step.action));
                        console.log(props.form.getValues(`steps.${step.stepNumber - 1}.reminderBody`) || "");
                        return props.form.getValues(`steps.${step.stepNumber - 1}.reminderBody`) || "";
                      }}
                      setText={(text: string) => {
                        console.log("Nomad");
                        console.log(!props.readOnly && !isWhatsappAction(step.action));
                        props.form.setValue(`steps.${step.stepNumber - 1}.reminderBody`, text);
                        props.form.clearErrors();
                      }}
                      variables={DYNAMIC_TEXT_VARIABLES}
                      height="200px"
                      updateTemplate={updateTemplate}
                      firstRender={firstRender}
                      setFirstRender={setFirstRender}
                      editable={!props.readOnly && !isWhatsappAction(step.action)}
                    />
```
                    
This piece of code gets rendered upon following the steps mentioned above to reproduce the code
Although I see that console value for editable is false( since `props.readOnly is false and isWhatsappAction(step.action) is true` , and even then I am able to edit it . On Hardcoding `editabble = {false}` makes the box uneditable. This implies somehow value of `!props.readOnly && !isWhatsappAction(step.action)` is getting changed , although I added logs in setText 
which still show value of `!props.readOnly && !isWhatsappAction(step.action)` as `false`. 


What could be the bug in the code ?
