### ISSUE TITLE
advanced availabillity

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1651]
/availability
- [ ] ability to create multiple schedules
- [ ] select a default
- [ ] timezone
- [ ] date overrides
- [ ] "active on" dropdown

/event-types

- [ ] availability dropdown in event-type settings

![image](https://user-images.githubusercontent.com/8019099/151672259-709abe2e-e188-4725-a44e-a7b4f034f558.png)
![image](https://user-images.githubusercontent.com/8019099/151672321-f1caab43-7f6a-4f94-a65e-d5b5ce388717.png)

![image](https://user-images.githubusercontent.com/8019099/151672381-01c3fee0-5923-45fc-a460-fd0ad96126ae.png)

**Comment by PeerRich** [comment]
done #2150

**Comment by aasargsian** [comment]
We are really looking forward to date overrides! 
Our doctors rarely have standard schedules and we typically only work with one-off availabilities.
Managing doctors' schedules once we switch to Cal.Com can become much more complicated without date overrides since we'll need to block a lot of slots out from their Google calendars.
