### ISSUE TITLE
dynamic group links (collective)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1661]
it would be amazing to have dynamic links such as:

cal.com/peer+bailey+zomars

for a collective call with all three

for now it should by default use Cal Video.

lets start with the default event types:

- 15 Minute meeting (cal.com/peer+bailey/15)
- 30 Minute meeting (cal.com/peer+bailey/30)
- 60 Minute meeting (cal.com/peer+bailey/60)

each uses Daily.co as location 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/8019099/159078061-4081b68a-2807-4734-b707-f570400e0699.png">

**Comment by philippdormann** [comment]
This could either use Daily.co, Huddle01 oder Jitsi Meet (see #1445) since no registration is needed.

Maybe as a base (so users can actually remember how to generate URLs), use something like "/peer+philipp/30min" to configure a meeting.

To extend this (for more advanced users) one could provide GET params - e.g. "/peer+philipp/30min?location=daily" or "/peer+philipp/30min?type=rr" for round-robin? Don't know if that gets too complicated though.

**Comment by PeerRich** [comment]
> This could either use Daily.co, Huddle01 oder Jitsi Meet (see #1445) since no registration is needed.
> 
> Maybe as a base (so users can actually remember how to generate URLs), use something like "/peer+philipp/30min" to configure a meeting.
> 
> To extend this (for more advanced users) one could provide GET params - e.g. "/peer+philipp/30min?location=daily" or "/peer+philipp/30min?type=rr" for round-robin? Don't know if that gets too complicated though.

seems too complicated. i think as a test we should go with daily.co
