### ISSUE TITLE
Zoom integration doesn't follow the zoom app settings for auto-record

### ISSUE THREAD

**Issue by achalliburton** [calcom/cal.com#16709]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When scheduling a meeting, the integration creates the Zoom meeting but it does not follow the recording parameters set inside Zoom. It defaults to not recording any meeting. 

### Steps to Reproduce

1. Connect Zoom App
2. Schedule Meeting
3. Check meeting inside Zoom platform (or jump on call) and notice the recording is defaulted to not recording 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

The connected app is not following the parameters set in the Zoom account settings. 

### Expected Results

The app connected through Cal.com should follow the parameters met by Zoom account settings

### Technical details

- Not browser specific
- Not account specific (Zoom or Cal.com) 
- Issue has been reported multiple times and closed without resolution 

### Evidence

- Related ticket: https://github.com/calcom/cal.com/pull/15489
- Related ticket: https://github.com/calcom/cal.com/pull/15478

**Comment by neehhaa06** [comment]
Hello @achalliburton :)

fix: #16709

`
The Zoom API correctly retrieves and applies the user's auto-record settings when scheduling a meeting via Cal.com. This requires proper synchronization between the Zoom account settings and the integration. Implement a fallback mechanism to default to Zoom's settings if synchronization fails.
`

**Comment by vijayraghav-io** [comment]
Verified again that its working as expected after this PR https://github.com/calcom/cal.com/pull/15489 is merged.
If its not working for specific users, its because of the scope not being added in zoomAppMarketplace https://marketplace.zoom.us/

Kindly refer this video to update scopes in ZoomAppMarketplace.
The new scope `user:read:settings` needs to be added to respect the recording settings in zoom.

https://www.loom.com/share/d1b8f6910ca946f7a729a80c78167da0?sid=7950171a-681c-45c4-9d7f-55aff7afe500

**Comment by vijayraghav-io** [comment]
@milospuac 

PFB video showing record settings is working as expected after the referenced PR  https://github.com/calcom/cal.com/pull/15489 is merged.
If not working for specific users, its because of scope not being added. Please refer the video in previous comment for adding scope in zoomAppMarketplace.

https://www.loom.com/share/48799d1d4af44de8ae82a6fff7353b0f?sid=8efbe50b-af43-4918-bbb7-4864a513b5ff

cc @joeauyeung

**Comment by vijayraghav-io** [comment]
> This scope needs to be added to the public Cal.com<http://Cal.com> Zoom app. The loom here is showing a private app created.

Members with admin credentials to public Cal.com<http://Cal.com> can do this.

cc @PeerRich , FYI
