### ISSUE TITLE
Event Duration displays incorrectly in event name

### ISSUE THREAD

**Issue by bugspotted** [calcom/cal.com#16887]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I used the advance option to name an event automatically with the following:

Video Call {Event duration}: {Organiser} and {Scheduler}

For some reason when people schedule a 30 min video call, it displays 60 min on the calendar invite

### Steps to Reproduce

1. Go to my cal page for a video event: https://cal.com/d/wimyZ3D94LjGG7Wuzn8CGh/vid
2. Choose 30 min for duration
3. Schedule an event and see the event name says 60 min

### Actual Results

The event name seems to always say 60 min

### Expected Results

The event name should say whatever the time chosen is as the event duration

### Technical details

This is happening when people schedule with me and has happened from 2 different people - I don't know their browser set up

### Evidence

See screenshot - both are 30 min meetings and both event names say 60

**Comment by bugspotted** [comment]
<img width="572" alt="Screenshot 2024-09-30 at 11 13 07 PM" src="https://github.com/user-attachments/assets/d417dae8-e1ff-416e-94d1-703f447623eb">

**Comment by Mobarak786** [comment]
I have read and understood the bug🐞.  Well i will try to fix it. Hope it is a small bug. Assign me the task please. 🙏

**Comment by naaa760** [comment]
Hello!  @bugspotted 


_I think changing the **`{Event duration}}** placeholder to dynamically reflect the user's selected duration instead of defaulting to 60 minutes would address the issue where the incorrect event duration is displayed in the event name. To do this, the event creation logic in the backend can be updated to retrieve the actual duration selected during scheduling. As a result, the user-selected duration—such as thirty minutes—will be accurately entered into the event name, guaranteeing precision and clarity in the scheduled events._

**Comment by anikdhabal** [comment]
Can't reproduce, i think it was fixed
![Screenshot 2024-10-24 113400](https://github.com/user-attachments/assets/204c2b5f-771d-4add-be27-f7391a6289cb)
![Screenshot 2024-10-24 113416](https://github.com/user-attachments/assets/dda0f3bc-b91e-4e0a-8100-6932e16b727e)
