### ISSUE TITLE
Option for mandatory payment at the time of booking 

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#1720]
### Customer feature request

  User wants to make his Stripe payments mandatory at the time of booking and not give his customers the option to pay later

### Additional context

 https://app.intercom.com/a/apps/txijvysj/inbox/inbox/5366480/conversations/181555500010847

<img width="434" alt="Screen Shot 2022-02-07 at 16 38 06" src="https://user-images.githubusercontent.com/97884287/152820502-033523a1-7e83-4d13-8151-31548ede77ca.png">

**Comment by Kfelts** [comment]
Just went searching for this request before adding it myself. This is ESSENTIAL for my ability to use cal.com. Otherwise my calendar will fill up with bookings that are unpaid, resulting in no-shows. Tidycal implemented this by adding a checkbox feature on the specific calendar settings "require payment at time of booking" and then using the hosted fields for stripe under the actual client inputs. Instead of "confirm" it says "submit" which sends the payment to Stripe and Stripe sends back a confirmation, allowing the calendar booking to be submitted successfully.

Another calendar software that has this requirement is Clientrock. After answering the questions, an integrated payment form replaces the client questions, and then they proceed to one more confirmation screen before the payment and appointment are submitted.

**Examples**
<img width="383" alt="Screen Shot 2022-09-26 at 3 27 58 PM" src="https://user-images.githubusercontent.com/51497445/192365177-d5b2097d-28d5-4639-be02-a773391aabf8.png">

<img width="797" alt="Screen Shot 2022-09-26 at 3 34 21 PM" src="https://user-images.githubusercontent.com/51497445/192365218-35b34c9a-8768-4e89-a675-606aacc4a68e.png">

https://user-images.githubusercontent.com/51497445/192365242-1df3be46-dd34-478e-8e59-90771a546498.mp4

**Comment by PeerRich** [comment]
this will be fixed with the new booking flow
