### ISSUE TITLE
[CAL-4631] allow OOO of the past and overlapping

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17368]
for tracking purposes it would be dope to add OOO retroactively. currently its blocked:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/98904731-a64a-4acd-bbb9-11c623f5d2bb/e6d5c988-eb40-47b6-aa1b-428c21dd0ff9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85ODkwNDczMS1hNjRhLTRhY2QtYmJiOS0xMWM2MjNmNWQyYmIvZTZkNWM5ODgtZWI0MC00N2I2LWFhMWItNDI4YzIxZGQwZmY5IiwiaWF0IjoxNzMwMTI3MjI1LCJleHAiOjE3NjE2NjMyMjV9.wvUfGn6dRudGQ1Ok1ja6yUIa1od1uZQdXzsACWHo7es)

it would also be nice if OOO could overlap, there is no reason someone cant be OOO for sick day and then when that ends be OOO for traveling or so

right now we throw an error for overlapping:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/734d7623-5572-44ac-a6dc-cdbacf86934a/2302f809-f529-4aeb-bae1-6168b6f882d4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83MzRkNzYyMy01NTcyLTQ0YWMtYTZkYy1jZGJhY2Y4NjkzNGEvMjMwMmY4MDktZjUyOS00YWViLWJhZTEtNjE2OGI2Zjg4MmQ0IiwiaWF0IjoxNzMwMTI3MjI1LCJleHAiOjE3NjE2NjMyMjV9.h08fq4JhQ7y-ue3cxvlHTyaLM4X-ySQZHDdIW3yfaB8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4631](https://linear.app/calcom/issue/CAL-4631/allow-ooo-of-the-past-and-overlapping)</sub>

**Comment by itsalam** [comment]
If its all okay, I've also submitted a PR, this one implements overlapping dates as a toggle.

**Comment by naaa760** [comment]
Hello @PeerRich 
I want to solve this issue!

**Comment by BHAVISHYA2005** [comment]
> Hello @PeerRich 
> I want to solve this issue!

PR has already been raised 🙌

**Comment by rahul1995** [comment]
@BHAVISHYA2005 @PeerRich Can you help me understand the process to claim? Looks like nobody gets assigned to the issue, so everyone independently solves the issue and tries to claim? If that's the case, it might make a lot of people working on the same issue which is unproductive, rather it might be better if people get assigned to a task along with the deadline..

**Comment by KyleChen26** [comment]
Hi! I'd like to work on this bounty.

**Approach:**
1. **Past OOO:** Remove the validation that blocks creating OOO entries for past dates
2. **Overlapping OOO:** Modify validation to allow overlapping date ranges instead of throwing error
3. Update UI to visually distinguish overlapping periods
4. Ensure calendar integrations handle overlapping correctly

**Changes needed:**
- Remove/modify date validation in OOO creation form
- Update backend validation logic
- Add tests for past and overlapping OOO scenarios
- Update UI if needed for clarity

**ETA:** 2-3 days

Can I take this?
