### ISSUE TITLE
[CAL-4732] Host entry not created when user added to team

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#17654]
Adding a user to a team doesn't seem to create an host entry for that user in an event where 'Assign all future members' is enabled.

I added the user to the team using data table actions

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b0cbfd8f-b01b-43e8-b1c4-8d0dcfd8e943/a74ccd3d-ad62-4492-973f-ac71ba9d69ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iMGNiZmQ4Zi1iMDFiLTQzZTgtYjFjNC04ZDBkY2ZkOGU5NDMvYTc0Y2NkM2QtYWQ2Mi00NDkyLTk3M2YtYWM3MWJhOWQ2OWVkIiwiaWF0IjoxNzMxNjQ3MTM0LCJleHAiOjE3NjMxODMxMzR9.osOAJUwkiA33Kkaa79RsyLrfuqd_P_22OgW76_ZwShc)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a14a4f18-c7ad-4b9b-bbd0-4120ddf2a07b/45751943-704c-4b5f-a941-5f8b02a3457e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMTRhNGYxOC1jN2FkLTRiOWItYmJkMC00MTIwZGRmMmEwN2IvNDU3NTE5NDMtNzA0Yy00YjVmLWE5NDEtNWY4YjAyYTM0NTdlIiwiaWF0IjoxNzMxNjQ3MTM0LCJleHAiOjE3NjMxODMxMzR9.dffJ9XUgElJo9vmJxse2rxD-HYy_ma74eZ4JMxQY0cU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4732](https://linear.app/calcom/issue/CAL-4732/host-entry-not-created-when-user-added-to-team)</sub>

**Comment by sanjeevs9** [comment]
can you please explain it further

**Comment by sanjeevs9** [comment]
working on it

**Comment by sanjeevs9** [comment]
Currently, when someone is added as a Round Robin host, they cannot be added as a Fixed host, and vice versa. However, when we click the "Add All Team Members" button, it adds all members to the Round Robin hosts and removes the Fixed host flag from them. As a result, they become Round Robin hosts, and we cannot make them Fixed hosts anymore.

If you want me to change this feature, please let me know.
We could modify it so that even if a user is a Round Robin host, they can still be added as a Fixed host.
@hariombalhara

**Comment by sanjeevs9** [comment]
![Screenshot 2024-11-17 110633](https://github.com/user-attachments/assets/ea46eae0-9490-4f63-9f1c-f1da4c59fe87)
Can you please explain the issue further? When I turn on this button(add all team members) and add members, they are being added as hosts in the database. I checked the host table. and i added using this table only
