### ISSUE TITLE
[CAL-4857] ability to require an email

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#18047]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/83e11dc2-69c5-46cb-9c70-8e56cda6ee7a/400e808b-bebd-44d6-880b-baaf9cf7a204?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84M2UxMWRjMi02OWM1LTQ2Y2ItOWM3MC04ZTU2Y2RhNmVlN2EvNDAwZTgwOGItYmViZC00NGQ2LTg4MGItYmFhZjljZjdhMjA0IiwiaWF0IjoxNzMzNTExNDQxLCJleHAiOjE3NjUwNDc0NDF9.id_yPfstVixz39AbAPBjwgzPUSfa8XE_NKgbrTSdHIA)

right now we have “exclude”.

lets the opposite for people who wanna lock down their form and require a certain email

Error:

* Your email has no permission to book. contact the owner of this link.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4857](https://linear.app/calcom/issue/CAL-4857/ability-to-require-an-email)</sub>

**Comment by bobo-m** [comment]
please give more details about the issue.

**Comment by giteshsarvaiya** [comment]
Let me clarify what I understood. 
We want one more input field that accepts "require email that contains" so that only those emails can be added in those fields. And if someone writes another email domain then it will show error. 

Few questions : 
Do we want to remove the current "excule" field or we want to have toggle effect between "inclue" and "exclude" field ? Or do we want both of them together with 'not required ' as true.

**Comment by PeerRich** [comment]
no keep excluded

and keep required switch

only add the "must include"

**Comment by giteshsarvaiya** [comment]
Alright!
