### ISSUE TITLE
"secret" event-type is not hidden

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1947]
the pre-made secret event-type used to be hidden but now it's hidden: false

<img width="211" alt="image" src="https://user-images.githubusercontent.com/8019099/155238219-101d1e0f-c9ad-4792-8857-7f6605526ad7.png">

**Comment by joeauyeung** [comment]
Hi @PeerRich, I edited the `hidden` field to `true`. On the frontend end the pre-made secret event is now displaying hidden. Is this the expected behaviour? 
![Screenshot from 2022-02-24 17-45-53](https://user-images.githubusercontent.com/65426560/155620403-f6d536c1-e459-41e8-9ab2-94a1b25fe99f.png)
If so I can follow the instructions to do a proper pull request.

Thanks.

**Comment by joeauyeung** [comment]
Hi @PeerRich, I solved the problem and now I'm running the tests before I do a pull request.

**Comment by joeauyeung** [comment]
Woops looks like I made a change in a file that's part of the .gitignore. I noticed it's a bug that stems from #1946 - Second go at removing Zod generated classes.

In `packages/prisma/zod/custom/eventtypes.ts` in the `pick` method the `hidden` field was left out.  This is my first time working with the Zod package but I'm looking into how we can keep the required fields while having `hidden` as optional.

Unless @emrysal you know the solution off the top of your head?

**Comment by joeauyeung** [comment]
I was mulling over this and I was thinking we could have the `hidden` field included with every new event creation. Although this maybe a bigger change since we would have to ensure that all options to create a new event has the `hidden` field included.
