### ISSUE TITLE
Team Owner/Organizer issue

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#2089]
If you change the role of the team owner for example to Admin, it isn't possible to select it back to Owner. 
<img width="598" alt="Screen Shot 2022-03-08 at 14 02 45" src="https://user-images.githubusercontent.com/97884287/157243247-762ce4fb-866d-4ad1-9f4c-927db58b5607.png">

Also, there is an issue where the organizer of the team isn't shown as the Organizer in the confirmation email, it shows the member instead, even though the owner of the team did the confirmation.

**Case for context**
![download](https://user-images.githubusercontent.com/97884287/157242303-81f9984a-5ab9-408a-ac42-81e4c9d9b074.png)
<img width="276" alt="Screen Shot 2022-dd03-03 at 18 48 08" src="https://user-images.githubusercontent.com/97884287/157242328-6621c8cf-ddf0-46d3-a0af-9bd7d06902f6.png">

The organizer should be always the team owner unless the booking is confirmed by the admin within the app. Speaking of which, bookings can be confirmed by everyone in the team right now within the app, even the team members. I reckon only Admin and Owner should be able to confirm meetings.

**Comment by juliansg022** [comment]
Hi, I'll take a look at this.

**Comment by juliansg022** [comment]
@milospuac The idea is that the team owner may change his role but conserve its status as the owner? Or to establish in the field the "Owner" option but this is only available to the team owner?

Could you give me more details please?

**Comment by milospuac** [comment]
I think establishing the field "Owner" and that one to be available only to the team owner would make sense. And if the team owner should change his role, or someone else's role to owner, he should be able to change it back instead of being stuck as either Admin or Member. 

Does that make sense?

**Comment by juliansg022** [comment]
I understand, but do you mean that a team could have more than one owner? In that case, the new owners should be able to change their roles to Admin or Member, and change again to Owner?

**Comment by milospuac** [comment]
If a team owner wants to assign someone else as the owner (going on a sabbatical for example) maybe to automatically sets them as Member or Admin? So that way you can't have more than one owner. 

Also, team owner to be the only one in full control of the role assigning. Idk, we are in the realm of personal preference now, what do you think?

**Comment by juliansg022** [comment]
That sounds good to me. I'm going to work on it.

**Comment by denik1981** [comment]
@juliansg022 I think we should not convert an issue in a requested feature. The issue here is that an Owner should not be able to downgrade his role (probably neither have access to change it) if he is the only owner of the team. An Owner can change his role to Admin (or Member) only if there is already another Owner in the Team that can backup the potential owner orphans of the team. Another policy restriction here is that no one can reassign itself to a role with a higher permission level. This means an Admin cannot become an Owner, even if he was an Owner before. It doesn't matter the history of your past role but your current one. The thing about transfer ownership might be a good feature to include as well. 
The inner business logic currently supports the possibility of a multi-owner team but I haven't clearly seen how to make one from the implemented UI for teams.

I'm developing some e2e tests for teams that adhere to this logic.

**Comment by juliansg022** [comment]
@denik1981 I understand, no problem. Can I solve this issue doing changes to PR #2119 or should I open a new PR for this?

**Comment by denik1981** [comment]
@juliansg022 It hasn't been merged yet so it wouldn't make a difference if you modify the already submitted one. If you need a hand with it, I can help you as well. I haven't explored further within the code of your PR. I read the title and the description of what it was supposed to do. In any case (just me) I would separate the concerns for two different PRs for what the resolution of the issue (this one) is and then a proposal (RFC) for an owner's transfer of his role.

Regarding the owner's transferring thing, my two cents on it is that I wouldn't make the owner the Admin after the transfer as it is suggested in the PR. I don't think it makes too much sense. Actually, the Admin represents the delegation of actions from an Owner that don't want to be in charge with. By making him/her the Admin, it will mean more responsibility but with fewer permissions. I can only think of a use case like this, in the case you were assigned to create the team on behalf of someone else (the owner) so you need to then swap the roles. But that's not much of a common use case and it is already cover in the deletion and the later reassignament of the Owner. IMHO, I would consider the Owner's transfership as a prompted question in the case he wants to withdraw from the team and is the only Owner left on it. Just an opinion. You might need to hear other voices as well.

**Comment by juliansg022** [comment]
@denik1981 I like the idea. Then, I'm going to open a new PR to solve this issue, based on your clarifications. After I'll talk with my fellows about the proposal to convert #2119 to an RFC. Thanks for your feedback.

**Comment by juliansg022** [comment]
@denik1981 I have a doubt, should an Admin be able to change the role of an Owner (if exists another Owner)? or only an owner could change the role of another owner?

**Comment by denik1981** [comment]
> @denik1981 I have a doubt, should an Admin be able to change the role of an Owner (if exists another Owner)? or only an owner could change the role of another owner?

The owner is the root user of the team. IMHO, an Admin shouldn't be able to change his role.
Neither Owner should be able to change other Owners' roles because they shared the same level of permissions.
Again, I haven't seen the implementation of a multi-owner team. I'm not sure if this is just a side-effect of how the code is written or if there is a real use behind this that Cal wants to address. In any case, some comments in the code make conditional logic based on the # of owners a team has. So, let's suppose this can be a possibility.

**Comment by agustif** [comment]
I think we could take the lead from github/vercel where they do have a way to transfer ownership, but it does have some extra requirement checks (like the other part being notified by email, and having to accept the transfer), and also requires you to have both a pro account /team in the case of vercel. or not be private repos in the case of free github.

Something like that could work, maybe?
