### ISSUE TITLE
Apple Calendar/CalDav events are getting converted to GMT

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#2139]
Apple Calendar events are shown in the GMT time zone in Cal even though the apple calendar account is set to EST.
This is causing double booking. 
![cal com timezone bug](https://user-images.githubusercontent.com/97884287/158144352-e491ab20-02ba-4ca7-b7bd-3907a33a8ae3.jpg)

**Comment by TheCapsLock** [comment]
I don't know if this issue is similar with the following but there is also a problem with CalDav : events are not on the correct timezone (UTC). They are displayed correctly on the calendar but when you edit them there is a bunch of issues :

* start and end hours are not correct regarding user's UI timezone - not sure if this is a bug on calcom side or on multiple calendar apps (which seems to be strange to me)
* start and end hours are equal (a meeting can be marked as starting at 09:00 and ending at 09:00 while it is supposed to last X minutes/hours)

**Comment by SamuelBlickle** [comment]
This still seems to be relevant, at least it does for CalDAV.

**Comment by PeerRich** [comment]
we promoted @alishaz-polymath two days ago so he will now focus on CalDav. before, caldav was maintained by the community

**Comment by SamuelBlickle** [comment]
This seems to be fixed in the cal.com version but not in the selfhosted one.

**Comment by hit2hat** [comment]
This not fixed in the cal.com. I looking this trouble with Apple Calendar now

**Comment by alishaz-polymath** [comment]
Thank you for the fresh report. I’ll try to identify and resolve this soon. 🙏

**Comment by isaiahdahl** [comment]
+1 on having this issue self-hosted and hosted. 

<img width="1039" alt="CleanShot 2022-09-26 at 19 41 07@2x" src="https://user-images.githubusercontent.com/23046374/192419029-d03085c6-0e3a-4448-a58a-ebd15c0bac9d.png">
