### ISSUE TITLE
Railway deployment problem - crowdin

### ISSUE THREAD

**Issue by titouanvct** [calcom/cal.com#2308]
Hello,

I tried to deploy Cal.com on Railway via the 1-click deployment feature unfortunately, after a few seconds of waiting, I get an error message on Github telling me that :
_❌ Configuration file is invalid. Check the following parameters in your configuration file:
	- Required option 'api_token' is missing
	- Required option 'project_id' is missing_

Can you tell me where the problem is coming from?
Thanks in advance

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Our team will have look

**Comment by evolverine** [comment]
I did the same, and I'm getting something similar: `Error: Input required and not supplied: token` in the `Submodule Sync` action.

**Comment by andrii-bodnar** [comment]
Hi @titouanvct @evolverine, I can help you with the setup. Are your issues are still relevant?

**Comment by evolverine** [comment]
Still relevant for me, yes. Thanks for your help.

**Comment by andrii-bodnar** [comment]
@evolverine could you please share more details about what is happening and when, and some steps to reproduce?

**Comment by evolverine** [comment]
I went ahead and deleted the old project and repository, and started the process anew.

The command `railway run npx prisma db push` failed with `Error: Could not find a schema.prisma file that is required for this command.` I copied `packages\prisma\schema.prisma` to `prisma\schema.prisma` and reran the command. Then I got:

```
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "railway", schema "public" at "containers-us-west-31.railway.app:6452"

Your database is now in sync with your schema. Done in 23.64s

Running generate... (Use --skip-generate to skip the generators)
Error: Could not resolve prisma and @prisma/client in the current project. Please install them with yarn add -D prisma and yarn add @prisma/client, and rerun npx prisma generate 🙏.
exit status 1
```

Then I copied the whole folder packages\prisma\ to prisma\ and reran the command. Got the same error.

At this point, I ignored it, because the database was initialized, and hoped the generators weren't essential.

Minor: Trying to add a user to the db, I saw that the table is called 'users', not 'User' as in [the article](https://blog.railway.app/p/calendso).

Reaching the point of `railway run yarn dev`, I realise that yarn is a dependency that I didn't have installed. I imagine it's an issue that gave me the errors above, so I install yarn, and then rerun `railway run npx prisma db push`. But I get the same error. I ignore it again, make sure the user is still in the database, and rerun `railway run yarn dev`.

This gives me the error `error calcom-monorepo@0.0.0: The engine "node" is incompatible with this module. Expected version ">=14.x <17". Got "18.4.0"`

Apparently, it's hoping to find a lower version of node installed... Do I need to do that, or is it an update that you need to do from your end?

**Comment by andrii-bodnar** [comment]
@evolverine, the topic was about an issue with Crowdin so I thought your issue is also related to Crowdin but it seems like it's related to something else.

**Comment by andrii-bodnar** [comment]
@titouanvct as I can see, the [crowdin.yml](https://github.com/calcom/cal.com/blob/main/.github/workflows/crowdin.yml) uses some environment variables. These variables are used to provide content synchronization with Crowdin.

- Please create the Actions secrets for your repository:
  - `CROWDIN_PERSONAL_TOKEN` - the personal access token generated in Crowdin.
  - `CROWDIN_PROJECT_ID` - ID of the Crowdin project.
  - `GH_TOKEN` - the personal access token generated in GitHub (only the `repo` scope is required).

**Comment by evolverine** [comment]
@andrii-bodnar, could you please guide me where I need to file this bug, then?

**Comment by andrii-bodnar** [comment]
@evolverine it's not a but. You need to configure the Action Secrets in your repo as I mentioned in my previous message.
