### ISSUE TITLE
Automated Holiday Blackout Dates

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2397]
### Discussed in https://github.com/calcom/cal.com/discussions/1370

<div type='discussions-op-text'>

<sup>Originally posted by **Pintadog** December 21, 2021</sup>
Hi, looking for options that would allow me to exclude certain days of the year. An example use case for this would be used for repeating events such as holidays, company events, or personal events. 

Would also be nice if these settings could be shared/ imported with people, so as not to have to manually add these blackout dates for people of the same company and cultural background. </div>

**Comment by LuisChiej** [comment]
Hello @PeerRich, Would like to help out with this issue

**Comment by PeerRich** [comment]
people should use the holiday feature of their calendar

**Comment by louisbarclay** [comment]
I couldn't figure this one out. I have UK holiday calendar enabled in my GCal, but this gives all-day events (which aren't marked as busy) so Cal.com doesn't block out those days. I couldn't find any other special 'holiday mode' on GCal that allowed me to prevent those days from being available. Feature request here would be to have a toggle so that all-day events in calendars can be respected as meaning that scheduling is not possible on them.

**Comment by nicwortel** [comment]
To @louisbarclay and anyone else stumbling upon this issue:

I experienced the exact same issue. Events in the Google holidays calendar seem to be implicitly considered as "free" because they are full-day events, so they are not considered by Cal.com when checking your availability.

I solved this by subscribing to a different, external calendar which explicitly marks the events as "busy". https://www.officeholidays.com/ is working well for this purpose. Find your country via the menu, click "subscribe to calendar", choose the right iCal URL (one that only contains official public holidays), and add it to Google Calendar. Don't forget to enable the new calendar in your calendar settings in Cal.com.

Now public holidays in my country are no longer available on my booking pages.

**Comment by arguemore** [comment]
> To @louisbarclay and anyone else stumbling upon this issue:
> 
> I experienced the exact same issue. Events in the Google holidays calendar seem to be implicitly considered as "free" because they are full-day events, so they are not considered by Cal.com when checking your availability.
> 
> I solved this by subscribing to a different, external calendar which explicitly marks the events as "busy". https://www.officeholidays.com/ is working well for this purpose. Find your country via the menu, click "subscribe to calendar", choose the right iCal URL (one that only contains official public holidays), and add it to Google Calendar. Don't forget to enable the new calendar in your calendar settings in Cal.com.
> 
> Now public holidays in my country are no longer available on my booking pages.

This worked for me. Thank you @nicwortel!
