### ISSUE TITLE
Feature Request: more OAuth options

### ISSUE THREAD

**Issue by YassinEldeeb** [calcom/cal.com#2511]
### Describe the solution you'd like

Adding one or two of the following OAuth providers as OAuth options to the login page.

- `Github`
- `Twitter`
- `LinkedIn`

**Comment by YassinEldeeb** [comment]
I'm willing to contribute adding this.

**Comment by PeerRich** [comment]
we won't be adding more OAuth providers yet as some studies have shown it's better to have email + one primary SSO provider and Google is the biggest one so far.

it's really really hard to remove OAuth providers later

**Comment by alexanderadam** [comment]
I'm not quite sure whether this is the right place to ask but therefore it is also not possible to authenticate against an selfhosted authentication provider (i.e. [Authelia](https://www.authelia.com/), [Keycloak](https://www.keycloak.org/), [Authentik](https://goauthentik.io/), [GitLab](https://docs.gitlab.com/ee/integration/oauth_provider.html))?

Because I thought that the integration OpenID Connect (OIDC) or OAuth2 providers is similar everywhere and only URLs and secrets differ?
Am I mistaken here? :thinking:

**Comment by celevra** [comment]
openId Connect is really needed and easy to implement

**Comment by francoisauclair911** [comment]
Hello, just checking if there has been any progress on this, we would love to be able to integrate with keycloak and OIDC protocol
