### ISSUE TITLE
If a caldav server stops responding, it takes Installed Apps Page down.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2786]
Steps
- Add a CalDAV  URL that works
- Make the corresponding server stop responding. The connection should be made but it should just not respond with any byte like https://blackhole.webpagetest.org/
- See that installed page keeps loading forever and the worst thing is you can't change the URL so that the issue can be fixed

**Comment by alishaz-polymath** [comment]
Hey @hariombalhara can you confirm this is still persistent?
From what I could see, in case a particular calendar takes a long time to respond (or times out) after some time, it just returns this screen. This was arguable fixed some time ago, I think? 🤔 

![image](https://user-images.githubusercontent.com/52925846/229102668-49655fc6-bd5b-491e-8ca4-11050ffde3bc.png)


I would argue it could still be improved if we only delay the confirmation of the calendar lagging instead of holding up the entire page for it, but that would probably require an RFC. What do you think?

**Comment by alishaz-polymath** [comment]
Closing this as the issue doesn't seem to exist with the new method of listing the connected calendars. Feel free to open if found otherwise 🙏
