### ISSUE TITLE
Webhooks not triggered for reschedules

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2877]
> I noticed that the Webhook works great for creating new appointments and cancelling, but does not seem to trigger on the Reschedule.

**Comment by alishaz-polymath** [comment]
I'll take a look

**Comment by alishaz-polymath** [comment]
I tried to reschedule, and it **did** trigger the webhook 🤔 
I rescheduled from the organizer's POV as well as from the booker's POV and on both the occassions, it did trigger.

When I clicked on `request-reschedule` however, the event was removed from the list, but webhook wasn't triggered. I'm not sure what the best course of action here is since when the booker ends up rescheduling, it would trigger the webhook.

**Comment by TheCapsLock** [comment]
I don't know if it's related but when an event is rescheduled, caldav event is not updated too

**Comment by alishaz-polymath** [comment]
@TheCapsLock it is probably unrelated. Could you please raise a new ticket for this?
🙏

**Comment by alishaz-polymath** [comment]
This issue was fixed earlier with #2987
