### ISSUE TITLE
Rescheduling on a non-yet approved opt-in booking (and creates duplicate booking)

### ISSUE THREAD

**Issue by TheCapsLock** [calcom/cal.com#2990]
### Issue Summary

An approval should be required when rescheduling a not yet approved booking.

To be noted : in that peculiar case we get a duplicate of the booking : one approved the other with pending approval (without a clear link between both) :

![Sans titre](https://user-images.githubusercontent.com/3322481/172327289-0471668d-0bd1-43ff-bdf8-585a61a04d39.png)

### Steps to Reproduce

1. Create an opt-in booking
2. Using the Web UI or the hyperlink in the email, reschedule it
3. Organizer can see in /bookings/upcoming something like the screenshot attached above

### Technical details

- Firefox 100.0.2 ; cal.com v1.6.3 ; node v14.19.3
- Caldav server : nextcloud 24.0.1

**Comment by gibranlamarca** [comment]
@TheCapsLock I couldn't reproduce your issue, but I recorded a Loom video. Please watch it and tell me if I did something wrong!
https://www.loom.com/share/d458154c85d5461aad34975a2d90ba68

**Comment by TheCapsLock** [comment]
@gibranlamarca I used a different path : I rescheduled the event using the link found at the bottom of the mail saying that booking is confirmed (but that it should be approved)

The link is named "Gérer cet événement" and points to path  /cancel/<str>

**Comment by gibranlamarca** [comment]
@TheCapsLock for some reason I'm not receiving the confirmation email.. That's weird. I'm looking into it.

**Comment by gibranlamarca** [comment]
@TheCapsLock Ok I managed to reproduce the issue

**Comment by gibranlamarca** [comment]
So.. I've been looking into this and I think the solution is just to remove this "Manage this event"(Img 1) link, or atleast revamp it, because it leads the user for a page where you can actually reschedule the event or cancel it. The problem is, you shouldn't be able to reschedule a meeting if you don't confirm it yet.. I see two workarounds here: to remove it completely(the "Manage this event" link) or to remove the "Reschedule instead"(Img 2) button, still letting the user cancel it via e-mail. 

![Screen Shot 2022-06-20 at 09 17 34](https://user-images.githubusercontent.com/709693
![Screen Shot 2022-06-20 at 09 20 10](https://user-images.githubusercontent.com/70969354/174600314-e2fffb6a-c39c-450c-9570-afdf3ae87abb.png)
54/174599930-f2ae4251-4148-46be-acca-7156c851df7e.png)

**Comment by zomars** [comment]
Let's continue the discussion in here #3064
