### ISSUE TITLE
og-image not working for event-links

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3159]
i believe this used to work, now it throws an error: 

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/8019099/175834998-f312b21c-0b06-4ae2-9774-83e310262026.png">

test yourself:

https://cards-dev.twitter.com/validator

https://cal.com/peer/30min

**Comment by alishaz-polymath** [comment]
It definitely used to work. Probably bugged out in some new changes. Will get it sorted upon my return. 🙏

**Comment by alishaz-polymath** [comment]
I've identified the issue. For some reason (probably consistency among dynamic teams, single user and teams), the `username` is not returned as part of the Profile prop but slug is returned which is now the entire username-slug combination instead of it being just the username (which was the case earlier) and that's why the avatar module now attempts to find the avatar for the slug instead of the username itself. The combination is only username in case of the `/[user]/` page but becomes `/[user]/[type]` for the availability page which is why it breaks in finding the avatar in that page

**Comment by PeerRich** [comment]
I believe this was fixed, correct?

**Comment by alishaz-polymath** [comment]
It's not merged yet. @zomars mentioned a concern so I'm running extra checks on it to be sure, and then it should be fine. 😊
