### ISSUE TITLE
Unconfirmed Meetings Should Still Include a Calendar Invite

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3331]
### Is your proposal related to a problem?

Problem: On the opt-in booking links, if you submit a time to book with someone, once it’s sent, but not confirmed, you aren’t aware of the booking anymore. This leads to people forgetting or possibly double booking themselves because there’s no time being held on their calendar.

### Describe the solution you'd like

Proposed Solution: There should still be a calendar invite listed as “TENTATIVE” to hold the time until the booking is confirmed by the other party. Once the booking is confirmed or rejected, a confirmation and/or cancellation booking needs to be sent to the user.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by PeerRich** [comment]
we thought about this a lot, but it would be an issue if you don't want to block out that time slot if someone books

**Comment by shirazdole** [comment]
Could we have a checkbox on the event page saying "Check this box if you would like to receive a tentative calendar invite to hold the booking time. This is not a confirmed meeting and other folks will not be able to book during this time." Something along those lines?

**Comment by kunal-sharda** [comment]
@PeerRich Facing this problem right now where several people booked over the same time slot, because I was unable to have a tentative blocked out time. This should be an option when booking out times so multiple bookings don't happen at the same time before they are confirmed.

**Comment by ivanAndCode** [comment]
@PeerRich I am facing the same problem! 
Here's how I got to this place. 

I wasn't sure if I was going to be busy or not.... someone sent me an invite and I DID NOT accept or decline it for 2 days... 
I ended up having several people booked for the same timeslot! ...and someone else booked the slot that ignored my "before event/after event" limits.

So my "bookings" tab looked like this:
- 10:20 to 10:40, unconfirmed, person A
- 10:20 to 10:40, unconfirmed, person B
- 10:40 to 11:00, unconfirmed, person C

I agree with the idea of the unconfirmed booking creating a "placeholder" (maybe as an on/off setting) in the calendar SO THAT nobody else can book it before the calendar owner MAKES A DECISION.
