### ISSUE TITLE
[CAL-506] Enable Cal Video (Daily) Recording

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3651]
Three things. We need to:

* enable DAILY_SCALE_PLAN=true in .env
* send a follow up email after the call with the download link of the Daily recording
* show the ”Download Recording” in "past bookings" as mp4 with all participants visible

Daily.co Docs: https://docs.daily.co/guides/products/live-streaming-recording/recording-calls-with-the-daily-api

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bc97f278-3d0a-429f-a591-871eac86af3b/8cb5b6f4-be2c-452b-b1f0-e4bef2074175)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-506](https://linear.app/calcom/issue/CAL-506/enable-cal-video-daily-recording)</sub>

**Comment by mocherfaoui** [comment]
to show a "Download Recording" button all recordings should be stored in the cloud right? because they're stored locally currently
https://github.com/calcom/cal.com/blob/ede987ba198ccf50ebeb1c6bf6e650b966603b76/packages/app-store/dailyvideo/lib/VideoApiAdapter.ts#L121
there is an endpoint to get a recording link [`GET`  `/recordings/:id/access-link`](https://docs.daily.co/reference/rest-api/recordings/get-recording-link) but the generated link is valid for 12 hours max

**Comment by PeerRich** [comment]
it would be stored in the daily.co cloud
