### ISSUE TITLE
Some test to verify that apps are installed after the build

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3694]
See https://github.com/calcom/cal.com/issues/3674#issuecomment-1204893918 for reference. 

If seeding doesn't happen, newly deployed instances will not have the app-store apps.

We need to ensure that only `yarn build` command is run to verify this because production deployments run only that command.

**Comment by PeerRich** [comment]
@hariombalhara is this still open?

**Comment by usmaann1** [comment]
/attempt #3694
Test Plan: Verification of Installed Apps after the Build

Objective:
The objective of this test plan is to verify that the required apps are successfully installed after the build process. The test plan includes both manual tests and a list of automated tests to ensure comprehensive verification.

Test Scope:
The test scope includes verifying the presence and functionality of installed apps on the target system after the build process.

Test Environment:
The test environment should consist of:

- The target system or device where the build is deployed.
- Access to the installed apps on the target system.
- Test data or content that requires the functionality of the installed apps.

Test Plan:
4.1 Manual Tests:

4.1.1 Visual Inspection:
Objective: To visually inspect the target system and validate the presence of the installed apps.
Steps:

- Access the target system or device after the build process.
- Navigate to the list of installed apps or applications.
- Verify that the required apps are present in the list.
- Validate the app icons and names to ensure they match the expected apps.
- Open each app to visually confirm its functionality.
- 4.1.2 App Launch and Basic Functionality:
- Objective: To test the basic functionality of the installed apps.

Steps:
- Launch each installed app one by one.
- Verify that the app successfully opens without any errors.
- Perform basic operations or functions within each app (e.g., navigating through menus, and performing simple actions).
- Ensure that the core functionalities of the apps are working as expected.

4.1.3 App Integration Testing:
Objective: To test the integration of the installed apps with the target system.
Steps:
- Identify the areas where the installed apps should integrate with the target system (e.g., sharing options, file associations).
- Perform actions that require interaction between the target system and the installed apps.
- Validate that the installed apps are properly integrated and function seamlessly within the target system.

4.2 Automated Tests:

4.2.1 App Installation Verification:
Objective: To automate the verification of installed apps using command-line tools or scripts.

Steps:
- Develop a script or utilize command-line tools to retrieve the list of installed apps.
- Compare the retrieved list against the expected list of required apps.
- Generate a report indicating any discrepancies between the expected and actual list of installed apps.

4.2.2 App Launch and Smoke Testing:
Objective: To automate the launch and basic functionality testing of installed apps.

Steps:
- Utilize automation tools (e.g., Selenium, Appium) to launch each installed app.
- Perform basic operations within each app, such as navigating through menus or interacting with UI elements.
- Validate the functionality of the apps by asserting expected outcomes and detecting any errors or crashes.

4.2.3 Integration Testing:
Objective: To automate the integration testing between the installed apps and the target system.

Steps:
- Develop automated tests that simulate integration scenarios (e.g., sharing files, opening app-specific file formats).
- Execute the automated tests to validate the seamless integration between the target system and installed apps.
- Verify that the expected integration functionalities are working as intended.

Test Reporting:
For each test, document the observed results, any deviations from expected behavior, and any defects found during testing. Report and track the issues found using a bug-tracking system.

Test Completion Criteria:
The test execution is considered complete when:

- All manual tests have been performed and documented.
- All automated tests have been executed, and their results are documented.
- Any identified issues have been reported and tracked.

**Comment by hariombalhara** [comment]
This was a one-off bug that happened like 2 years back. Never happened since then. 

So, I feel it might not be worth it to write tests for this scenario.
