### ISSUE TITLE
Invited Team Members Auto-Added to Teams

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3723]
### Issue Summary

When a team member is invited and they have to create a new account. After creating their account, they are auto-added to the team they were invited to. No opportunity to deny or accept the invitation.

[Twist Thread for Reference with Bird Eats Bug](https://twist.com/a/195135/ch/554218/t/3671992/)

**Comment by alannnc** [comment]
@Jaibles @zomars 
I'm reaching you two in order to clarify this scenario.
Right now the current scenario is this: 

- An invited user creates his account and gets automatically assigned to his team.

If he tries to create a new account from our signup, the email already exist as inviting a new user would create a passwordless user, thus he receives an error there.

Should we leave this as it is? Or after creation of the user from an invite link he then should accept/reject invitation.

**Comment by shirazdole** [comment]
@alannnc apologies just seeing this, I think this is the scenario:
- User creates an account or already has an account
- User is invited to join a team
- User should have the ability to accept or reject
- Bug: User does not have ability to accept or reject, user is automatically added to the team
- Therefore, user should always have the option to accept or reject the team invitation

**Comment by PeerRich** [comment]
i think this is expected behavior
