### ISSUE TITLE
Conflicting Sales Links

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3801]
### Issue Summary

Cal.com/shiraz/sales is somehow merging with cal.com/team/cal/sales. 
<img width="310" alt="CleanShot 2022-08-10 at 08 49 01@2x" src="https://user-images.githubusercontent.com/16177678/183993329-4cba6c15-dab7-47fb-a567-1296d566fafe.png">

<img width="296" alt="CleanShot 2022-08-10 at 08 49 08@2x" src="https://user-images.githubusercontent.com/16177678/183993365-2d21f397-f032-4290-9b3c-8c93b5a76c56.png">

Technically, this link:https://cal.com/shiraz/sales shouldn't even work, let alone pull in the other cal.com link: https://cal.com/team/cal/sales

**Comment by agustif** [comment]
I believe the problem comes from here

The thing is the page for /user/event-type-slug

search any events the user is member of, in users, not only their own owned events

if that makes sense

so since your user shiraz is also a member of the cal ‘sales’ event when you visit shiraz/sales, it finds that event, and thinks it’s that one

We have a problem of not having unique slugs for event-types globally, but we need to only check the ones you own I think…

havent tried to replicate

but probably any cal team member would have this

and I dont know how it will behave if you create your own sales event type
 https://github.com/calcom/cal.com/blob/88b41968126fb8768ecf86d56d383430c9b07757/apps/web/pages/%5Buser%5D/%5Btype%5D.tsx#L98-L103
