### ISSUE TITLE
Required additional inputs are not actually required

### ISSUE THREAD

**Issue by MathisTimo** [calcom/cal.com#3918]
### Issue Summary

When completing the form to book en event I can sumbit the form even if some custom additional inputs that are required are empty. 

### Steps to Reproduce

1. Went to the admin dashboard, add a custom addition field to an event 
2. Checked the box "Is required"
3. When testing the event, even if the new custom field is empty I can book the event
4. Only the first two default fields are actually required (Name & Email)

I use the live version of Cal, not self-hosted.

**Comment by milospuac** [comment]
Hi there

Just notified the engineering team to investigate. Thanks for reporting it.

**Comment by gondar00** [comment]
I believe the issue lies [here](https://github.com/calcom/cal.com/blob/main/packages/prisma/selects/event-types.ts#L17) @ `Prisma.validator<Prisma.EventTypeSelect>()({...})` I wasn't able to find any references to `Prisma.EventTypeSelect` can someone please point me where that can be found? 

I can see that without a validator the data loads up fine - [here](https://github.com/calcom/cal.com/blob/main/apps/web/pages/event-types/%5Btype%5D.tsx#L2077)

**Comment by PeerRich** [comment]
hey @MathisTimo, this will go live this week!
