### ISSUE TITLE
Cannot create Recurring Booking with API

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#3975]
### Is your proposal related to a problem?

Cannot create Recurring bookings with a post ApiCall. Even though I give it an event type of recurring type i.e. {"freq":2,"count":15,"interval":1}, it still posts the booking as a one time booking, with no "recurringEventId". Thus it;s not getting displayed in Bookings -> Recurring 
evenTypeId : 206  is a recurring event type of {"freq":2,"count":15,"interval":1}

{
    "eventTypeId": 206,
    "userId": 472,
    "startTime": "2022-08-30T17:00:00.000Z",
    "endTime": "2022-08-30T17:15:00.000Z",
    "title": "API Recurring Workaround",
}

I also tried to add a "recurringEventId": "a6b2bab9-8a3c-447d-be56-85f70c09140z" to the object but getting a bad request.

### Describe the solution you'd like

It would be great to be able to create a recurring booking, maybe based on the EventType 

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by PeerRich** [comment]
can you add more context to your ticket? @newz666

**Comment by newz666** [comment]
Sorry for that. Does that work? @PeerRich

**Comment by PeerRich** [comment]
@leog any ideas?

**Comment by leog** [comment]
@PeerRich We have discussed this in Slack with Octavian. In order to support this from the API, the API should create a booking for each recurring event in the series setting the `recurringEventId` parameter to be the same ID for every booking. For this to happen, the API should first of all detect the event type of the booking to be recurring, get a number of bookings to create by query parameter (equal or lower than the maximum count set in the event type) and trigger the booking of each instance as mentioned. I can grab this once I finish what I have in my plate, or maybe @agustif with the most API knowledge can do it in a jiffy.

**Comment by PeerRich** [comment]
@leog feel free to pick this up for 2.1 once you have the other things on your plate done 🙏
