### ISSUE TITLE
[CAL-104] /public-booking - 12/24h time format: Can we check users locale settings (Intl JS API)

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4340]
![Image](https://user-images.githubusercontent.com/4536123/189387254-77712657-f119-4359-9537-911d2325e9ae.png)
- As an American (quote) I basically never use 24h time so it feels really unfamiliar/unfriendly.
- Similarly, the date format "7 September" in the top right feels unfamiliar. I suggest looking at the user's locale settings (Intl JS API)
- Okay now just for fun I clicked to expand the time zone dropdown and I just noticed that there is a way to toggle am/pm — but (a) again, it should do ampm by default for en-us locales, (b) it's in a place I'd never normally look since the default timezone was correct for me already.
- The ampm option wasn't remembered/respected on the following screen (but the date format does look better here):

At the very least we can do "September 7" here instead of "7 September" which would be a slight improvement.

**Comment by MatheusBeniniF** [comment]
Hi @Jaibles, on user settings you can set the format if you prefer 12h or 24h, we should ignore that?

**Comment by popken** [comment]
Hi @MatheusBeniniF, from my understanding the 12h or 24h setting does not have an effect on the calendar widget. I am trying to do the opposite of what @Jaibles is trying to do. My meeting partners are all German, the 12 h format is confusing for them. I would be more than happy to have the ability to make the 24h format the standard setting.

**Comment by JeroenReumkens** [comment]
Hey @Jaibles  Shall we use this issue to track progress and discussions on this? Hopefully we can then come up with a list of changes required to make this perfect! 👌

Last week we fixed an issue where users would always see the 24h layout (see #4865 ) when they were logged in, which is partially related to this issue. 

## The fix we applied last week looks as follow

### Logged in:
* We always take your AM+PM / 24h setting from your profile settings and use this on the public booking page
* You don't see the AM+PM / 24h toggle in the timezone dropdown 
* If you want to change the time format, you need to go to your profile settings (we don't point you there from the booking page, bad UX currently, but quickest fix we could do)

### Not logged in:
* We look at your browser and guess the time format, and use that
* After that the time format is remembered in localstorage
* You can open the timezone dropdown and change your time format in there. If you do that, the value in localstorage is updated and remembered. If you come back to the site and still have the localstorage value, we use that setting rather than the guess based on your browser. 

## Next steps

I think there's still a few things we could improve, but I'm of course also wondering what you think:
1. **Make time format toggle more visible:** In general we think the time format toggle is quite hidden in the timezone dropdown. I think we need to move it out of the dropdown and give it a better place above / underneath the timezone dropdown? 
2. **What to do with logged in users:** Should logged in users be able to change their time format to anything different than their settings? 
  a. If they do so, will we also update the setting in the profile? 
  b. If not, do we remember it in localstorage and use that value (which is then different from settings?) 
  c. Offer the toggle for logged in users, but threat it as a one time change, explaining them with an 'i' that if they want it to be persistent they should update their settings (Idea by @alishaz-polymath )
  d.  — Start's to get confusing here! 😉  
3. **Behaviour for not logged in users:** I think the current behaviour is the right one. 
4. **Date formatting:** When we nailed the time format, we should also use this format for the dates like you mentioned in this ticket as well.

**Comment by popken** [comment]
Hi @JeroenReumkens,

I just got the newsletter where the timezone fix is mentioned. Maybe it's just me but it doesn't seem to work:

I'm logged in. My profile setting is set to 24 hour format (I'm in Germany).  
Expected behaviour:
"We always take your AM+PM / 24h setting from your profile settings and use this on the public booking page"
Actual behaviour:
Timezone is correctly Berlin/Amsterdam. But: AM/PM shows on the calendar widget, no switch / no possibility to change to 24 hour format. 

I'm not logged in:
Actual behaviour:
Timezone is correctly Berlin/Amsterdam. AM/PM shows on the calendar widget, the (almost hidden) switch shows, I can change to 24 hour settings.

**Comment by JeroenReumkens** [comment]
Hi @popken  Sorry for the late response, I only saw your mention just now. 
A few hours ago we did a new change to avoid a lot of confusion about this. The new behaviour is: 

* On the public booking page the toggle for changing 12/24h is back, it is now positioned on top of the hour slots. The profile setting is not used there anymore, but if you change the 12/24h setting it is remembers locally in your browser. The default format we assume is being done on your browser locale, not your location. 
* The setting in your profile is only used in the authenticated part of Cal, not on your public profile pages (we added a note next to that field explaining that).
