### ISSUE TITLE
[CAL-105] /onboarding - View of app before steps appear

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4383]
There's still a long view of the app before onboarding starts.. can we do anything about that?

**Comment by zomars** [comment]
We can go many way in order to prevent this flash.

- We can redirect from signup directly to onboarding (as it is expected) this won't cover logins tho.
- We can redirect from SSR, we would need to introduce SSR in all pages (which I'm personally against)
- We could set a temporary cookie at login/signup that would be read on a `next.config.js` redirect that will take you to onboarding even before SSR. This would be the less intrusive options but will need some special logic and testing to avoid unwanted redirects.

**Comment by Jaibles** [comment]
Honestly I can't say I've any strong preference on any of those given the considerations are more on the technical end of things.

**Comment by PeerRich** [comment]
did we end up fixing this @Jaibles? doesnt look like a quick win

**Comment by Jaibles** [comment]
No this is not fixed

**Comment by PeerRich** [comment]
@Udit-takkar wanna look into this?
