### ISSUE TITLE
[component] simple date selector - calendar arrows layout broken

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4389]
![Image](https://user-images.githubusercontent.com/4536123/189656361-2ceb5727-9e86-4a67-b289-6cc46a5a1a5e.png)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13738%3A97458)

![Image](https://user-images.githubusercontent.com/4536123/189656538-7d175b24-fe25-4815-b031-d16276f22abf.png)

**Comment by MuriloAmarals** [comment]
On my localhost the arrows layout aren't broken
![image](https://user-images.githubusercontent.com/87545137/189739768-dd99ec77-7f9b-40ed-9bd0-f7514710ddc6.png)

**Comment by alishaz-polymath** [comment]
This issue seems to be on prod but not on local. From the looks of it, the `Calendar.css` file in the daterangepicker component is not being loaded on prod but works just fine locally. 🤔 
I think I would just take the CSS rules in that file, add them to the CSS file that we're using with this with our custom changes and that should fix it. I'd also take this opportunity to optimize the css file a bit
