### ISSUE TITLE
Unable to make a booking in chrome incognito session

### ISSUE THREAD

**Issue by gzim-joinfella** [calcom/cal.com#4420]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

We are integrating cal.com an an embed in our web app portal where we allow our customers to make appointments.
Something we noticed is that when our customers are in incognito session in chrome, they are not able to make the appointments at all. 

The root cause is that in incognito, chrome settings are set to block 3rd party cookies by default. 

### Steps to Reproduce

1. Open chrome incognito
2. Navigate to our custom React.js web portal
3. Try to use cal.com through the embed

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
![Screen Shot 2022-09-13 at 09 36 51](https://user-images.githubusercontent.com/100677978/189841133-b0b70421-190c-4dc0-afaf-e6f84663ee21.png)
![Screen Shot 2022-09-13 at 09 36 43](https://user-images.githubusercontent.com/100677978/189841146-5bee1275-3197-4003-a890-3b61e9730118.png)

### Technical details

- Chrome, incognito
- 3rd party cookies not allowed

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. 

Our team will investigate this. Are you using our V2?

**Comment by hariombalhara** [comment]
This is an issue due to Rainbow kit integration. RainbowKit.tsx seems to use **_wagmi_** which uses localstorage which isn't accessible in incognito mode. It should be fixed there cc @PeerRich 
<img width="938" alt="Screenshot 2022-09-13 at 5 25 28 PM" src="https://user-images.githubusercontent.com/1780212/189894547-238ebda0-2ab7-477c-b098-5a7a25d68f9c.png">


Because Rainbow isn't needed if EventType doesn't have it enabled, it shouldn't cause booking pages to break in other cases
This recently merged https://github.com/calcom/cal.com/pull/4409 PR fixed that and thus the error no longer comes in Event Types not using RainbowKit

**Comment by gzim-joinfella** [comment]
@hariombalhara any ideas if there's something we can do about this as a quick workaround? We had this issue reported to us three times by different customers. 

It is frustrating because they just paid for the product but can't progress on making the appointment with the coach. 

thanks for looking into this 🙏

**Comment by hariombalhara** [comment]
@gzim-joinfella If you take the latest pull of main, it should be fixed unless you have Rainbow kit integration in your Event Types.

**Comment by gzim-joinfella** [comment]
@hariombalhara I am using the hosted cal.com version at http://app.cal.com/ via an iframe

**Comment by hariombalhara** [comment]
That should go live soon. cc @zomars

**Comment by PeerRich** [comment]
i believe this has been fixed a long time ago. can you try again with the most recent version?
