### ISSUE TITLE
V2 Implementation for logout page

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4525]
Forgive me if it's a duplicate. 
/auth/logout page isn't V2

<img width="1093" alt="Screenshot 2022-09-16 at 3 22 41 PM" src="https://user-images.githubusercontent.com/1780212/190612283-278ffcaf-b6a3-477b-b4a1-644fed455a37.png">

**Comment by hariombalhara** [comment]
cc @Jaibles for designs

**Comment by PeerRich** [comment]
true, but low priority

**Comment by Emmanuel-Melon** [comment]
> true, but low priority

Is there a design available for this?

**Comment by agustif** [comment]
> Not yet Emmanuel Gatwech.
> 
> I'm assuming we can't just bring them to the login page or cal.com automatically then Hariom Balhara?

We certainly could I think!

https://github.com/calcom/cal.com/blob/a1d4589e66e8adba10612e6dcab7edf914f1c874/apps/web/pages/api/auth/%5B...nextauth%5D.tsx#L209

I think we only have such a logout page, because it contains a ?survey=true props/url query argument, which in case of being true (only when removing your account from cal.com) redirects you to a feedback form instead of the regular page.

Maybe because of this , we want to keep the signout page? Could have a counter in the go back to login page that was something like 'Redirecting you to login...' and took a couple seconds or so to do so?

**Comment by hariombalhara** [comment]
@Jaibles yeah we can totally take the user to log in page and it makes sense

@agustif yeah we can do that. 

I think we should rename the issue to redirect to login automatically from logout page. If account is deleted, logout can rediredt to survey page.

**Comment by PeerRich** [comment]
done
