### ISSUE TITLE
404 error on https://cal.com/embed.js

### ISSUE THREAD

**Issue by SvenAlHamad** [calcom/cal.com#4629]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

We have been using the embed component on our website for our enterprise lead gen form for people to book product demo calls with our sales team. Since a few weeks now, the embed component stopped working, while we haven't made any changes to the site on our end. By looking at the network panel we noticed that `https://cal.com/embed.js` now throws a 404 error. 

### Steps to Reproduce

1. Implement the cal.com react embed into a page
2. Open the page and check what you get

### Technical details

- Tested on safari and chrome
- We are using the react implementation

**Comment by thom4parisot** [comment]
Yeah, I ran into this. This goes against the documentation https://developer.cal.com/embed/install-with-javascript, unless it is not up to date.

It's weird because it's part of the product, and all of a sudden, my support system on a website does not appear anymore. Which is "a bit" blocking.

Is there a new URL for the embed? Do you plan to setup a redirect to keep Cal.com working on customers websites?

**Comment by PeerRich** [comment]
@hariombalhara this was fixed, right?

**Comment by hariombalhara** [comment]
Yes
