### ISSUE TITLE
/event type /limits - Minimum notice period does not appear to be saving

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4678]
https://user-images.githubusercontent.com/4536123/191956436-ad177e6c-2582-464d-b3c4-75f31ab456dd.mp4

Also had report of a user saying it was capped at 120 minutes. But I suspect the placeholder threw him off. Will update that placeholder design to be lighter.

> That being said, it looks like the minimum booking notice is now capped at 120 minutes. When I had last used the product and set up my event types, I had this set to at least three days in advance.

**Comment by emrysal** [comment]
@Jaibles 

> Also had report of a user saying it was capped at 120 minutes. But I suspect the placeholder threw him off. Will update that placeholder design to be lighter.

This was due to the error fixed within https://github.com/calcom/cal.com/pull/4656 - the input field wasn't right before that was merged and capping to 120. That hotfix was missing a change that set the value of the field on load which caused the above behaviour, it was saving but it was not showing in the input on load.
