### ISSUE TITLE
Mobile /Public Booking page - Timezone dropdown goes offscreen

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4724]
![image](https://user-images.githubusercontent.com/4536123/192636073-a7857bdc-bba8-49db-bcba-c1866bb602ae.png)

The dropdown should be aligned left of the screen and below the icon & text with a max width ensuring it doesn't go off screen.

Requires confirmation and duration text size are also a size bigger than the other items and should be aligned.

**Comment by davidtaing** [comment]
Hi @Jaibles,
Can I please work on this issue?

**Comment by davidtaing** [comment]
Hi Peer,
I'm having trouble with the new Dropdown menu component because Radix renders the Dropdown Content in a Portal. So the content is contained in a separate DOM subtree.

My approach would be to change the flex-direction to column for viewports < 768px and then tidy up the styling.

But this doesn't work since the Dropdown content is not child of the flex container.

## From Changing the Tailwind ClassNames in Browser

![image](https://user-images.githubusercontent.com/8443215/192908636-3b7e96cc-a891-4230-a85e-20a55469672e.png)

https://github.com/calcom/cal.com/blob/7256dbf84fe79f76f78f54b6453037c269b789bb/apps/web/components/booking/pages/AvailabilityPage.tsx#L244

https://github.com/calcom/cal.com/blob/7256dbf84fe79f76f78f54b6453037c269b789bb/apps/web/components/booking/TimeOptions.tsx#L36

### Resulting Changes

320W
![cal com_teeang_30min_date=2022-09-30 (2)](https://user-images.githubusercontent.com/8443215/192908893-1fe43b70-ff65-443e-b34c-78f495568fe7.png)

768W
![cal com_teeang_30min_date=2022-09-30 (3)](https://user-images.githubusercontent.com/8443215/192908895-7798809d-7c70-4ab2-a9bb-f098216ca446.png)

## Radix Dropdown Menu
Inspecting the example [Dropdown Menu in the Radix Docs](https://www.radix-ui.com/docs/primitives/components/dropdown-menu) shows that Radix is creating another DOM subtree.

<img width="960" alt="58RYPVNYhr" src="https://user-images.githubusercontent.com/8443215/192910105-8e1426ec-b838-4c1d-9d94-59f910c2121b.png">

**Comment by davidtaing** [comment]
I'll poke around the repo and look for the other instances where we have used the Dropdown component. Let's see if I can figure this one out.

**Comment by davidtaing** [comment]
I got much closer and have put in a PR for review. It was quite difficult, but I'm glad I did this. I'm sure I picked up a few skills.

I approached this by using the Primitive Radix DropdownMenu. Got it working. Then I swapped out the primitive components with the calcom Dropdown components.

**Comment by JeroenReumkens** [comment]
This is fixed by #4839. Didn't know this issue existed! 😄
