### ISSUE TITLE
[CAL-266] Cannot update email from settings

### ISSUE THREAD

**Issue by Merlin04** [calcom/cal.com#4783]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When I attempt to update my email on the [https://app.cal.com/settings](https://app.cal.com/settings) page, the network request sent to the `viewer.updateProfile` endpoint does not contain the new URL, so the value does not change. I was able to manually resend the request with the updated email, which appears to have been successful.

### Steps to Reproduce

1. Log in and go to the settings page
2. Type in a new email, click update, type in password to confirm
3. See that the email does not update

### Technical details

* Browser version: Firefox 105.0.1

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
@zomars

**Comment by zomars** [comment]
Not a bug until a team member can reproduce. Adding "needs investigation" until then.

**Comment by CarinaWolli** [comment]
> Not a bug until a team member can reproduce. Adding "needs investigation" until then.

@zomars I could reproduce this. Here is a video showing that it is not working for me:
https://www.loom.com/share/2702cc1ef2da4c818c3aebd5a2a1fbd1

**Comment by jmfonseca** [comment]
Also happening to me.

**Comment by PeerRich** [comment]
we'll investigate!

**Comment by PeerRich** [comment]
@CarinaWolli do you wanna give this a try?

**Comment by CarinaWolli** [comment]
I did some further testing and I came to the conclusion that the email update is actually working. The only problem is that once you leave the page it resets all values. You can see in the [loom video](https://www.loom.com/share/2702cc1ef2da4c818c3aebd5a2a1fbd1) that I am clicking on my Bitwarden extension for my password and that's when the values get reset. So when the password pop-up closes it shows the old email again. 

It's happening because of these changes: https://github.com/calcom/cal.com/pull/4644/files

Maybe @emrysal or @hariombalhara could take a look at this?

**Comment by CarinaWolli** [comment]
@PeerRich is email updating not working? I just tested it and it is working for me
