### ISSUE TITLE
Currently it is not possible to get the 11:00pm slot to open up

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#4884]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1046695/194372841-9c34716c-7615-4744-9ce1-dcc8bb5ec200.png">

<img width="361" alt="image" src="https://user-images.githubusercontent.com/1046695/194372887-b6a63f7e-d4af-4a83-94a0-2a3f2be38d64.png">

**Comment by MatheusBeniniF** [comment]
In my opinion, in this case, it is not possible to schedule a meeting after 22 pm because your meeting is 1 hour long, as in this printscreen, the last available time is at 4:30 pm because my time is set until 5 pm.

![image](https://user-images.githubusercontent.com/88898100/194378310-f5816801-f18d-4fed-b721-f072e31ea51c.png)

**Comment by MatheusBeniniF** [comment]
@PeerRich can you give some feedback about this?

**Comment by PeerRich** [comment]
> @PeerRich can you give some feedback about this?

no clue, @emrysal?

**Comment by PeerRich** [comment]
pretty sure this was fixed a while ago
