### ISSUE TITLE
[CAL-252] Avatar icon not loading properly

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#5213]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b9a0102a-b2d7-4fd1-8680-99344ad9a4b7/f4fc41ed-9801-4425-8e68-c236284179ea)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by harshsinghatz** [comment]
@Udit-takkar Also the avatar is not getting updated from the profile section, I tried it with two accounts. Can you check it on your end?

**Comment by Udit-takkar** [comment]
Yeah there seem to be some problems with the Avatar updating also. I'll be looking into this. Why is this happening.

**Comment by Udit-takkar** [comment]
Yeah there seem to be some problems with the Avatar updating also. I'll be looking into it

**Comment by harshsinghatz** [comment]
@Udit-takkar would you be picking that as well?

**Comment by Udit-takkar** [comment]
@harshsinghatz  yes. the avatar seem to block updating profile.

**Comment by harshsinghatz** [comment]
Is it fixed? because rn it works fine on prod

**Comment by Udit-takkar** [comment]
@harshsinghatz no try creating new account and the avatar won't load or try updating the image in /settings.

**Comment by harshsinghatz** [comment]
Ok let me check

**Comment by harshsinghatz** [comment]
@Udit-takkar  Yeah, i did see and it's working unexpectedly

1. For a new user, avatar doesn't show 
![image](https://user-images.githubusercontent.com/51085015/198812512-9430452d-36de-499f-9c99-8a4c347317af.png)
but changing imgSrc from "https://app.cal.com/hello-world/avatar.png" to "https://cal.com/hello-world/avatar.png" works for some reason

2. I don't know if this just from my end but in main branch when i am trying to change the avatar the request doesn't hit trpc server if the image is md5 encrypted. Whereas if it is a default avatar then it does

Can you check the diff between the current main branch and the prod, because this seems like a new issue

**Comment by Udit-takkar** [comment]
2. yeah the trpc request is not returning any result in the main branch. i don't understand why is it happening. maybe due to trpc v10

**Comment by harshsinghatz** [comment]
Can you compare the main branch with the production?

**Comment by hariombalhara** [comment]
@harshsinghatz Wrt your point-1. This seems like a cloudflare caching issue with `cal.com` only. With `app.cal.com `it works fine.
See [this](https://www.loom.com/share/c631a2f0e0804cb2a8fac6ce0dfd0cf0) loom that clearly shows the issue. @baileypumfleet maybe Cloudflare needs some tweaking?

Wrt Point-2, the issue seems to be happening due to middleware. Deleting the middleware.ts file solves the issue and trpc mutation endpoint responds immediately.

**Comment by harshsinghatz** [comment]
@hariombalhara It seems both the domains have caching issues because earlier I saw problems with both the domains

Can you point out exactly what issue is middleware causing, is it like an infinite loop of redirects?
And also if we are sending the default image trpc endpoint responds, so is there any particular problem with the format of data?

**Comment by hariombalhara** [comment]
Middleware is simply not forwarding the request to next.js endpoint. It seems to be doing some processing of own and it's stuck there.

**Comment by hariombalhara** [comment]
Okay, so it's a known Next.js bug. People are reporting it.
https://github.com/vercel/next.js/issues/39593
https://github.com/vercel/next.js/issues/39262

**Comment by harshsinghatz** [comment]
That makes sense because after encryption the avatar data is around 225KB.
Should we prompt for some less bulky hashing technique?

But this issue wasn't present before, so an RCA would be needed for this (as this issue is only on main)

**Comment by Udit-takkar** [comment]
@hariombalhara  i am not sure if size is the issue here because i tried uploading avatar on prod and it worked fine and it returned a success response but when i tried uploading the same image on dev , the request did not return any response.

**Comment by Udit-takkar** [comment]
discussion on similar topic here https://github.com/calcom/cal.com/discussions/5164

**Comment by Udit-takkar** [comment]
now i think the avatar picture loading problem is fixed somehow. just tried creating new account and it seem to work fine.

<img width="227" alt="Screenshot 2022-10-30 at 12 40 00 AM" src="https://user-images.githubusercontent.com/53316345/198848794-fe94fd6e-67a7-44b6-bc57-7fc171fc2a92.png">

**Comment by milospuac** [comment]
Customers keep reporting this one today @udit

**Comment by Udit-takkar** [comment]
yeah no idea what's the issue here.

**Comment by PeerRich** [comment]
@leog @alannnc @hariombalhara  can you look and help?

**Comment by hariombalhara** [comment]
Opened a PR to fix it. Found the root cause for the issue. 
https://github.com/calcom/cal.com/pull/5299/files

**Comment by PeerRich** [comment]
@milospuac can you ask them to try again?
