### ISSUE TITLE
[CAL-293] remove dropdown from booking page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5301]
[https://www.loom.com/share/58fcf7916e034867942352fd1bf5e266](https://www.loom.com/share/58fcf7916e034867942352fd1bf5e266)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by Toledodev** [comment]
Hey @PeerRich, can I do this?

**Comment by PeerRich** [comment]
@Toledodev of course go for it! make sure to keep the design similar :)

**Comment by Toledodev** [comment]
Hey @PeerRich, I'm thinking about some topics:
1. I think it would be better to show the timezone in dropdwon (like "America/Sao_Paulo") instead of the whole label
2.We could reduce the font to make the options less "tight"

[Loom Video](https://www.loom.com/share/2029fea074bd47deb25407254e07add7)

If you have any more ideas I'll be happy to do it 👍

**Comment by PeerRich** [comment]
couple things: 
- the dropdown has to be bigger, its too narrow
- the select input (the trigger) has to look like the previous one, no border, etc.

**Comment by PeerRich** [comment]
really excited about this

**Comment by gitstart-calcom** [comment]
Duplicate of #5762?

**Comment by PeerRich** [comment]
yes
