### ISSUE TITLE
[CAL-317] Confirmation Email - Footer text isn't properly formatted.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5368]
![Screenshot 2022-11-04 at 3.42.20 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/51096f92-0940-442c-9714-7f0e080eb0eb/2002c76f-83e0-4a67-b6a3-c066d29d58a3)

Footer text isn't properly formatted.

> From [SyncLinear.com](https://synclinear.com)

**Comment by CarinaWolli** [comment]
Looks fine for me 🤔
<img width="420" alt="Screenshot 2022-11-04 at 11 54 04" src="https://user-images.githubusercontent.com/30310907/199956183-9e05026e-c630-4298-bb2c-a01d63202b5b.png">

**Comment by hariombalhara** [comment]
Forwarded you an email where it's wrong. Maybe you can compare the two?

**Comment by MuriloAmarals** [comment]
@hariombalhara @CarinaWolli I don't understand why you're seeing it like this, because I made the update of these buttons in the email, and I put space just for that.

![image](https://user-images.githubusercontent.com/87545137/199957780-37a3116e-88d0-487c-ade2-14e24df4be56.png)

This bug didn't show up to me.

**Comment by CarinaWolli** [comment]
Just checked, for me it's only shown correctly in the Mail app (Mac), but in Gmail or other Email Providers it looks like @hariombalhara has reported it
