### ISSUE TITLE
No padding on settings page

### ISSUE THREAD

**Issue by melissamarvin** [calcom/cal.com#5383]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

What it says on the tin.  The icons on the settings page have no padding on the left side.

### Steps to Reproduce

1. go to cal and login
2. Click on settings
3. refresh if bug 5382 is still unfixed

Notice the padding on the left side is missing.  The icons have no space between the edge and the icon.  
![2022-11-04_15-07-14](https://user-images.githubusercontent.com/117048096/200065310-cb966428-cdb8-4c92-b806-19892724455a.png)

### Technical details

Self hosted, main

**Comment by MuriloAmarals** [comment]
hey @melissamarvin Look what I got

![image](https://user-images.githubusercontent.com/87545137/200073135-c7242ff4-80cc-44d2-a918-6ea2aa7f3940.png)

**Comment by PeerRich** [comment]
looks good on my end

**Comment by emrysal** [comment]
@PeerRich this could be a windows only issue - worth investigating. @alishaz-polymath could you check whether the padding gets lost on windows?

**Comment by alishaz-polymath** [comment]
@emrysal Yep, I'll investigate 👍

**Comment by alishaz-polymath** [comment]
Upon further testing, it appears to be related to browser. I tested on Mozilla Firefox, Brave, and MS Edge on Windows and of them, Firefox doesn't have this issue but Brave and MS Edge pushes the content to make space for the scrollbar. I will test out a potential solution where the scrollbar floats on top instead of pushing the content.
