### ISSUE TITLE
[CAL-322] When rescheduling or scheduling the latest time during blocks we get the message that no available users have been found. 

### ISSUE THREAD

**Issue by melissamarvin** [calcom/cal.com#5384]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

If you select the last slot available to schedule with you get a message that no available users have been found.

### Steps to Reproduce

Pre condition:  setup a booking

1. login to cal
2. Click on bookings
3. click edit on the booking from the pre condition
4. click reschedule

[https://user-images.githubusercontent.com/117048096/200066697-a7f87129-8b93-4f1f-bd41-2d9f376c90bc.mp4](https://user-images.githubusercontent.com/117048096/200066697-a7f87129-8b93-4f1f-bd41-2d9f376c90bc.mp4)

1. select any day for rescheduling
2. click the last available slot
3. click reschedule

Notice you get you get a message that no available users have been found.

### Technical details

Self hosted, main.

> From [SyncLinear.com](https://synclinear.com)

**Comment by AaronPresley** [comment]
@melissamarvin could you confirm that this bug is still an issue for you? I've followed the steps you've described and can't recreate the problem. I'll outline my specific steps below so you can tell me what I'm missing:

- Created a new booking event (ex: Feb 6 @ 8am)
- Went to Bookings > Found newly created event > Edit > Reschedule booking
- Rescheduled to the last available time slot (Feb 6 @ 4:45pm in my case)
- The meeting was successfully rescheduled

Could you confirm whether you're still seeing the issue, or that I'm misunderstanding the steps to recreate the bug? Thanks! 🙏

**Comment by hariombalhara** [comment]
@emrysal @PeerRich I think we should close this issue. Pretty old and there have been so many fixes regarding this.
