### ISSUE TITLE
[CAL-374] Custom Payload for Webhooks not working

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#5527]
Custom payload for webhooks seems to have stopped working now, and it isn't even automatically placing the custom template for Discord URL (which it used to in V1)

> From [SyncLinear.com](https://synclinear.com) | [CAL-374](https://linear.app/calcom/issue/CAL-374/custom-payload-for-webhooks-not-working)

**Comment by joelgaribaygz** [comment]
Hello, I have my account configured with Google Meet, but when I receive the webhook, the link generated for the meeting does not arrive.

I would need to query the event ID via API in order to get the Google Meet url, however the webhook shows me the UID not the event ID.

How can I get the Google Meet URL from the webhook?

**Comment by alishaz-polymath** [comment]
Hi @joelgaribaygz 
It should contain the meeting url in the metadata part of the webhook. It was added a few weeks ago in #5773 by @CarinaWolli 
🙏

**Comment by joeauyeung** [comment]
@alishaz-polymath are we able to close this issue? I just tested the webhook and it's behaving as expected.

**Comment by alishaz-polymath** [comment]
Yeah @joeauyeung 
This should be resolved 🙏
