### ISSUE TITLE
[CAL-386] Control the order of fields on an event type

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5564]
VP of Marketing from Daily asked for the ability to control the order of fields on an event type. Especially if they add additional fields such as "company name."

> From [SyncLinear.com](https://synclinear.com) | [CAL-386](https://linear.app/calcom/issue/CAL-386/control-the-order-of-fields-on-an-event-type)

**Comment by aasargsian** [comment]
@shirazdole @PeerRich we have actually noticed a need for this feature too while testing Cal.Com

**Comment by Jaibles** [comment]
@shirazdole @PeerRich @aasargsian designs ready for review here:
https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1807%3A120640&t=Aiw1Icg3cGdHMn8X-1

**Comment by Jaibles** [comment]
This task is being worked on now. Will be released in the next milestone on the 15th of February.

**Comment by aasargsian** [comment]
The design look great, very excited about upcoming release! 

A few ideas from our team that you might like:
- It would be ideal to be able to give questions some internal names that we can use to handle the bookings via API. Otherwise, whenever we change the wording of any question - the API handler has to be updated.

- First name and Last name inputs ideally should be displayed in the same line as 1/2 width. Screenshot from Calendly:
<img width="1078" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/33749906/214865257-621273c8-5a1f-4581-ae5e-a999804c4850.png">

**Comment by Jaibles** [comment]
Designs:
https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1807%3A120640&t=GImgQNbOBI5jZ3DY-1

**Comment by hariombalhara** [comment]
" It would be ideal to be able to give questions some internal names that we can use to handle the bookings via API. Otherwise, whenever we change the wording of any question - the API handler has to be updated."
This has already been taken care of in the PR. Thanks for sharing and good to see that we are going in the right direction 🙏
