### ISSUE TITLE
[CAL-441] i18n: translate attendee phone number and other video options if possible

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5666]
Hello

I am a new user - very interesting application! I like it very much
I changed the language (-> French) and some pieces of text are not translated. Surely you knew that? In doubt I put you some screenshots.

> From [SyncLinear.com](https://synclinear.com) | [CAL-441](https://linear.app/calcom/issue/CAL-441/i18n-translate-attendee-phone-number-and-other-video-options-if)

**Comment by RainerZufall9393** [comment]
I have the same problem. My language is set to German, but the English term "Attendee Phone Number" is displayed on the booking pages instead of a German term. Can you please fix this?

<img width="729" alt="Screenshot" src="https://user-images.githubusercontent.com/126205884/221038497-3e3081e0-269b-4fde-a01a-0783b105d780.png">

**Comment by PeerRich** [comment]
yep, thats planned. lemme tag @G3root
