### ISSUE TITLE
[CAL-450] Create Webhooks at an Org. level, not just per event type

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#5684]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-450](https://linear.app/calcom/issue/CAL-450/create-webhooks-at-an-org-level-not-just-per-event-type)</sub>

**Comment by harshsinghatz** [comment]
@alannnc More info about this issue?

**Comment by alannnc** [comment]
@harshsinghatz Linear wrongly synced the issue with my user I think the autor for that it's @shirazdole.

**Comment by harshsinghatz** [comment]
Ok, @shirazdole can you give more info about this issue?

**Comment by shirazdole** [comment]
@harshsinghatz — working to get more context from the customer that requested this :)

**Comment by harshsinghatz** [comment]
@shirazdole Ok got it

**Comment by shirazdole** [comment]
Currently, customers on teams have to setup webhooks per user which is not scalable. Calendly has the ability to setup one webhook for the entire account including all teams and users.

cc @Jaibles @CarinaWolli

**Comment by PeerRich** [comment]
yep, planned!

**Comment by Jaibles** [comment]
Medium term plan: have webooks at a org/team level. 
Short term fix: allow the ability to add a webhook to an event type (as proposed by @CarinaWolli). Thoughts @PeerRich?

**Comment by CarinaWolli** [comment]
@Jaibles Are there designs for team webhooks?

**Comment by shirazdole** [comment]
@CarinaWolli this is live?

**Comment by CarinaWolli** [comment]
Team webhooks are in main so will go live with the next release. You can then create webhooks for teams in `settings/developer/webhooks`
<img width="748" alt="Screenshot 2023-05-24 at 14 23 47" src="https://github.com/calcom/cal.com/assets/30310907/eb85c0f9-830e-40ff-bd06-f543377555cc">


Now I am wondering. @shirazdole What was the initial request of the customer? Do they want the webhook to trigger for all the user event types of their members as well? 
Because currently if you create a wehook for a team it will only trigger for the team event types

Webhooks for managed event types are also planned
