### ISSUE TITLE
Rescheduling page refers to "Your name" regardless of who is viewing

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#572]
## How to reproduce

- Send a test invite to myself (using a separate address for the invitee)
- Acting as the host / calendar owner (not the invitee), go to the new event automatically created in my Google calendar
- Click the reschedule link

It takes me to a page where the "Your name" field refers to the invitee, not the host, and the "Email address" field does too.

## Expected results

The name field would be labelled "Invitee's name", and the address field as "Invitee's email address", or similar.

**Comment by ConnorGargano** [comment]
Hi, @aspiers I will reopen this issue as I have misunderstood this for something else. Sorry about this. An update will be given accordingly.

**Comment by aspiers** [comment]
No worries, thanks ;-)

**Comment by baileypumfleet** [comment]
This is intended functionality, although I completely see your point here. Rescheduling is intended for the invitee mainly, that's why their details are shown. We might look into changing this in the future, but this will be super low priority.

Thanks for reporting this though, it's an interesting point

**Comment by Jaibles** [comment]
We have done a lot of work around how rescheduling works that should resolve this.
