### ISSUE TITLE
yarn dx uses old "docker-compose" instead of current "docker compose"

### ISSUE THREAD

**Issue by minnixtx** [calcom/cal.com#5819]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When creating the initial database user using yarn dx, you will get an error about docker-compose. This is because current docker uses the syntax docker "space" compose, no hyphen.

### Steps to Reproduce

At https://github.com/calcom/cal.com#quick-start-with-yarn-dx is where the instructions are located.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

This is on a vanilla Debian server with newest version of docker installed. It is a syntax issue though, not a hardware issue.

**Comment by PeerRich** [comment]
@zomars i think i had a similar issue

**Comment by PeerRich** [comment]
is there any downside in docker-compose"?

**Comment by renancleyson-dev** [comment]
@PeerRich, I think this should be reopened.

> is there any downside in docker-compose"?

I think so. `docker-compose`(V1) is deprecated in favor of  `docker compose`(V2-VX). From [docker's blog](https://www.docker.com/blog/announcing-compose-v2-general-availability/)
>We’ve now marked Compose V1 as deprecated. Only high-priority security patches and critical bug fixes will apply to V1 until the next milestone.

I'm very interested in the project, but I had this issue when setup locally, so I would love to create a PR to fix it.

**Comment by krumware** [comment]
`docker-compose` and `docker compose` are now two different binaries, and the old `docker-compose` can still be installed separately. But `docker compose` (with the space) is the way to move forward, and probably works out-of-the-box here.

NOTE:
 (does not affect this particular method of running, because `yarn dx` is a convenience for running a local database in this case)
Because we require database access at build time, and the newer version of docker compose uses buildkit, which changes features related to build-time networking, building the front-end with `docker compose` recommends  the `DOCKER_BUILDKIT=0` env variable in order to use the legacy builder.
