### ISSUE TITLE
[CAL-525] Installed Apps / Outlook Calendar - Connected calendar not showing email address

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5836]
Currently shows:

![CleanShot 2022-12-02 at 13.00.53@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e80b792d-adfa-4048-9b43-392d78ec9a4b/7ae2db0d-9cfc-4c71-8009-2bef598afe5f)

Should show the email address?

Related

![CleanShot 2022-12-02 at 13.02.12@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d71fdd82-3826-4b31-ab2a-2f8de0e756b9/b594422d-9975-4fc9-9c36-222ee8dbfc9a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-525](https://linear.app/calcom/issue/CAL-525/installed-apps-outlook-calendar-connected-calendar-not-showing-email)</sub>

**Comment by mocherfaoui** [comment]
@Jaibles I was looking at this issue and noticed that Google uses email as calendar Id while Outlook uses a random string for that, but in Outlook the email can be found in the [`owner`](https://learn.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=javascript#response-1) object.

The connected calendars list uses an `externalId` as a description. This Id should stay unique since it's used elsewhere too. What I thought of as a solution is to add a new key `description` to the calendar response, this means that all calendars response should include this `description` key. I don't know if this is the right approach.
