### ISSUE TITLE
[CAL-592] Override check for conflicts calendars on a per-event basis

### ISSUE THREAD

**Issue by brianclements** [calcom/cal.com#5887]
### Is your proposal related to a problem?

While I can specify and override specific google calendars to add events to on a per-event basis, I cannot do the same with conflict checking.

#### Use case/Context

I'm creating a cal.com/MusicStudioName account to allow for teachers to reserve rooms (1-7). Right now, there is one user (MusicStudioName) and the events are created for each of the rooms. This looks like:

- cal.com/MusicStudioName/room1
- cal.com/MusicStudioName/room2
- cal.com/MusicStudioName/room3
- etc.

I have google calendar doing the calendar backend. On Google calendar, I have a calendar for each room.

For each event, I am able to specify which calendar to add events to. This is perfect. I select that rooms calendar for that event.

But for conflict checking, my only option is for calc to check ALL the calendars for every event. This doesn't work in my use-case because if room 1 is 100% booked, but room 2 is 100% empty, then the availability for room 2 will still show as 100% full because I cannot specify per-event where conflicts get checked.

### Describe the solution you'd like

Rather than check every calendar for conflicts, I would like to be able to specify which calendars to check for conflicts for. Usually, I would imagine this is always the calendar that I am adding the events to.

This option can be in the Advanced section of the events page underneath the "Add to calendar" section and above the "Event Name"; i.e. "Select which calendar to check for conflicts"

### Describe alternatives you've considered

The only way to get this functionality would be to host my own instance and then be able to make each room a "user". So I'd have to do:

- book.mydomain.com/room1
- book.mydomain.com/room2
- book.mydomain.com/room3

Just so that in the User Settings/My Account, I can only specify one calendar at a time in which to check for conflicts.

<sub>[CAL-592](https://linear.app/calcom/issue/CAL-592/override-check-for-conflicts-calendars-on-a-per-event-basis)</sub>

**Comment by shirazdole** [comment]
Cc @Jaibles I spoke with @brianclements, and when you have multiple event types, if you choose a different calendar to add the booking to, you cannot change which calendar the booking checks conflict for. The calendar you set in your settings is the default calendar for ALL event types to be checked against.

At some point, we will need to fix this to give users the ability not just to adjust where the booking gets added to but also to pick which calendar to check conflicts against. This hasn't been mentioned as much, but as we work towards scheduling infrastructure for all, this problem will come up quite a bit at some point.

My suggestion to Brian is to create seven individual accounts for each event type so that each event type will have an independent calendar to check conflicts against and add bookings to. Then, once those event types are created using Google Docs or Notion as the "profile page" for folks to check to make bookings. Not ideal, but a solution in the meantime.

**Comment by shirazdole** [comment]
cc @PeerRich does this mean this was completed? Or canceled?
