### ISSUE TITLE
[CAL-589] Investigate Email Confirmation

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6009]
Hey Cal team, there seems to be an issue/bug with the email confirmation I or the person booking is getting. Can anyone help me ?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-589](https://linear.app/calcom/issue/CAL-589/investigate-email-confirmation)</sub>

**Comment by CarinaWolli** [comment]
@joeauyeung Should the custom event name be shown in the email booking confirmation? Or is it correct to show the default one under the 'What'? Because the booking/\[uid\] shows the custom event name

![Screenshot 2022-12-23 at 09.28.50.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ccef4430-d7af-4607-bb14-da3566938ac7/bfc60b39-d1c5-467c-8a28-0796a64ddd05)

**Comment by joeauyeung** [comment]
@CarinaWolli good point. I think it should show the custom event name in the email as well.
