### ISSUE TITLE
[CAL-688] UI bug below filters

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#6285]
### Issue Summary

<img width="1212" alt="Screenshot 2023-01-05 at 5 54 12 PM" src="https://user-images.githubusercontent.com/53316345/210779567-285d2742-216a-4da0-aef7-db8ffe992806.png">

go to /booking pages ( /bookings/upcoming ) 

Browser: Brave [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64)](https://brave.com/latest/) 

<sub>[CAL-688](https://linear.app/calcom/issue/CAL-688/ui-bug-below-filters)</sub>

**Comment by sean-brydon** [comment]
I can't replicate this... Weird

**Comment by phishy** [comment]
I've seen this before

**Comment by phishy** [comment]
Also using Brave. 

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/26844/210841596-47bc418d-6e42-4ce0-82e3-5fff9b504b47.png">

**Comment by gane11** [comment]
I was just randomly scrolling through this pr but this might help here.
- You should almost always use overflow-auto instead of overflow-scroll. explanation here:

![Screen Shot 2023-01-05 at 1 12 16 PM](https://user-images.githubusercontent.com/65471943/210881295-f93ecbe8-50ab-47ff-876c-be1893e6a828.png)
