### ISSUE TITLE
Apple Calendar deleting event's not working

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6401]
### Issue Summary

With a connected Apple Calendar, add a booking through the platform, then in the Apple Calendar app, delete the event.

Nothing happens in the booking system, no removal, emails or anything

### Steps to Reproduce

1. Connect Apple Calendar
2. Book a new event
3. Delete the event in the Apple Calendar app (tested on iPhone)

This should remove the event and send out the relevant mail.

### Technical details

- No technical details overly required here, but here's all the versions im using:
- iOS 16.2
- Chrome 1.46.153
- Node 16 running the server

**Comment by zomars** [comment]
This is intended by design. As we don't have an optimal way to "listen" for Apple Calendar whenever you remove events from that side. So the recommended approach is to cancel bookings from Cal.com in order to keep the data flow in sync. 

Feel free to reopen if you have more questions or if this should be stated in our docs.

**Comment by Hybes** [comment]
Yeah I think this should be made clear, or there should be a better method than 'WipeMyCal' to bulk remove a day, or a expect few bookings without reason. For example. I may book a holiday in 3 week time, but have 20 bookings planned, clicking each one and cancelling is tedious
