### ISSUE TITLE
[CAL-785] Repeating events in calendar not blocking out time.

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6465]
### Issue Summary

If someone is to add an event that repeats say 'Every Tuesday between 4pm and 7pm' on their calendar (Apple calendar tested)
The booking system wont see that this is an event, potentially due to the fact its in a a repeating event.
Allowing people to therefore book in to these time slots.

My example is, someone is trying to block out lunch every day - 12 til 2 every monday, 12:30 til 2 tues-thurs and 1-2 on fridays. they have this as a repeating event, so they dont need to add it in each day. But someone was able to book in on those times earlier today.

### Technical details

- Latest Chrome
- Node.js 16
- Apple Calendar on iOS

<sub>[CAL-785](https://linear.app/calcom/issue/CAL-785/repeating-events-in-calendar-not-blocking-out-time)</sub>

**Comment by PeerRich** [comment]
I dont think there is a good solution for this. This is one of the downsides of recurring events. Unless you know of a solution, we'll have to close this

**Comment by Hybes** [comment]
Oh, shame! Just not possible? I've seen it work with things like Harmonizely/SimplyMeet

**Comment by PeerRich** [comment]
Harmonizely/SimplyMeet have recurring events?!

**Comment by Hybes** [comment]
They support users that have repeating events, as I have someone who's using them at the moment and has lunch pencilled in each day 12:45-1:30 - for now I'll just get them to use the availability and set 2 sets of availability per day to avoid lunch.
But I guess that means it must be possible.

**Comment by Hybes** [comment]
is this stale, or did you choose to keep this open?

**Comment by PeerRich** [comment]
we're currently investigating this!

**Comment by Hybes** [comment]
How's this going?

**Comment by alexsereno** [comment]
This issue is pretty breaking, are we sure there's not a way to check free busy times for recurring events?

[Calendly has this feature 
](https://help.calendly.com/hc/en-us/articles/4403218915607#moving-a-repeating-event-on-icloud-calendar-0-0)

As did my old FAANG's internal meetings tool, its really needed since a lot of meetings repeat on a pretty regular basis, not just lunch haha.

I _think_  this should be solvable since iCal uses rfc4791 & GCal's [freebusy](https://developers.google.com/calendar/api/v3/reference/freebusy/query) also returns busy for recurring blocks but I'm def not a calendar expert at all

**Comment by emrysal** [comment]
At the moment we don't have the infrastructure to be able to support this yet. We are working on improving our infrastructure to do this but at the moment I can't give an ETA until fix. Note that this is only slot rendering; recurring does have a legitimate concern of being very un-user friendly but there is a lot we need to do before we can fix this issue.

**Comment by hariombalhara** [comment]
It feels like I am really missing something here, but to get clarity and sharing what I understand here is a loom
https://www.loom.com/share/9a9239721c1b4d83a59f897be5125863

I created a Lunch event 12-12:30 everyday in Apple Calendar and that blocked the slot for many many months that I tested.

**Comment by Hybes** [comment]
Hi @hariombalhara i've just tested and still see the issue, I've blocked off 10-12 every day and it's showing in my bookings page:
See images here: 
<img width="1017" alt="image" src="https://github.com/calcom/cal.com/assets/53020786/b3138ac3-cb70-43ef-9d99-47113148d598">
<img width="1053" alt="image" src="https://github.com/calcom/cal.com/assets/53020786/7dd32b5a-7423-4a1f-bbeb-e37607e27069">
<img width="1721" alt="image" src="https://github.com/calcom/cal.com/assets/53020786/543a44db-326f-43f5-a3e9-b84221cf55e5">

**Comment by hariombalhara** [comment]
This is so weird @Hybes. Did you find anything wrong with [what I tested in loom](https://www.loom.com/share/9a9239721c1b4d83a59f897be5125863) because I couldn't replicate it there.

Could you share a recording with a completely new setup showing this bug because I am having a hard time replicating this issue(and even understanding how it can happen).

cc @joeauyeung as you are more experience

**Comment by ciaranha** [comment]
Closing for now as it seems to be resolved. Will re-open if we can recreate.
