### ISSUE TITLE
[CAL-978] Klaviyo App

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#6830]
Request for a customer for an integration with [Klaviyo](https://www.klaviyo.com/).

The use case is within the e-commerce space and it would allow them to track booking page abandonment. They want to track people who started to make a booking but didn't complete it.

<sub>[CAL-978](https://linear.app/calcom/issue/CAL-978/klaviyo-app)</sub>

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app

**Comment by orimdominic** [comment]
Hello @PeerRich I would like to work on this even though I'm new here. I'll like more information about this to get it done. To be more specific, for now
1. Aside from the build-an-app link that you shared, where can I find information about building integrations on cal.com? I searched in the search bar of https://cal.com/docs/ for "integration" but I did not find any result. If there is a sample somewhere, I'd like to be directed to it.
2. What property should be used to track the users who abandoned booking? `userId`? `email`?
3. How should this be tracked? Are we storing the data in a database table or does Klavio have an API we can send it to?

Thanks.

**Comment by rjackson** [comment]
I've been looking into this. There's a few wider architectural changes we'll have to make for an integration with Klaviyo – expanding apps' tracking tag capabilities, and the integration won't exactly suit the use-case as described because we won't have contact details for somebody until after they've made a booking.

Nonetheless, I think there's probably value in some level of tracking with Klaviyo. Not quite for the described use-case, but potentially others.

I've got some rough work in progress so far, and I'll aim to raise a draft tomorrow or over the weekend.
