### ISSUE TITLE
[CAL-1015] Booking date is always in english (booking/[uid])

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#6951]
### Issue Summary

On the booking/[uid] page the date is always shown in English. The email confirmation shows the date of the booking in the correct language. 

Date should be in german here: 
<img width="575" alt="Screenshot 2023-02-08 at 10 27 49" src="https://user-images.githubusercontent.com/30310907/217600018-fbab96d5-eefe-4fe9-bf74-4e584213eb87.png">

<sub>[CAL-1015](https://linear.app/calcom/issue/CAL-1015/booking-date-is-always-in-english-booking[uid])</sub>

**Comment by AaronPresley** [comment]
@PeerRich @CarinaWolli I've looked into this one, and it's a pretty simple fix from a _technical_ perspective, but there are definitely some pros / cons to weigh from the business / design side.

Firstly, it seems DayJS does support i18n ([source](https://day.js.org/docs/en/i18n/loading-into-browser)), however it requires the user's specific locale to be loaded. This would add some additional logic + data to be written each time the user changes their locale.

IMO this would also be overkill, because DayJS is likely simply loading [CLDR data](https://cldr.unicode.org/) which is accessible natively within the browser by default. In this case that would be through the `Intl.DateTimeFormat` object which is supported by all major browsers ([docs here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat#browser_compatibility)).

The good news is that this means dates can be easily localized and translated into any locale supported by Unicode. The **bad** news is that you would lose a bit of control over how dates are formatted. Because correct date display varies so widely by any combination of language + region, proper localization means relying on Unicode's `Intl.DateTimeFormat` to control how and in what order months, dates, times, timezones are generated.

That's not to say we have NO control. You can review the [Examples section of the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#examples) to see what type of control they provide.

That brings us to a slight complication: **duration**. Currently `Intl.DateTimeFormat` only outputs a single date, and not a date _range_. `Intl.DateTimeFormat` does have a function called `formatRange` that allows for this, but browser support is much lower ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange#specifications)), and I would rely on the Cal.com team to decide whether that's an appropriate risk to take.

If `formatRange()` doesn't have enough support, I would suggest the UI to be slightly tweaked.

**Currently** this page has:
```
When:       $date
            $timeStart - $timeEnd ($timezone)
```
But I would suggest something more along the lines of:
```
When:       $date
Start Time: $timeStart ($timezone)
End Time:   $timeStart ($timezone)
```
Splitting up each piece of data with a clear label would get closer to guarantee proper localization for every possible locale. Generally, relying on Javascript's built-in locale API's are _strongly_ recommended, as the main browsers work directly with Unicode on these specifications and keeping them updated. This isn't necessarily true of third-party libraries.

Happy to work on this bug once the above decisions are made ☝️ Let me know if you'd like to discuss in further detail. 

[cal.com/aaronpresley](https://cal.com/aaronpresley)

**Comment by CarinaWolli** [comment]
Hi @AaronPresley, thank you for taking a look at that 🙏

I am wondering, if we could format the `date` with Intl and leave the `timeStart` and `timeEnd` as it is (not sure how much difference there is between languages when it comes to showing the time in `HH:MM` format 🤔)? In general, I would prefer a solution that does not change anything in our current design

**Comment by AaronPresley** [comment]
@CarinaWolli that's certainly possible! Though since you can't use `formatRange()` I think the best approach would be to call `Intl.DateTimeFormat` for each of the individual piece of text (day month year + start time + end time + timezone).

I've thrown together [this example on Codepen](https://codepen.io/AaronPresley/pen/vYawbZR?editors=1011) to demonstrate what I mean. This gets you _close_ to the current output, but would be fully localized and translated as well.

Worth calling out that not all locales necessarily follow the pattern of `$startTime - $endTime` when displaying a range of time. However I agree that this seems like the best compromise until `formatRange()` gains more adoption.

**Comment by AaronPresley** [comment]
@CarinaWolli let me know if you'd like me to start on this fix. Not sure if you were planning to work on it?

**Comment by CarinaWolli** [comment]
@AaronPresley I like that, looks good 👍 You can work on that ticket, I'll assigned you :)
