### ISSUE TITLE
[CAL-1069] Remove branding in reminder email if Cal.com branding is disabled

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7115]
### Issue Summary

Remove 'Scheduling by Cal.com' in the reminder workflow template if Cal.com branding is disabled. 

Context: 
https://github.com/calcom/cal.com/pull/6463#issuecomment-1430496778

<sub>[CAL-1069](https://linear.app/calcom/issue/CAL-1069/remove-branding-in-reminder-email-if-calcom-branding-is-disabled)</sub>

**Comment by shivamklr** [comment]
@CarinaWolli While working on this issue, I had a few questions

- This looks like an ee only feature. How to enable the workflow page while debugging? (I see that we need a license to even use the page.)
- What all do I need to set up the test in the workflow? In the PR #6463, I saw that you got the email on your personal email address as part of the test. In order to debug and to see if my fix actually worked, I might need to test it similarly.
