### ISSUE TITLE
[CAL-1088] RFC: Create Organisations layer above teams

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7142]
We want to create organisations within [Cal.com](http://Cal.com) to enable people to easily and effectively manage multiple teams. An organisation will live above the current teams layer.

**An organisation will have**

* **People:** These people will be added as members to any number of teams within the organisation.
* **Teams:** will operate very much in the same way as they do now, except that certain things will be able to be shared across teams.
* it's own org-name that will compete with usernames: [cal.com/acme](http://cal.com/acme) = company, \[[cal.com/acme/anna](http://cal.com/acme/anna)\]
* when joining an org, you get a new org-username ([cal.com/peer](http://cal.com/peer) and [cal.com/cal/peer](http://cal.com/cal/peer) could be different people)
* subteams will compete with org-usernames for namespace:
  * [cal.com/acme/marketing](http://cal.com/acme/marketing) = marketing team
  * ([http://cal.com/acme/anna](http://cal.com/acme/anna)) = CEO of acme
  * [cal.com/acme/anna/30min](http://cal.com/acme/anna/30min) = 30 min with CEO anna
* org-usernames dont require premium and only compete with other names in the org

**Roles within an org**

* Owner (can edit all org & team settings)
* Admin (can edit all org & team settings)
* Analyst (see everything, read only)
* Team Admin (edit all settings team level)
* Member (view only within their team, can’t edit)

**Open questions**

* What else can be shared across teams via the organisation? ie workflows? apps? routing forms? etc.
* Does an org need it's own event types? Assumption for now is no.
* Can a member see all teams within an org?
* Can a member see all people within an org or just the people in the shared teams.

**(out of date) WIP chart - subdomain is now subpath**

![CleanShot 2023-02-16 at 11.27.41@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c6f21ef9-00aa-473c-a2f3-f3f72ac685ea/de38f252-132e-4ba6-9e0a-a1858c518ddf)

**Current state of designs**

[Organisations - Cal.com Teams (Figma)](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Cal.com-Teams?node-id=217%3A53765&t=nxZiKwVYEAFvYa2Q-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1088](https://linear.app/calcom/issue/CAL-1088/rfc-create-organisations-layer-above-teams)</sub>

**Comment by PeerRich** [comment]
We also wanna make sure that we can have unique usernames per organisation.

cal.com/peer should be a different person than acme.cal.com/peer 

which means every org member has an org-wide username that is unique

**Comment by PeerRich** [comment]
quick update:

for SaaS users, we will go with subpaths, not subdomains, because subdomains will cause a lot of issues with external apps and their verification.

which means:

acme.cal.com/marketing will be
cal.com/acme/marketing

which means organisations will compete with usernames when it comes to namespace (same as twitter.com/peerrich competes with twitter.com/calcom)

**Comment by zomars** [comment]
> quick update:
> 
> 
> 
> for SaaS users, we will go with subpaths, not subdomains, because subdomains will cause a lot of issues with external apps and their verification.
> 
> 
> 
> which means:
> 
> 
> 
> acme.cal.com/marketing will be
> 
> cal.com/acme/marketing
> 
> 
> 
> which means organisations will compete with usernames when it comes to namespace (same as twitter.com/peerrich competes with twitter.com/calcom)

Would a local namespace work?

`cal.com/o/acme/marketing`

This would help with testing separate profiles and we could use rewrites as well.

**Comment by PeerRich** [comment]
temporarily or indefinitely have /o/ ?

**Comment by PeerRich** [comment]
ideally we do the same as github where github.com/PeerRich is a user but github.com/calcom is an org

**Comment by PeerRich** [comment]
if possible, of course

**Comment by zomars** [comment]
Yeah makes sense to be on top level, although that could be resolved via rewrite. That would also allow us to separate logic to identify if it's a user or an organization via middleware maybe?

**Comment by PeerRich** [comment]
i dont mind either way as long as thats how the URLs will look like

**Comment by leog** [comment]
> for SaaS users, we will go with subpaths, not subdomains, because subdomains will cause a lot of issues with external apps and their verification.

@PeerRich @zomars I think we should be fine as the app will still be working under app.cal.com which is what all apps have as redirect URL when installed

the orgs under a subdomain will continue to serve the same app, just mapped differently to have the user understand the UI's context is the organization

when the user installs Zoom, they can choose to install it for an organization, the redirect URL will still be the same, maybe with an extra parameter, and nothing to worry about extra efforts regarding app verification processes

**Comment by zomars** [comment]
Some new Qs:

- How can we enforce uniqueness between usernames and orgnames at the DB level (since they're different tabled)
- If we can't, how can we prevent an org to takeover an username slug?
- How can we prevent a user, taking over an org slug?

Some possible ideas:

- Find a way to [force uniqueness between different tables](https://dba.stackexchange.com/questions/95817/unique-across-tables).
- Create a "Usernames/Slugs" model, migrate all usernames there, create a relationship back to `User` and `Team/Org` use the new table as single source of truth for uniqueness.
- Keep validations on the code side: When creating a new user, check for both users and teams slugs and error if found one already. When create a team, doing the same. This opens up the possibility for unexpected conflicts. Let's say a team created via API that we forgot to add validations to.

**Comment by leog** [comment]
@zomars very good questions and possibilities.

My idea was around linking a user with a team using an teamId in the User table, to be able to define the following constraints:
 - `@@unique([email])`: To have user with unique emails, already existed
 - `@@unique([email, username])`: To have user with unique usernames, without a linked organization
 - `@@unique([username, teamId])`: To have unique organization/username pairs

This will also allow letting people sign-up from an organization subdomain to be associated with that organization once the admin accepts it, which offloads a bit the whole invitation flows.

This is what the mentioned alternative looks like from the DB, run a POC for it:
<kbd><img src="https://user-images.githubusercontent.com/467258/231888667-ee9cc742-c3b4-46f4-a2c9-fce834f3bea3.png" /></kbd>

**Comment by zomars** [comment]
But this doesn't prevent a team slug being "example" if a user already has the username "example".

**Comment by leog** [comment]
> But this doesn't prevent a team slug being "example" if a user already has the username "example".

@zomars right, that is just to allow scoped usernames within the same table. This is what I imagine would the URL mapping scheme between username and team slugs (org or regular):

| | App | Profile | Booking |
|--------|--------|--------|--------|
| Org | app.cal.com/org-slug | org-slug.cal.com | org-slug.cal.com/team-slug/event-slug |
| Team | app.cal.com | cal.com/team/team-slug | cal.com/team/team-slug/event-slug | 
| Individual | app.cal.com | cal.com/user-slug | cal.com/user-slug/event-slug | 

Now, the way we want to adjust the UI for orgs opens a possibility for teams as well. Why not making the org selector a team selector (regular or org) to be able to scope the app to show team related entities such as event types, apps, insights? Availability section can let the user create shared availabilities throughout a team/org, insights already apply for teams and could apply for orgs as easily.

![image](https://user-images.githubusercontent.com/467258/232607688-196ef840-bf2b-45e2-a1d5-251efec867d9.png)

That new scenario would also mean a slight change in the URL mapping scheme:

| | App | Profile | Booking |
|--------|--------|--------|--------|
| Org | app.cal.com/org-slug | org-slug.cal.com | org-slug.cal.com/team-slug/event-slug |
| Team | **app.cal.com/team/team-slug** | cal.com/team/team-slug | cal.com/team/team-slug/event-slug | 
| Individual | app.cal.com | cal.com/user-slug | cal.com/user-slug/event-slug | 

That way we can scope the UI to be dealing with different entities when it comes to event types, apps, bookings, the works. That would also help declutter the UI from different filters to show individual/teams and orgs bookings, event types, etc all at once in the same view, cc @Jaibles.

**Comment by leog** [comment]
Regarding URL scheme @PeerRich @zomars. Taking into account subdomains are back to the table, as there shouldn't be any problem with apps verifications as I previously mentioned. 

We have what we currently do `for profiles`:
 - **Individual:**
   - **Prod:** https://app.cal.com/peer === https://cal.com/peer
   - **Staging:** https://app.cal.dev/peer === https://cal.dev/peer
   - **Local:** http://localhost:3000/peer
 - **Team:** 
   - **Prod:** https://app.cal.com/team/calcom === https://cal.com/team/calcom
   - **Staging:** https://app.cal.dev/team/calcom === https://cal.dev/team/calcom
   - **Local:** http://localhost:3000/team/calcom

That URL scheme allows having a team with slug `acme` and a user with slug `acme` because the team has a `/team` prefix.

As organizations are teams too, initially, without any change on the URL scheme, they can be accessed using the team URL, so for an org `deel` it can be accessed using `app.cal.com/team/deel`. But we can work on adding logic to the middleware to allow orgs to use a subdomain, like `deel.cal.com` as a shortcut.

The URL scheme for it would be:
 - **Organization:** 
   - **Prod:** https://app.cal.com/team/deel === https://cal.com/team/deel === https://deel.cal.com
   - **Staging:** https://app.cal.dev/team/deel === https://cal.dev/team/deel === https://deel.cal.dev
   - **Local:** http://localhost:3000/team/deel === http://deel.localhost:3000

The outstanding question is, should we allow the user to switch context when it comes to filter assets for individual/team/org using [the selector](https://github.com/calcom/cal.com/issues/7142#issuecomment-1512067607) from the URL? I don't think there is a straightforward way to do it, at least that I can see. Maybe we don't let the user change context by URL, as it can be tagged as a nice-to-have if you ask me.
