### ISSUE TITLE
Unable to add new location to event.

### ISSUE THREAD

**Issue by heyanurag** [calcom/cal.com#7191]
### Issue Summary

Previously I used to see a modal asking me the type of location I want to add ([something like this](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=1739%3A78022&t=FpoXhi0rABWhdMj2-0)) but now I only see the edit location modal with no other option.

### Steps to Reproduce

1. Go to Edit Event
2. Click on Add location

Recording - https://www.loom.com/share/c7a063dc50f042fd9c54df56435243fe

**Comment by PeerRich** [comment]
something is wrong with lazyloading @emrysal @zomars

**Comment by hariombalhara** [comment]
This is fixed now.

**Comment by harshsinghatz** [comment]
@hariombalhara This seem to be caused by a hook added yesterday which gets the mount state and it is referenced in useTheme. 
The RCA for this was that change in ref was not causing re-render due to which even though the ref's current was getting changed, isReady was still holding it's inital value (unchanged) i.e false
