### ISSUE TITLE
Selected Apple calendar is ignored

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#727]
### Issue Summary

Having an Apple Calendar with 3 calendars. Enable only the third one. When a booking is created. It's created on the first calendar. Am I making any sense?

**Comment by SBagaria2710** [comment]
Not really 😅 
Could you maybe elaborate a little?

**Comment by jstrellner** [comment]
In my case, I have a Google Workplace calendar configured (work), and Apple configured (personal, which has a Home, Work, and Family calendar).

It is adding the bookings correctly to my Google calendar, but I don't see any place to change which calendar meetings get booked onto. I would think it'd be set under Event Types, but I see no option... In my case it's not much of an issue, since they're going on the right calendar.

The real reason I'm replying here, though, is that no matter what I do, it doesn't take the Apple calendars into account.  I can add any item to any of the three Apple calendars, and it'll never block that spot. It does block spots when i add an event to my Google calendar, though.

And just to be clear, on my Integrations page, all 3 calendars have been checked under Select Calendars.

**Comment by PeerRich** [comment]
@alishaz-polymath did we fix this?

**Comment by alishaz-polymath** [comment]
@PeerRich yes, this isn't relevant now.
