### ISSUE TITLE
[CAL-1162] dont close "date overwrite" dialog after adding a new one

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7439]
right now:  [https://user-images.githubusercontent.com/8019099/221970061-275bc7de-f512-49c3-a4a6-5013a053b9f4.MOV](https://user-images.githubusercontent.com/8019099/221970061-275bc7de-f512-49c3-a4a6-5013a053b9f4.MOV)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1162](https://linear.app/calcom/issue/CAL-1162/dont-close-date-overwrite-dialog-after-adding-a-new-one)</sub>

**Comment by echo304** [comment]
So basically, should we prevent 'date overwrite' dialog from closing after adding a new one?

**Comment by Jaibles** [comment]
<img width="842" alt="CleanShot 2023-03-02 at 11 44 30@2x" src="https://user-images.githubusercontent.com/4536123/222419514-e9f351f2-c2e2-4184-870d-85d3894283bf.png">

@PeerRich what about an approach like linear? The toggle makes it easy to add one or multiple. Right now it's designed to make it easy to add just one, the approach you're suggesting assumes people want to add multiple. Would this be a better adjustment if you're trying to solve for the problem of wanting to add multiple, rather than making it the default.

**Comment by emrysal** [comment]
I agree with @Jaibles - IMO this shouldn't be the default behaviour. 

Instead:

* Allow selection of multiple dates
* Implement "Create more" toggle.

**Comment by Jaibles** [comment]
Yea imo if we want bulk adding of overrides we should wait and use the weekly view for this.

**Comment by emrysal** [comment]
Agreed, also with selection of multiple dates; tracked by https://github.com/calcom/cal.com/issues/6833; allowing to quickly create more date overrides becomes less needed. Closing this and I recommend we up the prio of multiple date selection.
