### ISSUE TITLE
[CAL-1227] Microsoft Teams not amongst installed apps

### ISSUE THREAD

**Issue by morizmartiner** [calcom/cal.com#7601]
### Issue Summary

Even though I enabled Microsoft Teams as the conferencing software in the admin portal, it does not show up amongst the apps for users nor is it possible to generate a Microsoft Teams calendar Link for events. Beyond this, when I try to enable FaceTime, Around, Campfire and other conferencing software, I get the following error: 

> Invalid `prisma.app.upsert()` invocation: Unique constraint failed on the fields: (`dirName`)

### Steps to Reproduce

1. Enter admin console
2. Enable Microsoft Teams conferencing application
3. Cannot find Microsoft Teams amongst user application

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: Google Chrome 110.0.5481.177
- Node.js version: 16.9

<sub>[CAL-1227](https://linear.app/calcom/issue/CAL-1227/microsoft-teams-not-amongst-installed-apps)</sub>

**Comment by gbdoin** [comment]
Same here. 

Trying to enable FaceTime and others seems to fail because of a unique constraint on `dirName`. Facetime, like msteams, gets added to the App table without any value in dirName, which prevents the user from adding more than one. 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/3705847/232181784-0a15367c-f4d1-4039-aa1a-14f849c2b96d.png">

Adding a value there, like office365video, will:

1. make msteams appear in the app list (but it won't be possible to actually install it to use it)
2. allow adding others like FaceTime

**Comment by gbdoin** [comment]
Seems like simply adding dirname like `office365video` and creating a new app registration in Azure with an updated redirect url (to use `office365video` instead of `office365calendar`) works. So just follow [this guide](https://cal.com/docs/introduction/quick-start/self-hosting/install-apps/microsoft) with only this change.

Then add the client id and client secret to the keys property of the msteams record in the App table.
