### ISSUE TITLE
[CAL-1265] Rescheduled events are not updated on calendars

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#7728]
While researching and fixing #7435, I noticed that the events were not updated after the event was rescheduled. Upon further investigation, it's because the `references` object is updated on the new `booking` after the call to `updateAllCalendarEvents` is made, which was expecting the new booking model to have that data on it.

Possibly related to #2434.

### Steps to Reproduce

1. Schedule a new event (event is put onto destination calendar)
2. Reschedule the event (TBD exactly which case is causing this. There are 4 places where event calendars are updated but this only happens in 1 case) 

### Technical details

- Tested with destination calendar of Outlook but seems like it could be any

<sub>[CAL-1265](https://linear.app/calcom/issue/CAL-1265/rescheduled-events-are-not-updated-on-calendars)</sub>

**Comment by shivamklr** [comment]
Sure thing @keithwillcode, will start working on this soon.

**Comment by hariombalhara** [comment]
[This issue was fixed](https://github.com/calcom/cal.com/pull/7851/files#diff-f028774ebd744c3141fb60f0fb171c59a2ae4773b285b70f834114e7a3d7afa2R442) around a week after reporting this issue. I think this was the issue where new booking doesn't have the references and were relying on that. Now, we are falling back to existing booking if new booking doesn't have the references.
Though as far as I can see, new booking won't have references like ever, as they are set later on to it.
