### ISSUE TITLE
[CAL-1278] team invite unintuitive (needs manual approval)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7788]
when they get the Team invite link, it doesn't automatically join a team, but instead the interface makes you go to the team tab and manually Accept (not v intuitive).

There is also a bug where a user is invited to a team > they accept via email > they try to change their username > error says "email address is already taken"

Would be very grateful to bang this out over a quick phone call v slack - looking to migrate hundreds of people in the coming months but this is roadblocking us.

[Slack Message](https://calendso.slack.com/archives/C01NXDSRY9W/p1678997246958269?thread_ts=1678993953.633269&cid=C01NXDSRY9W)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1278](https://linear.app/calcom/issue/CAL-1278/team-invite-unintuitive-needs-manual-approval)</sub>

**Comment by PeerRich** [comment]
@alishaz-polymath wanna look into this?

**Comment by shirazdole** [comment]
@alishaz-polymath - had some issue with onboarding a customer onto teams today; I'll recount below:

- Had they do their email +1 basically to create test accounts that they would set-up with all the settings they want for their users. The goal is to change the email after the accounts were set up. 
- For some reason, the accounts were not getting the invite email, in this case it was "mbezruchko+1@bvp.com" and "mbezruchko+2@bvp.com"
- We ended up using her personal email instead which successfully triggered an invite email, when she received the invite email and went to create the account she encountered a couple issues: 1) she wasn't logged out right away since she was already logged into another cal.com account, 2) when she went to create the account, it said that the user "was already created" — I was able to duplicate the issue in the loom below 
- We also had issues with changing the username and changing the email after the fact, but I wasn't able to duplicate those issues 

https://www.loom.com/share/d6ecd9f3a075416bb97e41af857efb13

**Comment by shirazdole** [comment]
Some issues with the copy as well (ty hanging onto the next line and the other thing)
![CleanShot 2023-03-27 at 19 32 15@2x](https://user-images.githubusercontent.com/16177678/228112175-c666d340-d77e-4596-83d9-805b6d82ea13.png)

**Comment by sean-brydon** [comment]
Closing as this should be fixed as of the org invites that was just merged.
