### ISSUE TITLE
[CAL-1344] Additional fields that attendees are not able to fill out

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7953]
Customer has additional fields that attendees are not able to fill out

Event type: [https://cal.com/laratiton/consultoriaestrategica](https://cal.com/laratiton/consultoriaestrategica)

Last two additional fields can't be filled out.

Created via Threads. See full discussion: [https://threads.com/34459068919](https://threads.com/34459068919)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1344](https://linear.app/calcom/issue/CAL-1344/additional-fields-that-attendees-are-not-able-to-fill-out)</sub>

**Comment by hariombalhara** [comment]
Fixed this particular issue. The bug occurred because the field `name` is having a comma, which `react-hook-form` doesn't work well with. I have just removed the comma from the two field names.

This happened because the fields were created as custom inputs and were migrated to new Booking Questions with name same as label.Followup would be ensure that during migration, **comma** is removed. We don't want to make any other modifications so that the we remain compatible with the data that we were posting earlier in webhooks
