### ISSUE TITLE
[CAL-1367] get rid of sentry warnings

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8004]
![CleanShot 2023-03-29 at 12 55 52@2x](https://user-images.githubusercontent.com/8019099/228512594-296b98cb-5383-4296-bd49-a57be6645d58.jpg)

<sub>[CAL-1367](https://linear.app/calcom/issue/CAL-1367/get-rid-of-sentry-warnings)</sub>

**Comment by PeerRich** [comment]
@hariombalhara can you look into this?

**Comment by lforst** [comment]
Hi, maintainer of the Sentry Next.js SDK here. Very randomly stumbled onto this issue.

These errors show up in the console because adblockers block requests to Sentry (we told them numerous times that Sentry does not collect anything but w/e). The only way to get rid of these errors is to proxy sentry requests through your own server so that the ad blockers cannot pattern match for our ingest endpoint.

Since you're using the Next.js SDK you have an easy way to do this via the [`tunnelRoute` option](https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-tunneling-to-avoid-ad-blockers). Please note that this can massively increase your server usage depending on how many requests you're sending.

**Comment by PeerRich** [comment]
aight bet! closing
