### ISSUE TITLE
[CAL-1377] feature: add validation to "Booking Questions"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8032]
i wonder if we could add validation to Booking Questions such as for email input:

ends with "cal.com" and throw and error underneath if {{email}} does not end with "cal.com"

or similar

this way, users can block out users who aren't team members or similar

you could also easily do: "Invite Code" and only validate true if its === code you selected

**alternatives**
- a proper gate feature (more work, but probably better UI/IX

<sub>[CAL-1377](https://linear.app/calcom/issue/CAL-1377/feature-add-validation-to-booking-questions)</sub>

**Comment by joeshajan** [comment]
Hey, @PeerRich sorry I don't get where we should add the validation here. Can you elaborate on it a little more?

![image](https://user-images.githubusercontent.com/69904519/229149925-c964e72a-08dd-49eb-8c87-eecbcc81441c.png)

![image](https://user-images.githubusercontent.com/69904519/229150006-1d222888-6457-485f-a11e-526e8790e21a.png)

**Comment by erik-bower-daily** [comment]
Our need is we don't want just anybody to be able to book a meeting directly with our sales team. There are several ways to approach. An integration with clearbit and salesforce where if they are on our target 1000 account list, we show the cal.com widget on web pages instead of a contact us sales form. Another way is to validate the email address and force a real company address. This isn't as good because a lot of start ups use gmail. 

![image](https://user-images.githubusercontent.com/118539309/229188503-3d6611e7-5f71-4762-9e87-7f6206a8df7f.png)
Hubspot has this flag. The link goes here: https://knowledge.hubspot.com/forms/what-domains-are-blocked-when-using-the-forms-email-domains-to-block-feature?KBOpenTab

Lastly, i've used a service called serviceobjects.com in the past to screen. That might be too expensive but you could maybe apply the same proess they do. For example a simple thing to do for email validation is does the domain resolve? Does the email contain profanity, celebrity names, etc.  

Ultimately we don't want people to be able to book meetings if they are bogus contacts or too small to warrant our sales people's time.  If we could mitigate that, we'd probably get rid of the contact us form entirely because that just slows the process of connecting.  hope that makes sense.
