### ISSUE TITLE
Use argon2id instead of bcrypt

### ISSUE THREAD

**Issue by G2G2G2G** [calcom/cal.com#8048]
Not much to explain in this feature request
bcrypt was good in ~2010-2016
argon2 is better, and bcrypt shouldn't really be used after ~2016
argon2id is great in the current year.

**Comment by emrysal** [comment]
Argon2 is worth considering; however when doing so investigation should reflect the extra resource drain and the fact we use serverless. We also should keep in mind the dependencies and whether it works on lambda environments at all. 
 
I completely disagree that BCrypt should not be used after ~2016. - It is still completely secure to use; given it is used correctly with salt & pepper.

I added the "Low priority" label due to potential complications and also that bcrypt is perfectly fine. Thank you for bring it up though; will leave this issue open as a reminder for future implementation.

@keithwillcode
