### ISSUE TITLE
[CAL-1450] Filter bookings by attendee request

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#8181]
Customer request

"our team keeps requesting the ability to filter the bookings by attendee or search by booking content (they want to be able to find bookings with particular people easily). Is something like this planned maybe? I wonder if the app-wide search could be used for something like that. Now it doesn't seem to look in the booking details"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1450](https://linear.app/calcom/issue/CAL-1450/filter-bookings-by-attendee-request)</sub>

**Comment by nataliiavuk** [comment]
To provide more details:

**Request: 
As an agent I would like to be able to filter/search bookings by the guest name or email, 
it would be also nice to be able to filter by event type**

there was another request which I guess should be a separate task
**As an agent I would like to be able to go to the event settings from the booking - to identify the source f the booking or in case I need to troubleshoot the event**

Business case:
- our team is working with multiple clients which is why we had to create multiple teams which leads to our booking page to be really full + the list of users/teams that bookings beong to become really long (would be also cool if we could search by the user name if the dropdown is too long)
- our agents would like to be able to find a necessary meeting easily and the current filters are not enough to do it 
- they were using Calendly before and had some expectations regarding the filtering 

On the example that the agents provided from Calendly they were using the following filters
- _Team (exists in cal.com)_
- _User (exists in cal.com)_
- **Event type** 
- _Event status (active/inactive - i don't think there is an analogy in cal.com )_
- _Tracking ID (i don't think there's an analogy in cal.com)_
- **Invitee email**
