### ISSUE TITLE
[CAL-1463] Payments cannot be disabled on a cloned paid event type

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#8206]
Recently we got a customer support request from a user that reported that he "Pending payment" for bookings that were turned off. Later he added that he originally cloned that event type from a paid event type.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1463](https://linear.app/calcom/issue/CAL-1463/payments-cannot-be-disabled-on-a-cloned-paid-event-type)</sub>

**Comment by joeshajan** [comment]
Could you please tell me how I can create a paid event? @zomars. I tried but I was not able to find the option for that.

**Comment by hariombalhara** [comment]
A booking depends on it's eventType to get payment data. It doesn't store anything related to payment in it's own table(except `paid` status).

Also, an EventType stores metadata.apps along with it and on cloning an eventType that data goes to the cloned event type as well as is.

So, I don't see any issue caused due in a cloned paid event wrt payments. If the origin event has disabled stripe, that information would go to cloned event and it would have stripe disabled automatically.

If a cloned event is booked when it has stripe is enabled and then later on stripe is disabled, the booking would reflect the status automatically because it refers to it's eventType for payment related info

I am closing this ticket for now. Let's reopen if someone else comes up with the same issue.
