### ISSUE TITLE
[CAL-1482] Booking not found error on cancel link for user with seat

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#8244]
### Issue Summary

When clicking on the cancel link in the confirmation email of a seated event it is throwing 404 booking not found. Not happening for the first seat booked. 

### Steps to Reproduce

1. Create a seated event type 
2. Make a sample booking 
3. Make a second sample booking 
4. Click on the cancel link from the confirmation email of the second sample booking
5. URL throws 404

<sub>[CAL-1482](https://linear.app/calcom/issue/CAL-1482/booking-not-found-error-on-cancel-link-for-user-with-seat)</sub>

**Comment by CarinaWolli** [comment]
@joeauyeung or @alannnc could you take a look at that?

**Comment by joeauyeung** [comment]
@CarinaWolli, what was the context behind this bug? I can't reproduce it.

**Comment by CarinaWolli** [comment]
Looks like this is already fixed, also can't reproduce it anymore

**Comment by rjackson** [comment]
I've re-discovered this issue when working on #9362.

The 404 page appears once you actually confirm the cancellation.

This is because the cancellation link from emails goes to `/booking/${seatUid}`. Once the BookingSeats entry has been deleted the `seatUid` no longer exists in the database, and so `/booking/${seatUid}` can no longer resolve a booking whose details to display.

**Comment by CarinaWolli** [comment]
@rjackson could you share a loom how you get the 404 error? I am to able to reproduce it 🤔
