### ISSUE TITLE
[CAL-1515] Issue with different start time when rescheduling

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8350]
Currently there is an issue when rescheduling an event that is in the same time frame of the original event.

for example, I have an appointment with a client from 14:30-16:30, and I need to push it back by 30min (so that it goes from 15:00-17:00), but the calendar doesn't show the 15:00 start time as available - because of the original event.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1515](https://linear.app/calcom/issue/CAL-1515/issue-with-different-start-time-when-rescheduling)</sub>

**Comment by jdaviescoates** [comment]
Yeah, I just hit this issue too and it's a bit frustrating.

Someone booked 11:30 - 12:15 but I realised I couldn't do that and we agreed by email that instead we'd meet at 11am instead. But I was unable to reschedule a 45 minute meeting to 11am because it overlapped with the original booking that I was rescheduling, so I had to reschedule to a 30 minute meeting instead just to get the correct start time in my calendar.
