### ISSUE TITLE
CalDav support used to work with Radicale but it is no longer working

### ISSUE THREAD

**Issue by timthelion** [calcom/cal.com#8523]
CalDav support used to work with Radicale (I'm on the ancient 1.1.1+v14 available with [sandstorm.io](https://sandstorm.io/) ). I don't see any way to debug this, CalDav works just fine with Thunderbird and DAVx5.

Here is what I see in Thunderbird:

![image](https://user-images.githubusercontent.com/1391608/234390462-610a1dce-dcb1-4ce6-b852-3f720779b4b2.png)

And here is what I see in cal.com

![image](https://user-images.githubusercontent.com/1391608/234390890-af3d9933-5ea0-42ef-9105-8da1d9b6d6df.png)

![image](https://user-images.githubusercontent.com/1391608/234391187-4a99579e-a42e-4b0d-bf15-d5d9ee5a6495.png)

![image](https://user-images.githubusercontent.com/1391608/234391334-05fe1b38-8bec-4c34-a7c1-72a6bfacc5f6.png)

As you can see, on days when there are events, some random times are blocked, but these are not the right times.

Here are relevant configurations:

![image](https://user-images.githubusercontent.com/1391608/234391030-3b63dbc8-edf4-43e2-b511-84f866f2d9a3.png)

![image](https://user-images.githubusercontent.com/1391608/234390778-9572bef9-4d5a-4416-8980-63cc87eee246.png)

**Comment by timthelion** [comment]
https://github.com/calcom/cal.com/issues/3457

**Comment by alishaz-polymath** [comment]
Hey @timthelion I tried to test out Radicale but I am unable to reproduce this. The changes in the CalDAV code are primarily to consider DST, I wonder if that had anything to do with it. However, before exploring this further I'd like to mention something I noticed in your Screenshots. 
The Timezone is different in the provided public page (ETC/GMT) vs the Availability/default Working hours (Europe/Belgrade).
That's a difference of 2 hours to begin with. Can you perhaps provide instructions on how to reproduce the error you're facing so that I can try to replicate that on my end and speed up the resolution?
Thanks 🙏

**Comment by alishaz-polymath** [comment]
Hey there @timthelion Can you please confirm if this is persisting?

**Comment by timthelion** [comment]
OK, so after examining the issue closely, it turns out that the trouble is somewhere between my client applications (thunderbird and android with Davx) and Radicale. The events are marked as Busy on the client applications but as Free in Radicale.

**Comment by charleslcso** [comment]
@timthelion so Cal recognises your busy events in Radicale and block the timeslots? Mine is not working/blocking...
