### ISSUE TITLE
[CAL-1604] team admin: see connected apps of team members

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8564]
![CleanShot 2023-04-29 at 19 21 19@2x](https://user-images.githubusercontent.com/8019099/235318279-b34e8fb6-9f0f-4d2d-b4c9-ab75ccefb2ff.jpg)

with a tooltip of the connected calendar, i.e. "peer@cal.com"

remember, someone can have two google calendar

<sub>[CAL-1604](https://linear.app/calcom/issue/CAL-1604/team-admin-see-connected-apps-of-team-members)</sub>

**Comment by shaikahmadnawaz** [comment]
Can I work on this issue?

**Comment by PeerRich** [comment]
sure go for it @shaikahmadnawaz

**Comment by PeerRich** [comment]
in the same PR can you also change app.cal.com/peer to cal.com/peer?


you can use the same code that's being used here:

![CleanShot 2023-04-29 at 20 16 12@2x](https://user-images.githubusercontent.com/8019099/235320413-2c498387-0c8f-4410-b18e-15e1310eb378.jpg)

**Comment by shaikahmadnawaz** [comment]
Thanks @PeerRich

**Comment by PeerRich** [comment]
@shaikahmadnawaz  any update on this

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz  any update on this?

Sorry @PeerRich, inactive because of exams, I will start working on this today itself and try to complete it 👍🏻

**Comment by riteshsp2000** [comment]
@shaikahmadnawaz are you working on this issue? 
If not, I'd like to work on this @PeerRich

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz are you working on this issue? If not, I'd like to work on this @PeerRich

Okay carry on @riteshsp2000

**Comment by PeerRich** [comment]
@riteshsp2000 go for it! adding a bounty too

**Comment by Kagabe** [comment]
@riteshsp2000 are you still planning to work on this? I'd like to attempt this @PeerRich :)

**Comment by Kagabe** [comment]
I'll do another bounty then.

**Comment by RahulkumarRV** [comment]
@PeerRich 
if it is not solved, I like to work on it, can you define this task more with an example?

**Comment by adarsh-technocrat** [comment]
Hi @PeerRich  can I take this up? can't see any PR attached to this issue.  

Cc: @riteshsp2000 @shaikahmadnawaz

**Comment by itsvanshchavda** [comment]
@PeerRich  I want to work on this give some more information so i can fix it

**Comment by adarsh-technocrat** [comment]
Hi Everyone sharing the pathway to solve this issue if anyone is interested can follow this path :)

**Requirements** 
-  Find the component where we need to make the necessary changes.
-  Identifying from where we can get the **relation** between the **installed apps and the user** 
- As this is specific to Admin then we need to add an `isAdmin `check to render installed apps to its members. 

I think this can help :)

Thank you !

**Comment by adarsh-technocrat** [comment]
Hi, @PeerRich  can you please assign this issue to me?

As per my findings, we need to work on this component ` team-members-view.tsx`   ( **MembersView** )

And the important thing is we won't directly get installed apps of members in 

```javascript
const { data: team, isLoading: isTeamsLoading } = trpc.viewer.teams.get.useQuery(
    { teamId },
    {
      onError: () => {
        router.push("/settings");
      },
    }
  );
```
The way to solve this issue is we need to get Members  installed apps data from the `Credential`  table  where we have the relation of installed apps and user

| id | type                        | key      | userId |   appId    | invlid | teamId |
|----|---------------------|---------|-------|------------|--------|---------|
| 1  | whatsapp_video      | {}      | 8     | whatsapp   | false  |  [null]   |
| 11 | metapixel_analytics | {}      | 3     | metapixel  | false  | [null]  |
| 13 | telegram_video      | {}      | [null]       | telegram   | false  |  11  |


As we are getting members' userId from `teams` so it's pretty straightforward now to get installed apps of members by performing a simple query on the `Credential` table by passing userId in the` where clause`.

Once we get members' Installed apps data we can create one helper function with the help of `map `and `reduce`  to group all `distinct apps`  according to` userId`

As in the `Credential` table, we don't get complete info on apps probably we can take reference from the below function 
```javascript

const getEnabledApps = async (userCredentials: CredentialData[]) => {
  const enabledApps = await prisma.app.findMany({
    where: { enabled: true },
    select: { slug: true, enabled: true },
  });
  const apps = getApps(userCredentials);

  const filteredApps = enabledApps.reduce((reducedArray, app) => {
    const appMetadata = apps.find((metadata) => metadata.slug === app.slug);
    if (appMetadata) {
      reducedArray.push({ ...appMetadata, enabled: app.enabled });
    }
    return reducedArray;
  }, [] as (ReturnType<typeof getApps>[number] & { enabled: boolean })[]);

  return filteredApps;
};
```

As only `Admin `can see the installed apps of its member so we already have this simple check which we can use to conditional render installed app icons on the member component list 😃 

```javascript
  const isAdmin =
    team && (team.membership.role === MembershipRole.OWNER || team.membership.role === MembershipRole.ADMIN);

```

```javascript
  {((team?.isPrivate && isAdmin) || !team?.isPrivate) && (
              <>
                <MembersList team={team} />
                <hr className="border-subtle my-8" />
              </>
            )}

```

@PeerRich  please let me know if my findings are in the right direction.

Thanks :)

**Comment by ViswanthSwarna** [comment]
Hi @PeerRich, I have few questions.

Is connected app same as installed app?
I assumed Yes. but if yes, what should be the tooltip for apps in every category?
do we need to display apps of member who didn't accept invitation?
I assumed not. 

this is how it looks based on above assumption 

![image](https://github.com/calcom/cal.com/assets/32818871/32f33dca-0ed8-4b2b-9258-0cbc33a4c639)
