### ISSUE TITLE
[CAL-1626] prevent reloading of mobile top nav and bottom nav

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8734]
[f6b679a4-0e92-4fa0-a569-c9b617ce887d](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6ebe40de-eb24-4b66-98ac-7c83fada1e13/f6b679a4-0e92-4fa0-a569-c9b617ce887d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1626](https://linear.app/calcom/issue/CAL-1626/prevent-reloading-of-mobile-top-nav-and-bottom-nav)</sub>

**Comment by vedant-jain03** [comment]
@PeerRich I wanted to work on this issue

**Comment by saikumarpb** [comment]
@PeerRich the issue seems to be not happening. please find my screen recordings attached. 

If this issue is happening in certain scenario, please do provide the steps to reproduce

[Screencast from 07-05-23 06:14:37 PM IST.webm](https://user-images.githubusercontent.com/50828572/236679280-7855122d-a3ef-4d13-abd6-115eef43cdab.webm)
[Screencast from 07-05-23 06:32:09 PM IST.webm](https://user-images.githubusercontent.com/50828572/236679281-f6e60a62-ea71-4085-85ff-51f875953689.webm)

**Comment by PeerRich** [comment]
seems to be fixed
