### ISSUE TITLE
[CAL-1627] Social share previews don't render ampersands

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8745]
Created via Threads. See full discussion: [https://threads.com/34470827863](https://threads.com/34470827863)

![Screenshot 2023-05-08 at 10.12.17.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/04c0ec20-0e64-499c-b8f0-3626f74b3251/32a8d40a-69ff-43b5-ab0a-d41d0ec21afc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1627](https://linear.app/calcom/issue/CAL-1627/social-share-previews-dont-render-ampersands)</sub>

**Comment by AyushMainali123** [comment]
Hey @milospuac , It seems this thread is not publicly accessible, or am I missing something here?

![image](https://user-images.githubusercontent.com/49358949/236777567-e185f2c3-d115-45fd-ae67-c402c41ca16a.png)

**Comment by milospuac** [comment]
Our thread is private, but I posted the picture which explains the issue. If in your profile description you have "&" symbol, the social preview image won't render it properly.

**Comment by AyushMainali123** [comment]
Got it, Thank you for the explanation. I will look into this issue now.

**Comment by milospuac** [comment]
@AyushMainali123 cool, I'll assign it to you. Thanks for contributing 🫡

**Comment by AyushMainali123** [comment]
Hey @milospuac , this  issue might be caused by NextSeo component we are using (imported from 'next-seo') inside HeadSeo component.

I have console logged the props that is sent to NextSEO. 
The props that is being passed to the NextSeo is not being convert into that entity. 

![image](https://user-images.githubusercontent.com/49358949/236789091-2e5411c5-8c1b-4736-aaa4-91118c217e04.png)
![image](https://user-images.githubusercontent.com/49358949/236789193-9c59369d-414c-4c82-ae6a-357dc488e60e.png)

**Comment by AyushMainali123** [comment]
@sean-brydon  @milospuac  , 

Could you please verify this behavior? If it's correct, we can create a workaround by replacing `&` with `and`. However, for other HTML entities, such as `&apos;`, we may not have any alternatives except to contact the team responsible for creating the library.

Please let me know if my diagnosis is wrong or if I am missing something here.

Thank you!
