### ISSUE TITLE
Fully booked days are not grayed out

### ISSUE THREAD

**Issue by marvinvonhagen** [calcom/cal.com#877]
### Issue Summary

While days in the past and disabled days are correctly grayed out to indicate that booking is not possible on those days, fully booked days are not grayed out.

### Steps to Reproduce

1. Connect your Google Calendar to Cal
2. Have one day fully booked with meetings
3. Try to book a meeting on cal.com/username
→ This day is displayed as bookable / not grayed out. Only when you click on it, you will get the prompt "All booked today".

**Comment by joshsny** [comment]
It'd probably make sense to refactor the getSlots function to pull availability for the whole month, rather than each day at a time. We'd then request the availability every time the selected month is changed rather than the selected date.

In terms of API response times, I think it'll be pretty similar requesting availability for 1 month vs for 1 day. What do you think @emrysal, since you recently refactored some of this?

**Comment by lhqs1314** [comment]
When will this feature be added :pleading_face:

**Comment by PeerRich** [comment]
> When will this feature be added 🥺

@lhqs1314 it was added in last weeks new version!
