### ISSUE TITLE
Allow the inviter to set the meeting duration

### ISSUE THREAD

**Issue by kimjin8** [calcom/cal.com#88]
As a Calendso user who is invited to meet with the inviter, I want to share my availabilities via Calendso and let the inviter set the meeting duration/ending time, so that I don't need to ask the inviter for the meeting duration.

**Comment by harad1** [comment]
I think it's helpful for those thinking how to implement this (unless, you'd like to give it a try), if you provide some more detail. 

For example: 
— How would you implement this? If you don't know how you would do it programmatically, you could describe the "high-level" vision of how this would work. For example, as a Calendso user you can currently create different event types of various durations — you can then decide which event type to send the link to. Thus, would you have a completely separate "customisable duration event type", which is the only event type that for which duration can be changed? What's your vision?
— I might be misunderstanding what you are saying, but an "inviter" is the person inviting, and "invitee" is the person being invited — if you send your Calendso link to someone, then you are the inviter, and the person you are sending it to, an invitee. Therefore, by saying "[I want to] let the inviter set the meeting duration/ending time" - do you mean "invitee"? Since you can already can do that as an inviter (the person sending the invite) — you create different event types as a Calendso user and thus implicitly set the duration of those events when creating an event type and sending off the link. 

Apologies if misunderstood what you said but if you can clarify then I can start thinking about the ways in which this could be accomplished and perhaps ask you for some additional clarification.

**Comment by yshuang13** [comment]
I like this idea. I'm not sure if Calendly has this feature.

From a UX perspective, here's how I think it would work:
1. For a specific or every Friday, 1pm-5pm are my 1:1 "office hours" for my students (invitees). I select that they can schedule a block of 15, 30 or 60 minutes depending on their need (I would think these 3 would be the top 3 options available and in demand, with 20 min and 50 min being the 2 other timeframes that I would recommend being options for the inviter's UI)
2. Invitee goes to meeting booking screen in Calendso, select the date of interest
3. Here's where the UI would differ: Invitee is asked if they'd like a 15, 30, or 60 minute meeting
4. the UI provides meeting start times at 15 minute intervals such that the 15, 30, or 60 minute meeting would end within the 1-5pm time frame
5. Same UI moving forward for booking meetings as with regular meeting.

Future features: ability for invitee to return to start of booking process if invitee wants to change the meeting duration to longer or shorter.

**Comment by PeerRich** [comment]
I dont think its a good idea to have dynamic times for each event-type. I think it's better to have one event-type for each duration.

in my experience its quite rare that the same event type has different durations.

closing for now.

a way to solve this:

have an event type for 15min, 30min and one for 60min (that's how all scheduling tools do it)

**Comment by aspiers** [comment]
> have an event type for 15min, 30min and one for 60min (that's how all scheduling tools do it)

Unfortunately this is not a good solution.  I already tried that as a workaround in the past, and it was a massive pain.  For example, let's say I want the following event types:

- Personal video call for non-work topics
- In-person meeting for personal topics
- Work video call with colleagues within my company
- Work video call with external particpants outside my company

All of these need their own event type, because they all require different parameters.  However I want to give anyone requesting any of these types of meetings a choice of different time durations.  (The "office hours" scenario mentioned above is one of several great reasons why this can be needed.)  If those choices are limited to, say, 30 / 60 / 90 mins, then that multiplies the four event types above by 3, so I have to create 12 event types in total.  If I also want to allow other durations like 15 mins or 120 mins then it gets even worse.

> in my experience its quite rare that the same event type has different durations.

I can of course appreciate that this is your experience, but it doesn't mean that many other people have different needs.  If you want to cater to the huge addressable market for calendar apps then I believe this is the kind of flexibility a lot of people will find useful. 

So I would be super grateful if you could reconsider this feature request.  I know that some of your competitors don't offer this feature, but that's a great opportunity for Cal to differentiate itself and become even more awesome ;-)

**Comment by PeerRich** [comment]
> > have an event type for 15min, 30min and one for 60min (that's how all scheduling tools do it)
> 
> 
> 
> Unfortunately this is not a good solution.  I already tried that as a workaround in the past, and it was a massive pain.  For example, let's say I want the following event types:
> 
> 
> 
> - Personal video call for non-work topics
> 
> - In-person meeting for personal topics
> 
> - Work video call with colleagues within my company
> 
> - Work video call with external particpants outside my company
> 
> 
> 
> All of these need their own event type, because they all require different parameters.  However I want to give anyone requesting any of these types of meetings a choice of different time durations.  (The "office hours" scenario mentioned above is one of several great reasons why this can be needed.)  If those choices are limited to, say, 30 / 60 / 90 mins, then that multiplies the four event types above by 3, so I have to create 12 event types in total.  If I also want to allow other durations like 15 mins or 120 mins then it gets even worse.
> 
> 
> 
> > in my experience its quite rare that the same event type has different durations.
> 
> 
> 
> I can of course appreciate that this is your experience, but it doesn't mean that many other people have different needs.  If you want to cater to the huge addressable market for calendar apps then I believe this is the kind of flexibility a lot of people will find useful. 
> 
> 
> 
> So I would be super grateful if you could reconsider this feature request.  I know that some of your competitors don't offer this feature, but that's a great opportunity for Cal to differentiate itself and become even more awesome ;-)

can you recommend your favorite way you'd want this to be implemented?

**Comment by aspiers** [comment]
[**@PeerRich**](https://github.com/PeerRich) commented on [March 19, 2022 11:39 PM](https://github.com/calcom/cal.com/issues/88#issuecomment-1073130620 "2022-03-19T23:39:59Z - Replied by Github Reply Comments"):
> can you recommend your favorite way you'd want this to be implemented?

Thanks a lot for the quick response and for being open-minded on this!  I think the implementation could be very simple:

1. When creating a new event type, multiple durations are allowed, e.g. add a `+` (plus) icon to add extra durations, and a trash icon to remove them.  Or allow comma-separated values like `15,30,60` as a more quick and dirty implementation.
2. When using an event type link to book a slot, if the event type has multiple durations, then the person booking the event has to first choose a duration before proceeding as normal with the rest of the booking process.  Then the availability will be displayed according to that chosen event duration.
3. Make it easy (i.e. ideally with a single click) for the person booking to change their duration choice after selection, in which case the displayed availability is adjusted accordingly. So for example if they are looking for an hour slot but can't find any availability which works for them, they have the option of reducing the slot to 30 mins in order to potentially gain more options.
4. [Stretch goal for optimal UX] If the event type allows multiple durations, then after the user of the link selects a duration and a day, if there are no slots available for that combination, do one of the following:
    - If there are smaller slots available on that day, rather than just displaying "All booked today", display something like "No 60 minute slots today, but there are two 30 minute slots." and a button "__Reduce duration to 30 minutes__" which changes the duration parameter and updates the display accordingly.
    - If there are *no* smaller slots available on that day, display something like "No slots of any duration available today".  (Just keeping the original "All booked today" text would also be OK, but I was thinking that this change might clarify the situation a bit better in this case.)

**Comment by aspiers** [comment]
I also note that there seems to be some terminology confusion here which we should try to clear up:

[**@harad**](https://github.com/harad) commented on [April 22, 2021 9:43 PM](https://github.com/calcom/cal.com/issues/88#issuecomment-825172079 "2021-04-22T20:43:30Z - Replied by Github Reply Comments"):
> 2.  I might be misunderstanding what you are saying, but an "inviter" is the person inviting, and "invitee" is the person being invited — if you send your Calendso link to someone, then you are the inviter, and the person you are sending it to, an invitee.

That seems the exact opposite of what I'd expect, and therefore quite confusing.  In my mind, the person who receives the link and uses it to request a meeting is the one trying to set up the meeting, and therefore they are the inviter, and the owner of the cal.com account and link is the invitee.  In other words, "I am using your cal.com link to invite you to a meeting".

Perhaps this confusion stems from the fact that an event link can either result in an immediate booking, or it can result in an invite which requires confirmation.  In the former case, I can see an argument for describing the link sender (i.e. cal.com account holder) as the "inviter", since they are inviting the counterparty to book their time.  But in the latter case, the link sender is "inviting the other party to create an invite"!

> Therefore, by saying "\[I want to\] let the inviter set the meeting duration/ending time" - do you mean "invitee"? Since you can already can do that as an inviter (the person sending the invite) — you create different event types as a Calendso user and thus implicitly set the duration of those events when creating an event type and sending off the link.

Since the original description begins with the words "As a Calendso user who is invited to meet with the inviter", it seems very clear to me that this is not what is being asked for, and that @kimjin8 and I both think of the Calendso user being the "invitee" and the person using the link as the "inviter".  It is well understood that an event type can already be customised to a single, fixed duration, but this issue is requesting more than that, i.e. that the duration of the event type can be flexible.

**Comment by PeerRich** [comment]
we talked about it internally and the implementation is not straightforward enough to ship a quick fix and for a proper feature release it is not demanded by enough people yet.

if you think this is a super high priority and we should work on this, instead of other critical things, upvote the initial post 👍

**Comment by aspiers** [comment]
I definitely don't think it's super high priority, or perhaps even high priority :-)  And I agree that it's not a super quick fix.

However I do think it would be a valuable addition to the feature set, and quite possibly a feature that people won't necessarily realise they want until it appears.  So I hope you keep it on the backlog of things to consider for the future at least.  Thanks again!

**Comment by harad** [comment]
> I also note that there seems to be some terminology confusion here which we should try to clear up:
> 
> [**@harad**](https://github.com/harad) commented on [April 22, 2021 9:43 PM](https://github.com/calcom/cal.com/issues/88#issuecomment-825172079):
> 
> > 2. I might be misunderstanding what you are saying, but an "inviter" is the person inviting, and "invitee" is the person being invited — if you send your Calendso link to someone, then you are the inviter, and the person you are sending it to, an invitee.
> 
> That seems the exact opposite of what I'd expect, and therefore quite confusing. In my mind, the person who receives the link and uses it to request a meeting is the one trying to set up the meeting, and therefore they are the inviter, and the owner of the cal.com account and link is the invitee. In other words, "I am using your cal.com link to invite you to a meeting".
> 
> Perhaps this confusion stems from the fact that an event link can either result in an immediate booking, or it can result in an invite which requires confirmation. In the former case, I can see an argument for describing the link sender (i.e. cal.com account holder) as the "inviter", since they are inviting the counterparty to book their time. But in the latter case, the link sender is "inviting the other party to create an invite"!
> 
> > Therefore, by saying "[I want to] let the inviter set the meeting duration/ending time" - do you mean "invitee"? Since you can already can do that as an inviter (the person sending the invite) — you create different event types as a Calendso user and thus implicitly set the duration of those events when creating an event type and sending off the link.
> 
> Since the original description begins with the words "As a Calendso user who is invited to meet with the inviter", it seems very clear to me that this is not what is being asked for, and that @kimjin8 and I both think of the Calendso user being the "invitee" and the person using the link as the "inviter". It is well understood that an event type can already be customised to a single, fixed duration, but this issue is requesting more than that, i.e. that the duration of the event type can be flexible.

@aspiers whilst I appreciate your argument, I still think that the cal.com's user is the inviter, and the person receiving the link would be the invitee. Since the link originates with the inviter, not the invitee. Ultimately, it's the person with the greater control over the link and the available times for the meeting should be the inviter. 

The inviter, the cal.com's user, is streamlining the process of scheduling a meeting with them, and therefore, makes a link available. Interesting take on: 'In other words, "I am using your cal.com link to invite you to a meeting"'. - I would argue it's the right opposite, and your example is very specific. Whilst it's true in some cases and probably largely depends on the way you use cal.com, I use cal.com to simply reduce back-and-forth, even when I'm the one asking the person for a meeting - therefore, for me, it'd be more of "I am asking you to use my cal.com link to invite you to a meeting". As in, I am providing you with my cal.com link, so we can have a meeting at a mutually convenient time. If you send a birthday party invitation, who is the inviter, and who is the invitee? The person whose birthday we are celebrating, or the person who is attending the party? I'd strongly argue it's the former, not the latter. 

Whilst I don't have the data to back it up to what most people think - I think potentially changing the meaning of inviter/invitee could lead to some serious confusion among the users. Happy to be proved wrong.

**Comment by aspiers** [comment]
Thanks @harad, I do see your points.  Ultimately both perspectives have validity, and it's not a matter of one being right and the other being wrong.  In case you have any doubts about that, please consider this scenario:

1. I have a conversation with a friend or colleague, either online or offline, in which I mention that if they ever need to talk to me about anything, they are welcome to book a time slot via the given cal.com URL.  They make a note of this URL for future use.
2. Six months later, they visit this URL to book a time slot.  An email automatically appears in my inbox asking me to confirm whether I am OK with that time slot.  I confirm, and the meeting happens.
3. Six months later, the same thing happens again.

In this scenario, they are much closer to being the inviter than I am, since I never requested organisation of a specific event; I merely expressed my openness to being available, should they wish to meet with me.  On both occasions, they were the one who initially proposed the meeting.  Cal.com was merely the tool to facilitate this process in an efficient manner, but I could have equally said "look, if you ever want to talk, just send me an email and we'll find a time we're both free".

But anyway, let's not get too distracted into a long debate on the semantics ;-) That would not be very productive, and it's certainly off topic for this particular GitHub issue.  There are two concrete takeaways here:

1. It seems very clear that the OP was using "inviter" to refer to the person using the link to book a time slot.
2. As a more general point, it's important that cal.com uses clear wording to avoid any confusion along these lines.  I believe the wording I have seen so far has been perfectly clear, so I'm not aware of anything actionable on that front.
