### ISSUE TITLE
[CAL-1728] confirmation mail: booking questions uses identifier not label

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8998]
![image](https://github.com/calcom/cal.com/assets/8019099/c5838fd1-43f2-47d1-abc6-b9ab7957386b)

![image](https://github.com/calcom/cal.com/assets/8019099/80a81823-3aef-41ce-ad6a-a7ea3c1f7581)

![image](https://github.com/calcom/cal.com/assets/8019099/2332ff16-f802-4dd5-9f4e-e00f3784dfbb)

<sub>[CAL-1728](https://linear.app/calcom/issue/CAL-1728/confirmation-mail-booking-questions-uses-identifier-not-label)</sub>

**Comment by PeerRich** [comment]
emails (everywhere in general) should use label and not identifier

**Comment by shaharyar-shamshi** [comment]
hello @PeerRich is this issue in the main branch because I checked the main branch from code perspective it is still label

**Comment by gitstart-calcom** [comment]
Hi @PeerRich 
We tried to reproduced the issue with a new added question (screenshot below) <img alt="Screenshot 2023-05-24 at 11 57 34" width="1500" src="https://private-user-images.githubusercontent.com/8848104/240581787-1f32fbb7-679e-4693-8b31-9875c2469ac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjg0OTQxMjI0LCJuYmYiOjE2ODQ5NDA5MjQsInBhdGgiOiIvODg0ODEwNC8yNDA1ODE3ODctMWYzMmZiYjctNjc5ZS00NjkzLThiMzEtOTg3NWMyNDY5YWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMwNTI0VDE1MDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOTIxYzQ3OGE5Yzk2ZGZmMDU3MjgwNzQ5ZjE1ZjQ4YmJiOGEzMWE5Yzk5N2YyZTI1YTRkNGZlZjgyN2JiMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MxGcUJ6KDONOouDQCJ3KeU3Gk7aW9aeMiU0JRrXiLhI">
 
And from the mail we have received, we noticed that the question label is used instead of identifier. <img alt="Screenshot 2023-05-24 at 11 57 21" width="959" src="https://private-user-images.githubusercontent.com/8848104/240582695-30357291-9211-4e79-b319-913fb2438682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjg0OTQxMjI0LCJuYmYiOjE2ODQ5NDA5MjQsInBhdGgiOiIvODg0ODEwNC8yNDA1ODI2OTUtMzAzNTcyOTEtOTIxMS00ZTc5LWIzMTktOTEzZmIyNDM4NjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMwNTI0VDE1MDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMTc0MmQ4NTczNWEzMjk3NWEwYmYyY2Y2MzBiYmIzZDBkNGZmNWQzY2JiOWVjOTlhODJiOTNkZDE0MDJlOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RixiSCF1x2vG5yOe3ZYHTE56rBuvzds-pnGo7YbHIg4">

**Comment by hwdsjtu97** [comment]
@PeerRich Hi, I am interested in taking this one. Would you mind sharing how to get to the "add a question" page?

**Comment by PeerRich** [comment]
@hwdsjtu97 its in event-types > advanced settings

**Comment by ujwalkumar1995** [comment]
Hey @PeerRich
I tried replicating this issue but it is working fine for me.
To replicate, I add a question in event types. I created a booking. The email that I received was fine and was showing labels and not identifiers.
Is it some specific scenario that is causing this?

**Comment by PeerRich** [comment]
can you try turning on "requires confirmation" and try again?

**Comment by ujwalkumar1995** [comment]
Hey @PeerRich 
Just to confirm are you seeing this issue on the live production app or is this something that you observed in your local machine from the main branch?

**FYI:** I tried this on the live production app with "requires confirmation" on but was not able to replicate it. On my local machine, I am not sure how we can replicate it without the SMTP server. I tried to put some logs to see what body is being passed to the email. Don't see anything wrong in there.
