### ISSUE TITLE
[CAL-1765] opt-in: clicking "confirm" or "reject" broken

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9110]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1b0edf51-2e0a-4abf-b9de-0553859432e6/2bd5a8a9-e0d4-444d-b8ef-8b6d2a25af57)

both buttons just goes to the booking page view

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/40810dea-1607-430f-bc20-fa66d095e08a/8453a8ec-42f0-4573-b6fa-310e9b89bd76)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1765](https://linear.app/calcom/issue/CAL-1765/opt-in-clicking-confirm-or-reject-broken)</sub>

**Comment by Subhojit-Dey1234** [comment]
Is it possible to share any video? I just checked it is working for me. I might be not able to understand the issue.

**Comment by shirazdole** [comment]
Yah not working for me, what happens is when you press the "reject" button for example, you get led to the page that the person who booked you sees rather than what you see as a host:
![CleanShot 2023-05-25 at 10 53 35@2x](https://github.com/calcom/cal.com/assets/16177678/1f4e7090-600e-4c9e-92c7-f1748fb73f6a)
![CleanShot 2023-05-25 at 10 54 40@2x](https://github.com/calcom/cal.com/assets/16177678/bb3b0626-433b-4587-9555-f4e3053c9fae)

**Comment by leog** [comment]
@shirazdole @PeerRich I can't reproduce the issue. The logic seems to be fine, first accepts and rejects the booking and then redirects the user to the booking page, which shows the current status, if it was accepted/rejected in the previous step. Not sure if a loom would help visualize it, perhaps forwarding me the emails with the confirm/reject buttons that doesn't seem to be working so I can debug better.

**Comment by Udit-takkar** [comment]
@leog yeah works fine for me too locally

**Comment by keithwillcode** [comment]
Still happening. Let's investigate.
