### ISSUE TITLE
[CAL-1769] embed: replace loading animation with skeleton

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9116]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c113cb8c-6b93-4ccc-b9bc-741b1dcc416f/6f88cdea-f290-4f41-98ff-1fa2b1894dfd)

should be a skeleton of the embed instead. we can launch this with the new booking page @hariombalhara @JeroenReumkens

ideally also no layout shitf

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1769](https://linear.app/calcom/issue/CAL-1769/embed-replace-loading-animation-with-skeleton)</sub>

**Comment by Ninad3721** [comment]
Can you tell me on which specific page the loader is shown instead of skeleton ?

**Comment by PeerRich** [comment]
its in the embed

**Comment by Ninad3721** [comment]
ok got it.

**Comment by riteshsp2000** [comment]
@PeerRich 

I would like to work on this issue. I have gone through the designs and found the [embed skeletons](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/1.-Cal-DS?type=design&node-id=1183-43880&t=65GyxlTPcwE25ym0-0) Could you please confirm if these are the appropriate ones? If so, I'll start creating/updating the required components.

**Comment by hariombalhara** [comment]
We need to understand first that the loader is there for the time the booker in the iframe isn't ready. AFAIR, we keep the embed iframe hidden(and the loader running) till the window load in iframe has happened. 

We do that so that embed iframe's height has appropriately adjusted before showing it. Otherwise the situation can be that initially there is only 100px of content in the iframe and iframe's height is 100px and then some other content loads in a few milliseconds and it increases the height to 150px then iframe adjusts it's height to 150px. So, there would be multiple CLS happening on the page which doesn't look good. 
Note that, this is done because we don't want the scrollbar to ever appear in iframe as long as your viewport is big enough.

So, the loader is actually shown from T1 -> Tn time where T1 is when embed.js loads on the page and Tn is when window.load event fires in iframe. We should work towards moving Tn to some time earlier, ideally the time when iframe get's it first byte(after that the skeleton in iframe would be shown automatically).

Now, assuming that we have made that improvement we might not need this loader itself.

@riteshsp2000 if you would like you can try removing the style to hide the content from the iframe. https://github.com/calcom/cal.com/blob/main/apps/web/pages/_document.tsx#L55 
Also, fire this [linkReady](https://github.com/calcom/cal.com/blob/main/packages/embeds/embed-core/src/embed-iframe.ts#L332) event as early as possible so that the loader goes away as soon as possible.
You can observe what happens in a few scenarios.

**Comment by riteshsp2000** [comment]
sure thing, I am on to it.

**Comment by gitstart-calcom** [comment]
we tried a lot of ways to solve it and unfortunately, we didn't find a solution good enough to push
