### ISSUE TITLE
[CAL-3885] Default to showing the next month with availability (instead of showing an empty state)

### ISSUE THREAD

**Issue by mxstbr** [calcom/cal.com#9153]
### Is your proposal related to a problem?

All visitors of my calendar links towards the end of the month are greeted by a view that says "No availability in {month}":

<img width="1820" alt="CleanShot 2023-05-26 at 11 15 48@2x" src="https://github.com/calcom/cal.com/assets/7525670/fd14b5a7-bf77-4231-bd45-2baa8ec2e09e">

### Describe the solution you'd like

By default, show the next month with availability. Why do my visitors have to manually navigate to it?!

### Describe alternatives you've considered

N/A

### Additional context

N/A

<sub>[CAL-3885](https://linear.app/calcom/issue/CAL-3885/default-to-showing-the-next-month-with-availability-instead-of-showing)</sub>

**Comment by emrysal** [comment]
The reason for the manual navigation is to prevent confusion - why only show June when we're still in May. But it's probably worth considering changing this CC @Jaibles

**Comment by Jaibles** [comment]
> The reason for the manual navigation is to prevent confusion - why only show June when we're still in May. But it's probably worth considering changing this CC @Jaibles 

I thought we did this for technical reasons due to fetching availability. IMO we should definitely show June here. There's enough places where it's made clear what month you're booking. 

Right now we don't allow people to navigate back to previous months. We could allow people to navigate back to months that have not yet passed, and there we show the component that explains there's no availability. This will allow bookers to double check why they're seeing the next month rather than current in case there's any confusion on that front.

**Comment by Hormor** [comment]
@Jaibles I would like to work on this.

**Comment by matheusmondaini-startse** [comment]
This issue is happening again: cal.com
