### ISSUE TITLE
[CAL-1831] Colour picker display padding

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#9228]
![CleanShot 2023-05-31 at 10.45.28.gif](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c1dc6f32-1979-4f5a-a774-eae1ab20d9b0/cd6b4236-5ad8-4794-bc54-23c5e5ddbe29)

When you change the colour picker from a colour other than default the padding changes 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1831](https://linear.app/calcom/issue/CAL-1831/colour-picker-display-padding)</sub>

**Comment by sagarsingh23** [comment]
Hi sea-brydon, Can you help me find out in which section I can find this bug?

**Comment by sean-brydon** [comment]
> Hi sea-brydon, Can you help me find out in which section I can find this bug?

This is in packages/ui/components/form/color-picker/colorpicker.tsx

It is used n your settings -> appearance :)

**Comment by sagarsingh23** [comment]
I have found this issue I just wanted to confirm it is happening because you have provided a fixed width to the form container in the appearance section, so on changing the colour, the padding changes because we are getting a reset to default button.

So what we can do is just shift the brand colour (dark theme) palette a bit left, and that will resolve the issue. Will that work for you?
