### ISSUE TITLE
[CAL-1859] Identifier "email" should be capitalized

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9311]
Under "advanced" in an event type, the pre-determined email field has an identifier that I believe should be capitalized 

![CleanShot 2023-06-04 at 09.05.48@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7a61a42f-76c9-4d99-a85d-8d8b9c30937c/53fc55ad-287f-41f6-be09-006490f110f0)

cc @hariombalhara 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1859](https://linear.app/calcom/issue/CAL-1859/identifier-email-should-be-capitalized)</sub>

**Comment by shirazdole** [comment]
I think the "n" in "Additional notes" should be capitalized as well 

![CleanShot 2023-06-04 at 09.26.20@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dedc2624-b250-4d7d-b3d0-01e1337e1322/a9c12f8e-302c-438b-8d95-ba93d8f7cbaf)

**Comment by Shubh-2402** [comment]
I would like to work on this issue @shirazdole

**Comment by shirazdole** [comment]
I would wait to hear from @hariombalhara in case this effects anything in the database

**Comment by shirazdole** [comment]
Thank you! @Shubh-2402

**Comment by Shubh-2402** [comment]
Sure. I will pick it up after some more discussion on this issue. @hariombalhara @shirazdole

**Comment by a0m0rajab** [comment]
I did a quick check: 

As for additional notes, it would be able to be changed from: 

https://github.com/calcom/cal.com/blob/26400403593382056d45650cee3c62abd4e4e1d8/apps/web/public/static/locales/en/common.json#L1149

And 

https://github.com/calcom/cal.com/blob/26400403593382056d45650cee3c62abd4e4e1d8/apps/web/public/static/locales/en/common.json#L490

Changing this will not break the database since it's only on the localization file. 

As for identifiers: 

Here is the related code block: 

https://github.com/calcom/cal.com/blob/26400403593382056d45650cee3c62abd4e4e1d8/packages/features/form-builder/FormBuilder.tsx#L488-L497

I am investigating the source of the word, and if it's connected to database (I think it's not)

**Comment by a0m0rajab** [comment]
Whoever will take this, I would suggest to remove the `additional_notes_variable` from the localisation file since it's not used anywhere else:  https://github.com/search?q=repo%3Acalcom%2Fcal.com+%22additional_notes_variable%22&type=code&p=1

Plus, adding the identifier locations to the label, would be great

**Comment by Ykumar1415** [comment]
I want to work on this issue

**Comment by Ykumar1415** [comment]
can i work ?

**Comment by hariombalhara** [comment]
Capitalisation might not be trivial as the identifier get stored in DB in the end. 
As, identifier is a variable in a sense, it doesn't make much sense to me to put effort to capitalize it(as it's an internal thing only, booker never sees it).

**Comment by a0m0rajab** [comment]
@hariombalhara if it's simple to do that, then why not to have correct grammar? (you just need to update the common.en file), 
In case if you want to do it dynamically then you need to set capitalization for the placeholder, and this would be solved for future mistakes too!

**Comment by PeerRich** [comment]
i dont think these changes make sense. closing. also closing #9338

**Comment by shm-dsgn** [comment]
if it is not needed, should i close my PR too?

**Comment by sujal12344** [comment]
I want to work on this issue..
