### ISSUE TITLE
[CAL-1860] Routing Forms: Ability to open dropdown by pressing "Enter"

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9312]
When I'm filling out a form and tabbing to the next field, I think it's natural to press "enter" and open the drop-down select, currently, we present a warning error

[615b9402-ecb1-4ee0-a9da-be61b97c8684](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/af343a14-b783-47a6-b4c0-eb730181e50c/615b9402-ecb1-4ee0-a9da-be61b97c8684)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1860](https://linear.app/calcom/issue/CAL-1860/routing-forms-ability-to-open-dropdown-by-pressing-enter)</sub>

**Comment by a0m0rajab** [comment]
How to reproduce this? 

Side note, this error is happening due to the enter acting like to send the form, I think this should not be happen unless the focus is on the send button. 

If I am not mistake repoducing this would be like the next; 
- create a new event 
- go to advanced 
- add a new question 
- chose the question as: select 
- save the settings 
- try to book this slot, you will face that issue

@shirazdole am I correct?

**Comment by rvikunwar** [comment]
@shirazdole Other than using enter button to list options. Now, on just focusing on select field or on getting to select fields using tab button, list shows up automatically we don't have do to anything in this case.
Is this fine with you ?
