### ISSUE TITLE
[CAL-1884] Make E2E test: Cancelled paid booking should be refunded.

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9370]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1884](https://linear.app/calcom/issue/CAL-1884/make-e2e-test-cancelled-paid-booking-should-be-refunded)</sub>

**Comment by chaithanya009** [comment]
Hello there!

I'm eager to take on the task of writing the test mentioned in the link [CAL-1884](https://linear.app/calcom/issue/CAL-1884/make-e2e-test-cancelled-paid-booking-should-be-refunded). However, since I don't have access to the content of the link, I'm unable to confirm if there are any specific requirements or details necessary for the task.

![screenshot-linear app-2023 06 25-19_05_44](https://github.com/calcom/cal.com/assets/104218999/9592b053-5961-4289-a89e-4cc61f251e4c)

To ensure that I can provide the most accurate and effective test, it would be greatly appreciated if you could provide a brief summary or description of the task directly in this comment. This will allow me to fully understand the requirements and proceed with writing the test promptly.

Alternatively, if it's possible to grant me access to the relevant information or resources related to this task, I would be grateful.

Thank you for your assistance, and I'm looking forward to working on this contribution!

**Comment by ologbonowiwi** [comment]
@roae @PeerRich guys, what is the step-by-step to confirm a pending payment in a test environment? working on this issue, but struggling to confirm the payment before check the refund.

**Comment by ologbonowiwi** [comment]
I got help on discord saying that I need to use Stripe webhooks to do it.

**Comment by ologbonowiwi** [comment]
@roae @PeerRich, should this test cover paid and not confirmed, paid and confirmed, or both?

**Comment by ologbonowiwi** [comment]
Hey @PeerRich @roae! I noticed many mentions and attempts on this issue, but since I didn't find anyone already working on the pipelines, I created #10243 to solve this issue. If you have any considerations about my PR, feel free to drop them there, and I'll fix it asap. Thank you!

**Comment by ologbonowiwi** [comment]
Can we close this?

It's done already @roae @PeerRich @keithwillcode

**Comment by ologbonowiwi** [comment]
this one also can be closed
