### ISSUE TITLE
[CAL-1885] Make E2E test: Can add Google Calendar

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9371]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1885](https://linear.app/calcom/issue/CAL-1885/make-e2e-test-can-add-google-calendar)</sub>

**Comment by Rahulcheerio** [comment]
Where to add Google calender @roae ? It would be helpful if you please elaborate.

**Comment by Drizer909** [comment]
where to add Google calender @roae ??

**Comment by hariombalhara** [comment]
It requires mocking of Google Calendar API at server and we haven't configured our tests to allow mocking calls initiated from server. So, this needs some groundwork first.

**Comment by Sidcode99** [comment]
hey there i'm new to open source and i'v made some changes so i wanna to make sure it is working or not and i used npm run dev and got this erorr what should i do 
![WhatsApp Image 2023-07-06 at 11 37 27 AM](https://github.com/calcom/cal.com/assets/94822955/af398b50-8347-4349-861e-62384ce1694d)

**Comment by KSSaiTeja** [comment]
is this issue still not fixed, please give me a oppurtunity to fix it.

**Comment by ologbonowiwi** [comment]
found some issues to make it work. this page appears
<img width="443" alt="image" src="https://github.com/calcom/cal.com/assets/100464352/cf9a862f-a4e2-4f20-ba33-03d06e828405">
and the link from "Learn more" is this one: https://support.google.com/accounts/answer/7675428?hl=en

According to [this article](https://adequatica.medium.com/google-authentication-with-playwright-8233b207b71a), this is on purpose cause Google doesn't want anyone logging in to their accounts with bots/via automation.

One option that we could go for is [playwright-extra](https://github.com/berstend/puppeteer-extra/tree/master/packages/playwright-extra) with [puppeteer-extra-plugin-stealth](https://github.com/berstend/puppeteer-extra/tree/master/packages/playwright-extra#-puppeteer-extra-plugin-stealth).

I created a PR with my implementation (which follows the steps that worked for me when setting up Google Calendar manually), but we'll probably need to stress it a bit more before it's done.

Possibly we'll find resistance because of this Google blocking thing, but at least we have a base test to follow

**Comment by shivamklr** [comment]
@ologbonowiwi Thank you for the contribution. It would be great if you add the packages mentioned above. Since this is an e2e test that will run on the Github CI, we want to make sure that it does not introduce any flakes. Kindly use the above-mentioned packages and let us know the results of the same.
