### ISSUE TITLE
[CAL-1925] Better handling of Conferencing apps for team event-types

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9430]
### **Current problem**

* When selecting a conferencing app as a location for a team event-type, it's very unclear whose link the conferencing app selected will use.
* For example, if we have a Round Robin event and select **Zoom**, it will use the **Zoom** link of the person who created the event type - not the person who is actually selected as the host for the call.

\----

### **The current work-around**

* A stop-gap solution we built added an option to "Use organizers default app". This goes some way to solving the problem, but it provides little or no control to admins.

\----

### **Goal / ideal outcome**

Enable an admin to be able to:

* select Zoom/Teams etc. for a team event type
* the event will use the Zoom account of the host
* In the future, they will also be able to see if there is anyone in the event type who does not have the relevant account installed/connected (and ping them to connect.)

The two apps that are most popular in these use cases are Zoom and Teams. We will focus our initial investigations around those.

We also need to factor in apps that use links like Whereby/Around/etc. One option for these, is to let individuals install the app, and in the installation process paste in their link. The other is to have the option to paste in links for each person in the event-type in the event-type settings.

\-------

### **Alex's thoughts:**

> Eventually we were looking into basically having a location dropdown per round robin attendee, so  this would be configurable to anything - you could then go to the event type as a round robin member and adjust your settings from there, default app would still be supported but only as default.

I like this idea, but also think it's worth doing a phase of design to see if there are any other possible solutions before jumping into just one.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1925](https://linear.app/calcom/issue/CAL-1925/better-handling-of-conferencing-apps-for-team-event-types)</sub>

**Comment by jeesm7** [comment]
2 years later and you still havent done this simple feature that would help us so much. smh.

I need to be able to select zoom for location for my teams links. 

We host some calls on zooms for our support team because they can use zoom to control the client's screen. 

The rest of our calls are on google meets because its simpler (sales calls mostly)

**Comment by kav** [comment]
As we approach the third anniversary of this issue it's worth noting the fix from 2023 doesn't address the issue in general or even in specific for the conferencing apps requested by the user above. I'd love this to work in the general case because in addition to having the same Zoom issue described above I've got Riverside I'd like to use for some event types.

I can open a new issue if that's the preferred workflow here.
