### ISSUE TITLE
[CAL-1962] Cal.com branding logo in New Booker, doesn't look well in Inline Embed

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9561]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/40087231-b9be-4999-9ccb-36a643474408/a062a5b7-12db-4a55-9cb1-8946bda03726)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1962](https://linear.app/calcom/issue/CAL-1962/calcom-branding-logo-in-new-booker-doesnt-look-well-in-inline-embed)</sub>

**Comment by Vivek7038** [comment]
do you want its color to be dark so that it becomes visible i ? or anything else .

**Comment by Vivek7038** [comment]
plz specify in which file this exist , i am unable to find it out

**Comment by JeroenReumkens** [comment]
@Jaibles I'm a bit unsure how we want to fix this. 
It seems logical that dark mode has a light logo, and light mode has a dark logo. But of course that doesn't work in all cases. 
Another option Hariom suggested would be the put the logo "inside" the booker, so extend the dark/light background. That would be a design change though. What are your thoughts on this? Might not be worth it to invite too much time at all, since I guess the current solution will work in 99% of the cases.

**Comment by hariombalhara** [comment]
Cool. Let's leave it as is then for now. We can revisit it later.
