### ISSUE TITLE
[CAL-2043] onboarding: dont make bio required

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9783]
[https://twitter.com/jacobmparis/status/1672975809714479104](https://twitter.com/jacobmparis/status/1672975809714479104)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/251464fb-8065-4633-8b7d-9ace7603dc7f/cb12e29a-5a6e-4ef8-a5fb-d5c518d65e6f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2043](https://linear.app/calcom/issue/CAL-2043/onboarding-dont-make-bio-required)</sub>

**Comment by jacobparis** [comment]
Oh to be clear the bio was not required and I was able to proceed without it – my comment there was just about whether getting more bookings is really the reason people set bios, rather than providing clarity around the services/information you are providing, which may reduce failed conversions. Understandably an improved conversion rate **does** mean more bookings, but at the same time if someone isn't getting enough appointments, their bio is probably not going to be the bottleneck. **This tweet was more snark than genuine critique and this issue can probably be closed**. There are no form/input issues on this page. 

BUT if we're making changes here anyway, there is a slight grammar issue

"A brief description about you and a photo really **help** you" should be "really **helps** you". The plurality of help needs to agree with both description and photo. The plural case would look like "Brief descriptions and photos really help you"

**Comment by PeerRich** [comment]
ahh cool! will fix the typo. closing

**Comment by PeerRich** [comment]
> "A brief description about you and a photo really **help** you" should be "really **helps** you". The plurality of help needs to agree with both description and photo. The plural case would look like "Brief descriptions and photos really help you"

fixed typo https://github.com/calcom/cal.com/pull/9788
