### ISSUE TITLE
[CAL-2094] loading time from cal.com/peer to cal.com/peer/15min is too high

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9924]
i dont know why it loads so slow, but it has to be a lot faster
[https://cal.com/peer](https://cal.com/peer)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2094](https://linear.app/calcom/issue/CAL-2094/loading-time-from-calcompeer-to-calcompeer15min-is-too-high)</sub>

**Comment by suman-somu** [comment]
cal.com/peer also loads very slow

**Comment by keithwillcode** [comment]
After recent performance changes, this is down to 3 seconds for me. @PeerRich What timing were you seeing before? I imagine it was around the 6-7 seconds range.

**Comment by keithwillcode** [comment]
I see a 1.11 second server load time before we even see cal.com/peer/15min and load the schedule. This will go away soon as well because we are getting rid of server-side load times on this page now.

**Comment by Entrepositive** [comment]
The load time is not conducive to business. We have clients turning away from bookings. If there's something we can do on our end to speed up calendar load times, please share. We are starting to backpedal on Cal.com as our scheduling tool.. I really enjoy this tool otherwise and would hate to have to move. Please help.

**Comment by keithwillcode** [comment]
@Entrepositive What kind of load time are you seeing for the booking page?

**Comment by Entrepositive** [comment]
Hey @keithwillcode the cal takes substantially more than one second, but less than 5 seconds to populate. Something seems to have changed in terms of loading times, both ~2 weeks ago when I wrote my original comment, and since then. It's quite a bit faster now.

Two weeks ago it had load times beyond 10 seconds... That's not effective IMO.
