### ISSUE TITLE
bug: 500 when redirected back from checkout

### ISSUE THREAD

**Issue by juliusmarminge** [calcom/cal.com#9932]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When upgrading to a premium username, I got a 500 after the checkout was finished:

<img width="926" alt="CleanShot 2023-07-04 at 22 54 40@2x" src="https://github.com/calcom/cal.com/assets/51714798/09cf8223-cab2-46da-bfe0-6eb3e333cc6c">

I still got the username though:

<img width="813" alt="CleanShot 2023-07-04 at 23 02 37@2x" src="https://github.com/calcom/cal.com/assets/51714798/9fb714c7-8aba-4a59-82c7-dca3b4d83087">

The upgrade was a sponsored one though, so not sure if that has something to do with it still going through?

### Steps to Reproduce

1. Go to account page
2. Enter a premium username you want to upgrade to
3. Go to the billing portal
4. Enter the sponsored discount code, and your card details
5. See the screenshot posted above when redirected back to Cal.

**Comment by emrysal** [comment]
That's not great @juliusmarminge - we'll look into it urgently.

**Comment by alannnc** [comment]
The error has been identified, a fix is coming shortly.

**Comment by ashish1233** [comment]
When i click "Go to billing"

<img width="1728" alt="image" src="https://github.com/calcom/cal.com/assets/20872233/02764b47-fc59-46d2-b242-40c943a435d9">


I am getting this
<img width="1728" alt="image" src="https://github.com/calcom/cal.com/assets/20872233/ae5a184b-845f-44e9-aac1-d1bd2ec0fc77">


Please correct me if i am wrong Expected behaviour should be it should take me to to the billing page right?



cc: @alannnc @emrysal
